var DATA = [
  {
    "fieldName": "Identifiers",
    "children": [
      {
        "fieldName": "ID",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:unique",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "",
        "guidance": null,
        "examples": null
      }
    ]
  },
  {
    "fieldName": "Data",
    "children": [
      {
        "fieldName": "wine label",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "year",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:nonNegativeInteger",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "1900",
        "xs:maxInclusive": "2021",
        "requirement": "required",
        "description": "",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "grape variety",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "multiple",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "schema:ItemList": {
          "Albarin": {},
          "Albarin\u0303o": {},
          "Caberet Sauvignon": {},
          "Cabernet Franc": {},
          "Callet": {},
          "Cari\u00f1ena": {},
          "Chardonnay": {},
          "Fogoneu": {},
          "Garnacha": {},
          "Garnacha Blanca": {},
          "Garnacha Tinta": {},
          "Godello": {},
          "Macabeo": {},
          "Malvasia De Sitges": {},
          "Mand\u00f3": {},
          "Merlot": {},
          "Moscatel": {},
          "Picapoll": {},
          "Picapoll Blanca": {},
          "Picapoll Negre": {},
          "Sams\u00f3": {},
          "Sams\u00f3 (Old Vineyards)": {},
          "Sauvignon Blanc": {},
          "Sumoll": {},
          "Syrah": {},
          "Tempranillo": {},
          "Tinta Fina": {},
          "Trepat": {},
          "Xarel-Lo": {}
        }
      },
      {
        "fieldName": "distributor",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "schema:ItemList": {
          "Celler De La Ribera": {},
          "Kedivi": {},
          "Underground": {}
        }
      },
      {
        "fieldName": "domain of origin",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "schema:ItemList": {
          "D.O. Conca Del Riu Anoia": {},
          "D.O. Montsant": {},
          "D.O. Conca De Barber\u00e0": {},
          "D.O. Pened\u00e8s": {},
          "D.O. Pla I Llevat ( Mallorca)": {},
          "D.O. Ribera Del Duero": {},
          "D.O. Rioja": {},
          "D.O. Pla Del Bages": {},
          "D.O. Priorat": {},
          "D.O. R\u00edas Baixas": {},
          "D.O. Ribeiro": {},
          "D.O. Rueda": {},
          "D.O. Utiel Requena": {},
          "D.O. Vt Le\u00f3n": {},
          "D.O. Cava": {},
          "D.O. Costers Del Segre": {},
          "D.O. Navarra": {},
          "D.O. R\u00edas Baixas, Valdeorras": {},
          "D.O. Ribeira Sacra": {}
        }
      },
      {
        "fieldName": "cellar",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "schema:ItemList": {
          "Abadia Gomariz": {},
          "Aroa": {},
          "Baronia Del Montsant": {},
          "Benito Santos": {},
          "Bodega Classica Rioja Hacienda L\u00f3pez de Haro": {},
          "Bodega de Bardos": {},
          "Bodegas Aragonesas Campo de Borja": {},
          "Bodegas Guimaro": {},
          "Bodegas Ostatu": {},
          "Bodegas San Valero Chardonnay Particular": {},
          "Bodegas Valderiz": {},
          "Bodegues Miquel Oliver": {},
          "Cal Pla": {},
          "Can Serra Dels Exibis": {},
          "Castillo de Maetierra Libalis": {},
          "Caves I Vins Eudald Massana Noya": {},
          "Celler Cal Pla": {},
          "Celler Carles Andreu": {},
          "Celler Sanmarti": {},
          "Celler Vega De Ribes": {},
          "Cellers Underground": {},
          "Collbaix El Moli": {},
          "Finca Santamaria": {},
          "Frank Margenat": {},
          "Jaumandreu": {},
          "Pazo de Se\u00f1or\u00e1ns": {},
          "Raventos I Blanc": {},
          "Rovellats": {},
          "Tayaimgut": {},
          "Vinyes De Castellgali": {}
        }
      },
      {
        "fieldName": "type",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "schema:ItemList": {
          "white": {},
          "rose": {},
          "red": {},
          "sparkling": {},
          "desert": {}
        }
      },
      {
        "fieldName": "alcohol content",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:decimal",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": ""
      }
    ]
  },
  {
    "fieldName": "Format",
    "children": [
      {
        "fieldName": "bottle size cl",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "schema:ItemList": {
          "75": {},
          "150": {}
        }
      },
      {
        "fieldName": "notes",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": ""
      }
    ]
  }
]