var DATA = [
  {
    "fieldName": "sample identification",
    "children": [
      {
        "fieldName": "Globally Unique ID",
        "capitalize": "",
        "ontology_id": "IoT:ID",
        "datatype": "xs:unique",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "A globally unique identifier assigned to the biological sample to link all analytes and subsamples derived from it.",
        "guidance": "Field REQUIRED for ALL sample submission. Options: IGSN- http://www.geosamples.org/getigsn ; UUID- https://www.uuidgenerator.net/",
        "examples": ""
      },
      {
        "fieldName": "Analysis/Data Type",
        "capitalize": "",
        "ontology_id": "MIXS:0000007",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Nucleic Acid Sequence Report is the root element of all MIGS/MIMS compliant reports as standardized by Genomic Standards Consortium. This field is either eukaryote,bacteria,virus,plasmid,organelle, metagenome,mimarks-survey, mimarks-specimen, metatranscriptome, single amplified genome, metagenome-assembled genome, or uncultivated viral genome",
        "guidance": "This field is constrained to contain only a set of limited terms (listed under Expected value) that indicate the types of data that were generated. Include all the data types, this field can have multiple values separated by a ;",
        "examples": "metagenome",
        "schema:ItemList": {
          "chemical speciation/mapping": {},
          "genome": {},
          "imaging- electron": {},
          "imaging- ion": {},
          "imaging- light": {},
          "lipidome": {},
          "metabolome": {},
          "molecular structure": {},
          "organic matter": {},
          "proteome": {},
          "transcriptome": {}
        }
      },
      {
        "fieldName": "Sample Type",
        "capitalize": "",
        "ontology_id": "IoT:package",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "",
        "guidance": "MIxS Package",
        "examples": ""
      },
      {
        "fieldName": "Project ID",
        "capitalize": "",
        "ontology_id": "IoT:project_ID",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "5 digit EMSL user project ID",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "Sample Name",
        "capitalize": "",
        "ontology_id": "MIXS:0001107",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "A local identifier or name that for the material sample used for extracting nucleic acids, and subsequent sequencing. It can refer either to the original material collected or to any derived sub-samples. It can have any format, but we suggest that you make it concise, unique and consistent within your lab, and as informative as possible. INSDC requires every sample name from a single Submitter to be unique. Use of a globally unique identifier for the field source_mat_id is recommended in addition to sample_name.",
        "guidance": "ID that is present on the shipped sample. Human readable.",
        "examples": "ISDsoil1"
      },
      {
        "fieldName": "Source Material ID",
        "capitalize": "",
        "ontology_id": "IoT:source_mat_ID",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "",
        "guidance": "A unique identifier assigned to an original material sample collected or to any derived sub-samples. The source material should be listed as a sample to inform details about parent material relationship.",
        "examples": ""
      }
    ]
  },
  {
    "fieldName": "required",
    "children": [
      {
        "fieldName": "Collection Date",
        "capitalize": "",
        "ontology_id": "MIXS:0000011",
        "datatype": "xs:date",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "The time of sampling, either as an instance (single point in time) or interval. In case no exact time is available, the date/time can be right truncated i.e. all of these are valid times: 2008-01-23T19:23:10+00:00; 2008-01-23T19:23:10; 2008-01-23; 2008-01; 2008; Except: 2008-01; 2008 all are ISO8601 compliant",
        "guidance": "Expected value: date and time",
        "examples": "2018-05-11T10:00:00+01:00; 2018-05-11"
      },
      {
        "fieldName": "Growth Facility",
        "capitalize": "",
        "ontology_id": "MIXS:0001043",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Type of facility where the sampled plant was grown; controlled vocabulary: growth chamber, open top chamber, glasshouse, experimental garden, field. Alternatively use Crop Ontology (CO) terms, see http://www.cropontology.org/ontology/CO_715/Crop%20Research",
        "guidance": "Type of facility or location from where the sample was harvested",
        "examples": "Growth chamber [CO_715:0000189]",
        "schema:ItemList": {
          "experimental_garden": {},
          "field": {},
          "field_incubation": {},
          "greenhouse": {},
          "growth_chamber": {},
          "lab_incubation": {},
          "open_top_chamber": {},
          "other": {}
        }
      },
      {
        "fieldName": "Replicate Number",
        "capitalize": "",
        "ontology_id": "IoT:replicate_number",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "If sending biological replicates, indicate the rep number here.",
        "guidance": "This will guide staff in ensuring your samples are block & randomized correctly",
        "examples": ""
      },
      {
        "fieldName": "Material Processing",
        "capitalize": "",
        "ontology_id": "MIXS:0000016",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "A brief description of any processing applied to the sample during or after retrieving the sample from environment, or a link to the relevant protocol(s) performed.",
        "guidance": "Expected value: text",
        "examples": "filtering of seawater, storing samples in ethanol"
      },
      {
        "fieldName": "Sample size",
        "capitalize": "",
        "ontology_id": "MIXS:0000001",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "The total amount or size (volume (ml), mass (g) or area (m2) ) of sample collected.",
        "guidance": "Expected value: measurement value|Preferred unit: millliter, gram, milligram, liter",
        "examples": "5 liter"
      },
      {
        "fieldName": "Storage temperature",
        "capitalize": "",
        "ontology_id": "MIXS:0000110",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Temperature at which sample was stored, e.g. -80 degree Celsius",
        "guidance": "Expected value: measurement value|Preferred unit: degree Celsius|Occurrence: 1|This field is used in: 15 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "-80 degree Celsius",
        "schema:ItemList": {
          "-20 degree Celsius": {},
          "-80 degree Celsius": {},
          "4 degree Celsius": {},
          "other": {},
          "room temperature": {}
        }
      },
      {
        "fieldName": "Storage Condition",
        "capitalize": "",
        "ontology_id": "MIXS:0000327",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Explain how and for how long the soil sample was stored before DNA extraction (fresh/frozen/other).",
        "guidance": "Informs how your sample was stored",
        "examples": "-20 degree Celsius freezer;P2Y10D",
        "schema:ItemList": {
          "fresh": {},
          "frozen": {},
          "lyophilized": {},
          "other": {}
        }
      },
      {
        "fieldName": "Number Technical Replicate",
        "capitalize": "",
        "ontology_id": "IoT:technical_reps",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "If sending multiple technical replicates of the same sample, indicate how many replicates are being sent",
        "guidance": "",
        "examples": ""
      }
    ]
  },
  {
    "fieldName": "required where applicable",
    "children": [
      {
        "fieldName": "altitude-meters",
        "capitalize": "",
        "ontology_id": "MIXS:0000094",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Altitude is a term used to identify heights of objects such as airplanes, space shuttles, rockets, atmospheric balloons and heights of places such as atmospheric layers and clouds. It is used to measure the height of an object which is above the earth's surface. In this context, the altitude measurement is the vertical distance between the earth's surface above sea level and the sampled position in the air",
        "guidance": "Expected value: measurement value|This field is used in: 3 packages: air, host-associated, miscellaneous natural or artificial environment",
        "examples": "100 meter"
      },
      {
        "fieldName": "depth-meters",
        "capitalize": "",
        "ontology_id": "MIXS:0000018",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "The vertical distance below local surface, e.g. for sediment or soil samples depth is measured from sediment or soil surface, respectively. Depth can be reported as an interval for subsurface samples.",
        "guidance": "When sample is collected with a ___ depth and homogenized, please report depth as a ____. (example, 0-10cm for soil collected from the surface to 10cm below and homogenized, or 10-20 for soil collected and homogenized from 10cm below the surface to 20cm).",
        "examples": "10 meter"
      },
      {
        "fieldName": "elevation-meters",
        "capitalize": "",
        "ontology_id": "MIXS:0000093",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Elevation of the sampling site is its height above a fixed reference point, most commonly the mean sea level. Elevation is mainly used when referring to points on the earth's surface, while altitude is used for points above the surface, such as an aircraft in flight or a spacecraft in orbit.",
        "guidance": "Expected value: measurement value|This field is used in: 9 packages: air, host-associated, hydrocarbon resources-cores, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, soil, water",
        "examples": "100 meter"
      },
      {
        "fieldName": "Geographical Location Name",
        "capitalize": "",
        "ontology_id": "MIXS:0000010",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "The geographical origin of the sample as defined by the country or sea name followed by specific region name. Country or sea names should be chosen from the INSDC country list (http://insdc.org/country.html), or the GAZ ontology (http://purl.bioontology.org/ontology/GAZ)",
        "guidance": "Expected value: country or sea name (INSDC or GAZ): region(GAZ), specific location name",
        "examples": "USA: Maryland, Bethesda"
      },
      {
        "fieldName": "latitude, longitude",
        "capitalize": "",
        "ontology_id": "MIXS:0000009",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "The geographical origin of the sample as defined by latitude and longitude. The values should be reported in decimal degrees and in WGS84 system",
        "guidance": "Expected value: decimal degrees,  limit to 8 decimal points",
        "examples": "50.586825 6.408977"
      },
      {
        "fieldName": "Other",
        "capitalize": "",
        "ontology_id": "IoT:other",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "",
        "guidance": "Other details about your sample that you feel can't be accurately represented in the available columns.",
        "examples": ""
      },
      {
        "fieldName": "sample collection device",
        "capitalize": "",
        "ontology_id": "IoT:samp_collect_device",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "",
        "guidance": "Report dimensions and details when applicable",
        "examples": ""
      },
      {
        "fieldName": "Size Fraction- Filter Type",
        "capitalize": "",
        "ontology_id": "MIXS:0000017",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Filtering pore size used in sample preparation",
        "guidance": "Expected value: filter size value range",
        "examples": "0-0.22 micrometer"
      },
      {
        "fieldName": "size-fraction lower threshold",
        "capitalize": "",
        "ontology_id": "MIXS:0000735",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Refers to the mesh/pore size used to pre-filter/pre-sort the sample. Materials larger than the size threshold are excluded from the sample",
        "guidance": "Expected value: value|Preferred unit: micrometer|Occurrence: 1|This field is used uniquely in: water",
        "examples": "0.2 micrometer"
      },
      {
        "fieldName": "size-fraction upper threshold",
        "capitalize": "",
        "ontology_id": "MIXS:0000736",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Refers to the mesh/pore size used to retain the sample. Materials smaller than the size threshold are excluded from the sample",
        "guidance": "Expected value: value|Preferred unit: micrometer|Occurrence: 1|This field is used uniquely in: water",
        "examples": "20 micrometer"
      }
    ]
  },
  {
    "fieldName": "treatment",
    "children": [
      {
        "fieldName": "air temperature regimen treatment",
        "capitalize": "",
        "ontology_id": "MIXS:0000551",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Information about treatment involving an exposure to varying temperatures; should include the temperature, treatment regimen including how many times the treatment was repeated, how long each treatment lasted, and the start and end time of the entire treatment; can include different temperature regimens",
        "guidance": "Expected value: temperature value;treatment interval and duration|Preferred unit: meter|Occurrence: m|This field is used uniquely in: plant-associated",
        "examples": "25 degree Celsius;R2/2018-05-11T14:30/2018-05-11T19:30/P1H30M"
      },
      {
        "fieldName": "biotic regimen/addition treatment",
        "capitalize": "",
        "ontology_id": "MIXS:0001038",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Information about treatment(s) involving use of biotic factors, such as bacteria, viruses or fungi.",
        "guidance": "Expected value: free text|Occurrence: 1|This field is used uniquely in: plant-associated",
        "examples": "sample inoculated with Rhizobium spp. Culture"
      },
      {
        "fieldName": "chemical administration/addition treatment",
        "capitalize": "",
        "ontology_id": "MIXS:0000751",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "List of chemical compounds administered to the host or site where sampling occurred, and when (e.g. Antibiotics, n fertilizer, air filter); can include multiple compounds. For chemical entities of biological interest ontology (chebi) (v 163), http://purl.bioontology.org/ontology/chebi",
        "guidance": "Expected value: CHEBI;timestamp|Occurrence: m|This field is used in: 13 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "agar [CHEBI:2509];2018-05-11T20:00Z"
      },
      {
        "fieldName": "climate environment treatment",
        "capitalize": "",
        "ontology_id": "MIXS:0001040",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Treatment involving an exposure to a particular climate; treatment regimen including how many times the treatment was repeated, how long each treatment lasted, and the start and end time of the entire treatment; can include multiple climates",
        "guidance": "Expected value: climate name;treatment interval and duration|Occurrence: m|This field is used uniquely in: plant-associated",
        "examples": "tropical climate;R2/2018-05-11T14:30/2018-05-11T19:30/P1H30M"
      },
      {
        "fieldName": "gas environment/exposure treatment",
        "capitalize": "",
        "ontology_id": "MIXS:0000558",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Use of conditions with differing gaseous environments; should include the name of gaseous compound, amount administered, treatment duration, interval and total experimental duration; can include multiple gaseous environment regimens",
        "guidance": "Expected value: gaseous compound name;gaseous compound amount;treatment interval and duration|Preferred unit: micromole per liter|Occurrence: m|This field is used uniquely in: plant-associated",
        "examples": "nitric oxide;0.5 micromole per liter;R2/2018-05-11T14:30/2018-05-11T19:30/P1H30M"
      },
      {
        "fieldName": "humidity regimen/addition treatment",
        "capitalize": "",
        "ontology_id": "MIXS:0000568",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Information about treatment involving an exposure to varying degree of humidity; information about treatment involving use of growth hormones; should include amount of humidity administered, treatment regimen including how many times the treatment was repeated, how long each treatment lasted, and the start and end time of the entire treatment; can include multiple regimens",
        "guidance": "Expected value: humidity value;treatment interval and duration|Preferred unit: gram per cubic meter|Occurrence: m|This field is used uniquely in: plant-associated",
        "examples": "25 gram per cubic meter;R2/2018-05-11T14:30/2018-05-11T19:30/P1H30M"
      },
      {
        "fieldName": "isotope exposure/addition treatment",
        "capitalize": "",
        "ontology_id": "IoT:isotope_exposure",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "light regimen treatment",
        "capitalize": "",
        "ontology_id": "MIXS:0000569",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Information about treatment(s) involving exposure to light, including both light intensity and quality.",
        "guidance": "Expected value: exposure type;light intensity;light quality|Preferred unit: lux; micrometer, nanometer, angstrom|Occurrence: 1|This field is used uniquely in: plant-associated",
        "examples": "incandescant light;10 lux;450 nanometer"
      },
      {
        "fieldName": "treatment-other details",
        "capitalize": "",
        "ontology_id": "IoT:other_treatment",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "watering regimen/schedule treatment",
        "capitalize": "",
        "ontology_id": "MIXS:0000591",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Information about treatment involving an exposure to watering frequencies, treatment regimen including how many times the treatment was repeated, how long each treatment lasted, and the start and end time of the entire treatment; can include multiple regimens",
        "guidance": "Expected value: measurement value;treatment interval and duration|Preferred unit: milliliter, liter|Occurrence: m|This field is used uniquely in: plant-associated",
        "examples": "1 liter;R2/2018-05-11T14:30/2018-05-11T19:30/P1H30M"
      }
    ]
  },
  {
    "fieldName": "optional",
    "children": [
      {
        "fieldName": "alkalinity",
        "capitalize": "",
        "ontology_id": "MIXS:0000421",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Alkalinity, the ability of a solution to neutralize acids to the equivalence point of carbonate or bicarbonate",
        "guidance": "Expected value: measurement value|Preferred unit: milliequivalent per liter, milligram per liter|Occurrence: 1|This field is used in: 7 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, wastewater_sludge, water",
        "examples": "50 milligram per liter"
      },
      {
        "fieldName": "alkalinity method",
        "capitalize": "",
        "ontology_id": "MIXS:0000298",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Method used for alkalinity measurement",
        "guidance": "Expected value: description of method|Occurrence: 1|This field is used in: 3 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, water",
        "examples": "titration"
      },
      {
        "fieldName": "alkyl diethers",
        "capitalize": "",
        "ontology_id": "MIXS:0000490",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of alkyl diethers",
        "guidance": "Expected value: measurement value|Preferred unit: mole per liter|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "0.005 mole per liter"
      },
      {
        "fieldName": "aminopeptidase activity",
        "capitalize": "",
        "ontology_id": "MIXS:0000172",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of aminopeptidase activity",
        "guidance": "Expected value: measurement value|Preferred unit: mole per liter per hour|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "0.269 mole per liter per hour"
      },
      {
        "fieldName": "ammonium",
        "capitalize": "",
        "ontology_id": "MIXS:0000427",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of ammonium in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter, milligram per liter, parts per million|Occurrence: 1|This field is used in: 6 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "1.5 milligram per liter"
      },
      {
        "fieldName": "atmospheric data",
        "capitalize": "",
        "ontology_id": "MIXS:0001097",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of atmospheric data; can include multiple data",
        "guidance": "Expected value: atmospheric data name;measurement value|Occurrence: m|This field is used uniquely in: water",
        "examples": "wind speed;9 knots"
      },
      {
        "fieldName": "bacterial production",
        "capitalize": "",
        "ontology_id": "MIXS:0000683",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Bacterial production in the water column measured by isotope uptake",
        "guidance": "Expected value: measurement value|Preferred unit: milligram per cubic meter per day|Occurrence: 1|This field is used uniquely in: water",
        "examples": "5 milligram per cubic meter per day"
      },
      {
        "fieldName": "bacterial respiration",
        "capitalize": "",
        "ontology_id": "MIXS:0000684",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of bacterial respiration in the water column",
        "guidance": "Expected value: measurement value|Preferred unit: milligram per cubic meter per day, micromole oxygen per liter per hour|Occurrence: 1|This field is used uniquely in: water",
        "examples": "300 micromole oxygen per liter per hour"
      },
      {
        "fieldName": "bacterial carbon production",
        "capitalize": "",
        "ontology_id": "MIXS:0000173",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of bacterial carbon production",
        "guidance": "Expected value: measurement value|Preferred unit: nanogram per hour|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "2.53 microgram per liter per hour"
      },
      {
        "fieldName": "biomass",
        "capitalize": "",
        "ontology_id": "MIXS:0000174",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Amount of biomass; should include the name for the part of biomass measured, e.g. Microbial, total. Can include multiple measurements",
        "guidance": "Expected value: biomass type;measurement value|Preferred unit: ton, kilogram, gram|Occurrence: m|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "total;20 gram"
      },
      {
        "fieldName": "bishomohopanol",
        "capitalize": "",
        "ontology_id": "MIXS:0000175",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of bishomohopanol",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter, microgram per gram|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "14 microgram per liter"
      },
      {
        "fieldName": "bromide",
        "capitalize": "",
        "ontology_id": "MIXS:0000176",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of bromide",
        "guidance": "Expected value: measurement value|Preferred unit: parts per million|Occurrence: 1|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "0.05 parts per million"
      },
      {
        "fieldName": "calcium",
        "capitalize": "",
        "ontology_id": "MIXS:0000432",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of calcium in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: milligram per liter, micromole per liter, parts per million|Occurrence: 1|This field is used in: 6 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "0.2 micromole per liter"
      },
      {
        "fieldName": "carbon/nitrogen ratio",
        "capitalize": "",
        "ontology_id": "MIXS:0000310",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Ratio of amount or concentrations of carbon to nitrogen",
        "guidance": "Expected value: measurement value|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "0.417361111"
      },
      {
        "fieldName": "chloride",
        "capitalize": "",
        "ontology_id": "MIXS:0000429",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of chloride in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: milligram per liter, parts per million|Occurrence: 1|This field is used in: 6 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "5000 milligram per liter"
      },
      {
        "fieldName": "chlorophyll",
        "capitalize": "",
        "ontology_id": "MIXS:0000177",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of chlorophyll",
        "guidance": "Expected value: measurement value|Preferred unit: milligram per cubic meter, microgram per liter|Occurrence: 1|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "5 milligram per cubic meter"
      },
      {
        "fieldName": "conductivity",
        "capitalize": "",
        "ontology_id": "MIXS:0000692",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Electrical conductivity of water",
        "guidance": "Expected value: measurement value|Preferred unit: milliSiemens per centimeter|Occurrence: 1|This field is used uniquely in: water",
        "examples": "10 milliSiemens per centimeter"
      },
      {
        "fieldName": "density",
        "capitalize": "",
        "ontology_id": "MIXS:0000435",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Density of the sample, which is its mass per unit volume (aka volumetric mass density)",
        "guidance": "Expected value: measurement value|Preferred unit: gram per cubic meter, gram per cubic centimeter|Occurrence: 1|This field is used in: 5 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, miscellaneous natural or artificial environment, sediment, water",
        "examples": "1000 kilogram per cubic meter"
      },
      {
        "fieldName": "diether lipids",
        "capitalize": "",
        "ontology_id": "MIXS:0000178",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of diether lipids; can include multiple types of diether lipids",
        "guidance": "Expected value: diether lipid name;measurement value|Preferred unit: nanogram per liter|Occurrence: m|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "0.2 nanogram per liter"
      },
      {
        "fieldName": "dissolved carbon dioxide",
        "capitalize": "",
        "ontology_id": "MIXS:0000436",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of dissolved carbon dioxide in the sample or liquid portion of the sample",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter, milligram per liter|Occurrence: 1|This field is used in: 6 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "5 milligram per liter"
      },
      {
        "fieldName": "dissolved hydrogen",
        "capitalize": "",
        "ontology_id": "MIXS:0000179",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of dissolved hydrogen",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter|Occurrence: 1|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "0.3 micromole per liter"
      },
      {
        "fieldName": "dissolved inorganic carbon",
        "capitalize": "",
        "ontology_id": "MIXS:0000434",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Dissolved inorganic carbon concentration in the sample, typically measured after filtering the sample using a 0.45 micrometer filter",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter, milligram per liter, parts per million|Occurrence: 1|This field is used in: 6 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "2059 micromole per kilogram"
      },
      {
        "fieldName": "dissolved inorganic nitrogen",
        "capitalize": "",
        "ontology_id": "MIXS:0000698",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of dissolved inorganic nitrogen",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter, micromole per liter|Occurrence: 1|This field is used uniquely in: water",
        "examples": "761 micromole per liter"
      },
      {
        "fieldName": "Concentration of dissolved inorganic phosphorus in the sample",
        "capitalize": "",
        "ontology_id": "MIXS:0000106",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of dissolved inorganic phosphorus in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter, milligram per liter, parts per million|Occurrence: 1|This field is used in: 3 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, water",
        "examples": "56.5 micromole per liter"
      },
      {
        "fieldName": "dissolved organic carbon",
        "capitalize": "",
        "ontology_id": "MIXS:0000433",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of dissolved organic carbon in the sample, liquid portion of the sample, or aqueous phase of the fluid",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter, milligram per liter|Occurrence: 1|This field is used in: 5 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, sediment, water",
        "examples": "197 micromole per liter"
      },
      {
        "fieldName": "dissolved organic nitrogen",
        "capitalize": "",
        "ontology_id": "MIXS:0000162",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Dissolved organic nitrogen concentration measured as; total dissolved nitrogen - NH4 - NO3 - NO2",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter, milligram per liter|Occurrence: 1|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "0.05 micromole per liter"
      },
      {
        "fieldName": "dissolved oxygen",
        "capitalize": "",
        "ontology_id": "MIXS:0000119",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of dissolved oxygen",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per kilogram, milligram per liter|Occurrence: 1|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "175 micromole per kilogram"
      },
      {
        "fieldName": "downward PAR",
        "capitalize": "",
        "ontology_id": "MIXS:0000703",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Visible waveband radiance and irradiance measurements in the water column",
        "guidance": "Expected value: measurement value|Preferred unit: microEinstein per square meter per second, microEinstein per square centimeter per second|Occurrence: 1|This field is used uniquely in: water",
        "examples": "28.71 microEinstein per square meter per second"
      },
      {
        "fieldName": "fluorescence",
        "capitalize": "",
        "ontology_id": "MIXS:0000704",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Raw or converted fluorescence of water",
        "guidance": "Expected value: measurement value|Preferred unit: milligram chlorophyll a per cubic meter, volts|Occurrence: 1|This field is used uniquely in: water",
        "examples": "2.5 volts"
      },
      {
        "fieldName": "glucosidase activity",
        "capitalize": "",
        "ontology_id": "MIXS:0000137",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of glucosidase activity",
        "guidance": "Expected value: measurement value|Preferred unit: mol per liter per hour|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "5 mol per liter per hour"
      },
      {
        "fieldName": "light intensity",
        "capitalize": "",
        "ontology_id": "MIXS:0000706",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of light intensity",
        "guidance": "Expected value: measurement value|Preferred unit: lux|Occurrence: 1|This field is used uniquely in: water",
        "examples": "0.3 lux"
      },
      {
        "fieldName": "magnesium",
        "capitalize": "",
        "ontology_id": "MIXS:0000431",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of magnesium in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: mole per liter, milligram per liter, parts per million, micromole per kilogram|Occurrence: 1|This field is used in: 5 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, sediment, water",
        "examples": "52.8 micromole per kilogram"
      },
      {
        "fieldName": "mean friction velocity",
        "capitalize": "",
        "ontology_id": "MIXS:0000498",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of mean friction velocity",
        "guidance": "Expected value: measurement value|Preferred unit: meter per second|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "0.5 meter per second"
      },
      {
        "fieldName": "mean peak friction velocity",
        "capitalize": "",
        "ontology_id": "MIXS:0000502",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of mean peak friction velocity",
        "guidance": "Expected value: measurement value|Preferred unit: meter per second|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "1 meter per second"
      },
      {
        "fieldName": "miscellaneous parameter",
        "capitalize": "",
        "ontology_id": "MIXS:0000752",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Any other measurement performed or parameter collected, that is not listed here",
        "guidance": "Expected value: parameter name;measurement value|Occurrence: m|This field is used in: 16 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, soil, wastewater_sludge, water",
        "examples": "Bicarbonate ion concentration;2075 micromole per kilogram"
      },
      {
        "fieldName": "n-alkanes",
        "capitalize": "",
        "ontology_id": "MIXS:0000503",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of n-alkanes; can include multiple n-alkanes",
        "guidance": "Expected value: n-alkane name;measurement value|Preferred unit: micromole per liter|Occurrence: m|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "n-hexadecane;100 milligram per liter"
      },
      {
        "fieldName": "nitrate",
        "capitalize": "",
        "ontology_id": "MIXS:0000425",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of nitrate in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter, milligram per liter, parts per million|Occurrence: 1|This field is used in: 7 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, wastewater_sludge, water",
        "examples": "65 micromole per liter"
      },
      {
        "fieldName": "nitrite",
        "capitalize": "",
        "ontology_id": "MIXS:0000426",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of nitrite in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter, milligram per liter, parts per million|Occurrence: 1|This field is used in: 6 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "0.5 micromole per liter"
      },
      {
        "fieldName": "nitrogen",
        "capitalize": "",
        "ontology_id": "MIXS:0000504",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of nitrogen (total)",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter|Occurrence: 1|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "4.2 micromole per liter"
      },
      {
        "fieldName": "organic carbon",
        "capitalize": "",
        "ontology_id": "MIXS:0000508",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of organic carbon",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter|Occurrence: 1|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "1.5 microgram per liter"
      },
      {
        "fieldName": "organic matter",
        "capitalize": "",
        "ontology_id": "MIXS:0000204",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of organic matter",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter|Occurrence: 1|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "1.75 milligram per cubic meter"
      },
      {
        "fieldName": "organic nitrogen",
        "capitalize": "",
        "ontology_id": "MIXS:0000205",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of organic nitrogen",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter|Occurrence: 1|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "4 micromole per liter"
      },
      {
        "fieldName": "organism count",
        "capitalize": "",
        "ontology_id": "MIXS:0000103",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Total cell count of any organism (or group of organisms) per gram, volume or area of sample, should include name of organism followed by count. The method that was used for the enumeration (e.g. qPCR, atp, mpn, etc.) Should also be provided. (example: total prokaryotes; 3.5e7 cells per ml; qpcr)",
        "guidance": "Expected value: organism name;measurement value;enumeration|Preferred unit: number of cells per cubic meter, number of cells per milliliter, number of cells per cubic centimeter|Occurrence: m|This field is used in: 16 packages: air, built environment, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "total prokaryotes;3.5e7 cells per milliliter;qPCR",
        "schema:ItemList": {
          "ATP": {},
          "MPN": {},
          "other": {}
        }
      },
      {
        "fieldName": "oxygenation status of sample",
        "capitalize": "",
        "ontology_id": "MIXS:0000753",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Oxygenation status of sample",
        "guidance": "Expected value: enumeration|Occurrence: 1|This field is used in: 15 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "aerobic",
        "schema:ItemList": {
          "aerobic": {},
          "anaerobic": {},
          "anoxic": {},
          "facultative": {},
          "microaerophilic": {},
          "microanaerobe": {},
          "obligate aerobe": {},
          "obligate anaerobe": {}
        }
      },
      {
        "fieldName": "particulate organic carbon",
        "capitalize": "",
        "ontology_id": "MIXS:0000515",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of particulate organic carbon",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "1.92 micromole per liter"
      },
      {
        "fieldName": "particulate organic nitrogen",
        "capitalize": "",
        "ontology_id": "MIXS:0000719",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of particulate organic nitrogen",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter, micromole per liter|Occurrence: 1|This field is used uniquely in: water",
        "examples": "0.3 micromole per liter"
      },
      {
        "fieldName": "perturbation",
        "capitalize": "",
        "ontology_id": "MIXS:0000754",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Type of perturbation, e.g. chemical administration, physical disturbance, etc., coupled with perturbation regimen including how many times the perturbation was repeated, how long each perturbation lasted, and the start and end time of the entire perturbation period; can include multiple perturbation types",
        "guidance": "Expected value: perturbation type name;perturbation interval and duration|Occurrence: m|This field is used in: 13 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "antibiotic addition;R2/2018-05-11T14:30Z/2018-05-11T19:30Z/P1H30M"
      },
      {
        "fieldName": "petroleum hydrocarbon",
        "capitalize": "",
        "ontology_id": "MIXS:0000516",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of petroleum hydrocarbon",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "0.05 micromole per liter"
      },
      {
        "fieldName": "pH",
        "capitalize": "",
        "ontology_id": "MIXS:0001001",
        "datatype": "xs:decimal",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Ph measurement of the sample, or liquid portion of sample, or aqueous phase of the fluid",
        "guidance": "Expected value: measurement value|Occurrence: 1|This field is used in: 8 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, soil, wastewater_sludge, water",
        "examples": "7.2"
      },
      {
        "fieldName": "pH method",
        "capitalize": "",
        "ontology_id": "MIXS:0001106",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Reference or method used in determining ph",
        "guidance": "Expected value: PMID,DOI or url|Occurrence: 1|This field is used uniquely in: soil",
        "examples": ""
      },
      {
        "fieldName": "phaeopigments",
        "capitalize": "",
        "ontology_id": "MIXS:0000180",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of phaeopigments; can include multiple phaeopigments",
        "guidance": "Expected value: phaeopigment name;measurement value|Preferred unit: milligram per cubic meter|Occurrence: m|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "2.5 milligram per cubic meter"
      },
      {
        "fieldName": "phosphate",
        "capitalize": "",
        "ontology_id": "MIXS:0000505",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of phosphate",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter|Occurrence: 1|This field is used in: 5 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, wastewater_sludge, water",
        "examples": "0.7 micromole per liter"
      },
      {
        "fieldName": "phospholipid fatty acid",
        "capitalize": "",
        "ontology_id": "MIXS:0000181",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of phospholipid fatty acids; can include multiple values",
        "guidance": "Expected value: phospholipid fatty acid name;measurement value|Preferred unit: mole per gram, mole per liter|Occurrence: m|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "2.98 milligram per liter"
      },
      {
        "fieldName": "photon flux",
        "capitalize": "",
        "ontology_id": "MIXS:0000725",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of photon flux",
        "guidance": "Expected value: measurement value|Preferred unit: number of photons per second per unit area|Occurrence: 1|This field is used uniquely in: water",
        "examples": "3.926 micromole photons per second per square meter"
      },
      {
        "fieldName": "potassium",
        "capitalize": "",
        "ontology_id": "MIXS:0000430",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of potassium in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: milligram per liter, parts per million|Occurrence: 1|This field is used in: 6 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "463 milligram per liter"
      },
      {
        "fieldName": "Practice Target",
        "capitalize": "",
        "ontology_id": "IoT:practice_method-dev",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "If your sample is being sent as a test or practice sample, indicate the target test or what this test sample is meant to resolve.",
        "guidance": "Example, if it's unclear if lyophilizing will affect your results, so you're sending a lyophilized and not lyophilized sample, the Practice Target would be \"lyophilization affect, dry (or wet)\"",
        "examples": ""
      },
      {
        "fieldName": "pressure",
        "capitalize": "",
        "ontology_id": "MIXS:0000412",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Pressure to which the sample is subject to, in atmospheres",
        "guidance": "Expected value: measurement value|Preferred unit: atmosphere|Occurrence: 1|This field is used in: 6 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "50 atmosphere"
      },
      {
        "fieldName": "primary production",
        "capitalize": "",
        "ontology_id": "MIXS:0000728",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of primary production, generally measured as isotope uptake",
        "guidance": "Expected value: measurement value|Preferred unit: milligram per cubic meter per day, gram per square meter per day|Occurrence: 1|This field is used uniquely in: water",
        "examples": "100 milligram per cubic meter per day"
      },
      {
        "fieldName": "redox potential",
        "capitalize": "",
        "ontology_id": "MIXS:0000182",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Redox potential, measured relative to a hydrogen cell, indicating oxidation or reduction potential",
        "guidance": "Expected value: measurement value|Preferred unit: millivolt|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "300 millivolt"
      },
      {
        "fieldName": "salinity",
        "capitalize": "",
        "ontology_id": "MIXS:0000183",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The total concentration of all dissolved salts in a liquid or solid sample. While salinity can be measured by a complete chemical analysis, this method is difficult and time consuming. More often, it is instead derived from the conductivity measurement. This is known as practical salinity. These derivations compare the specific conductance of the sample to a salinity standard such as seawater.",
        "guidance": "Expected value: measurement value|Preferred unit: practical salinity unit, percentage|Occurrence: 1|This field is used in: 15 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "25 practical salinity unit"
      },
      {
        "fieldName": "silicate",
        "capitalize": "",
        "ontology_id": "MIXS:0000184",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of silicate",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter|Occurrence: 1|This field is used in: 4 packages: microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "0.05 micromole per liter"
      },
      {
        "fieldName": "sodium",
        "capitalize": "",
        "ontology_id": "MIXS:0000428",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Sodium concentration in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: milligram per liter, parts per million|Occurrence: 1|This field is used in: 7 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, wastewater_sludge, water",
        "examples": "10.5 milligram per liter"
      },
      {
        "fieldName": "soluble reactive phosphorus",
        "capitalize": "",
        "ontology_id": "MIXS:0000738",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of soluble reactive phosphorus",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter, milligram per liter, parts per million|Occurrence: 1|This field is used uniquely in: water",
        "examples": "0.1 milligram per liter"
      },
      {
        "fieldName": "sulfate",
        "capitalize": "",
        "ontology_id": "MIXS:0000423",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of sulfate in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter, milligram per liter, parts per million|Occurrence: 1|This field is used in: 6 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "5 micromole per liter"
      },
      {
        "fieldName": "sulfide",
        "capitalize": "",
        "ontology_id": "MIXS:0000424",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of sulfide in the sample",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter, milligram per liter, parts per million|Occurrence: 1|This field is used in: 6 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, sediment, water",
        "examples": "2 micromole per liter"
      },
      {
        "fieldName": "suspended particulate matter",
        "capitalize": "",
        "ontology_id": "MIXS:0000741",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Concentration of suspended particulate matter",
        "guidance": "Expected value: measurement value|Preferred unit: milligram per liter|Occurrence: 1|This field is used uniquely in: water",
        "examples": "0.5 milligram per liter"
      },
      {
        "fieldName": "temperature",
        "capitalize": "",
        "ontology_id": "MIXS:0000113",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Temperature of the sample at the time of sampling.",
        "guidance": "Expected value: measurement value|Preferred unit: degree Celsius|This field is used in: 15 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "25 degree Celsius"
      },
      {
        "fieldName": "tidal stage",
        "capitalize": "",
        "ontology_id": "MIXS:0000750",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Stage of tide",
        "guidance": "Expected value: enumeration|Occurrence: 1|This field is used in: 2 packages: sediment, water",
        "examples": "high tide",
        "schema:ItemList": {
          "ebb tide": {},
          "flood tide": {},
          "high tide": {},
          "low tide": {}
        }
      },
      {
        "fieldName": "total depth of water column",
        "capitalize": "",
        "ontology_id": "MIXS:0000634",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of total depth of water column",
        "guidance": "Expected value: measurement value|Preferred unit: meter|Occurrence: 1|This field is used in: 2 packages: sediment, water",
        "examples": "500 meter"
      },
      {
        "fieldName": "total dissolved nitrogen",
        "capitalize": "",
        "ontology_id": "MIXS:0000744",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Total dissolved nitrogen concentration, reported as nitrogen, measured by: total dissolved nitrogen = NH4 + NO3NO2 + dissolved organic nitrogen",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter|Occurrence: 1|This field is used uniquely in: water",
        "examples": "40 microgram per liter"
      },
      {
        "fieldName": "total inorganic nitrogen",
        "capitalize": "",
        "ontology_id": "MIXS:0000745",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Total inorganic nitrogen content",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter|Occurrence: 1|This field is used uniquely in: water",
        "examples": "40 microgram per liter"
      },
      {
        "fieldName": "total nitrogen concentration",
        "capitalize": "",
        "ontology_id": "MIXS:0000102",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Total nitrogen concentration of water samples, calculated by: total nitrogen = total dissolved nitrogen + particulate nitrogen. Can also be measured without filtering, reported as nitrogen",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter, micromole per liter, milligram per liter|Occurrence: 1|This field is used in: 4 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, wastewater_sludge, water",
        "examples": "50 micromole per liter"
      },
      {
        "fieldName": "total particulate carbon",
        "capitalize": "",
        "ontology_id": "MIXS:0000747",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Total particulate carbon content",
        "guidance": "Expected value: measurement value|Preferred unit: microgram per liter, micromole per liter|Occurrence: 1|This field is used uniquely in: water",
        "examples": "35 micromole per liter"
      },
      {
        "fieldName": "total phosphorus",
        "capitalize": "",
        "ontology_id": "MIXS:0000117",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Total phosphorus concentration in the sample, calculated by: total phosphorus = total dissolved phosphorus + particulate phosphorus",
        "guidance": "Expected value: measurement value|Preferred unit: micromole per liter, milligram per liter, parts per million|Occurrence: 1|This field is used in: 3 packages: hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, water",
        "examples": "0.03 milligram per liter"
      },
      {
        "fieldName": "turbidity",
        "capitalize": "",
        "ontology_id": "MIXS:0000191",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measure of the amount of cloudiness or haziness in water caused by individual particles",
        "guidance": "Expected value: measurement value|Preferred unit: formazin turbidity unit, formazin nephelometric units|Occurrence: 1|This field is used in: 3 packages: microbial mat_biofilm, sediment, water",
        "examples": "0.3 nephelometric turbidity units"
      },
      {
        "fieldName": "water current",
        "capitalize": "",
        "ontology_id": "MIXS:0000203",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of magnitude and direction of flow within a fluid",
        "guidance": "Expected value: measurement value|Preferred unit: cubic meter per second, knots|Occurrence: 1|This field is used in: 2 packages: miscellaneous natural or artificial environment, water",
        "examples": "10 cubic meter per second"
      }
    ]
  }
]