const DATA = [
  {
    fieldName: 'Database Identifiers',
    children: [
      {
        fieldName: 'specimen collector sample ID',
        vocabulary: {},
      },
      {
        fieldName: 'PHAC sample ID',
        vocabulary: {},
      },
      {
        fieldName: 'IRIDA sample name',
        vocabulary: {},
      },
      {
        fieldName: 'umbrella bioproject accession',
        vocabulary: {
          'PRJNA623807': {},
        },
      },
      {
        fieldName: 'bioproject accession',
        vocabulary: {},
      },
      {
        fieldName: 'biosample accession',
        vocabulary: {},
      },
      {
        fieldName: 'SRA accession',
        vocabulary: {},
      },
      {
        fieldName: 'GenBank accession',
        vocabulary: {},
      },
      {
        fieldName: 'GISAID accession',
        vocabulary: {},
      },
    ],
  },
  {
    fieldName: 'Sample collection and processing',
    children: [
      {
        fieldName: 'sample collected by',
        vocabulary: {},
      },
      {
        fieldName: 'sample collector contact email',
        vocabulary: {},
      },
      {
        fieldName: 'sample collector contact address',
        vocabulary: {},
      },
      {
        fieldName: 'sequence submitted by',
        vocabulary: {},
      },
      {
        fieldName: 'sequence submitter contact email',
        vocabulary: {},
      },
      {
        fieldName: 'sequence submitter contact address',
        vocabulary: {},
      },
      {
        fieldName: 'sample collection date',
        vocabulary: {},
      },
      {
        fieldName: 'geo_loc_name (country)',
        vocabulary: {
          'Afghanistan': {},
          'Albania': {},
          'Algeria': {},
          'American Samoa': {},
          'Andorra': {},
          'Angola': {},
          'Anguilla': {},
          'Antarctica': {},
          'Antigua and Barbuda': {},
          'Argentina': {},
          'Armenia': {},
          'Aruba': {},
          'Ashmore and Cartier Islands': {},
          'Australia': {},
          'Austria': {},
          'Azerbaijan': {},
          'Bahamas': {},
          'Bahrain': {},
          'Baker Island': {},
          'Bangladesh': {},
          'Barbados': {},
          'Bassas da India': {},
          'Belarus': {},
          'Belgium': {},
          'Belize': {},
          'Benin': {},
          'Bermuda': {},
          'Bhutan': {},
          'Bolivia': {},
          'Borneo': {},
          'Bosnia and Herzegovina': {},
          'Botswana': {},
          'Bouvet Island': {},
          'Brazil': {},
          'British Virgin Islands': {},
          'Brunei': {},
          'Bulgaria': {},
          'Burkina Faso': {},
          'Burundi': {},
          'Cambodia': {},
          'Cameroon': {},
          'Canada': {},
          'Cape Verde': {},
          'Cayman Islands': {},
          'Central African Republic': {},
          'Chad': {},
          'Chile': {},
          'China': {},
          'Christmas Island': {},
          'Clipperton Island': {},
          'Cocos Islands': {},
          'Colombia': {},
          'Comoros': {},
          'Cook Islands': {},
          'Coral Sea Islands': {},
          'Costa Rica': {},
          'Cote d\'Ivoire': {},
          'Croatia': {},
          'Cuba': {},
          'Curacao': {},
          'Cyprus': {},
          'Czech Republic': {},
          'Democratic Republic of the Congo': {},
          'Denmark': {},
          'Djibouti': {},
          'Dominica': {},
          'Dominican Republic': {},
          'Ecuador': {},
          'Egypt': {},
          'El Salvador': {},
          'Equatorial Guinea': {},
          'Eritrea': {},
          'Estonia': {},
          'Eswatini': {},
          'Ethiopia': {},
          'Europa Island': {},
          'Falkland Islands (Islas Malvinas)': {},
          'Faroe Islands': {},
          'Fiji': {},
          'Finland': {},
          'France': {},
          'French Guiana': {},
          'French Polynesia': {},
          'French Southern and Antarctic Lands': {},
          'Gabon': {},
          'Gambia': {},
          'Gaza Strip': {},
          'Georgia': {},
          'Germany': {},
          'Ghana': {},
          'Gibraltar': {},
          'Glorioso Islands': {},
          'Greece': {},
          'Greenland': {},
          'Grenada': {},
          'Guadeloupe': {},
          'Guam': {},
          'Guatemala': {},
          'Guernsey': {},
          'Guinea': {},
          'Guinea-Bissau': {},
          'Guyana': {},
          'Haiti': {},
          'Heard Island and McDonald Islands': {},
          'Honduras': {},
          'Hong Kong': {},
          'Howland Island': {},
          'Hungary': {},
          'Iceland': {},
          'India': {},
          'Indonesia': {},
          'Iran': {},
          'Iraq': {},
          'Ireland': {},
          'Isle of Man': {},
          'Israel': {},
          'Italy': {},
          'Jamaica': {},
          'Jan Mayen': {},
          'Japan': {},
          'Jarvis Island': {},
          'Jersey': {},
          'Johnston Atoll': {},
          'Jordan': {},
          'Juan de Nova Island': {},
          'Kazakhstan': {},
          'Kenya': {},
          'Kerguelen Archipelago': {},
          'Kingman Reef': {},
          'Kiribati': {},
          'Kosovo': {},
          'Kuwait': {},
          'Kyrgyzstan': {},
          'Laos': {},
          'Latvia': {},
          'Lebanon': {},
          'Lesotho': {},
          'Liberia': {},
          'Libya': {},
          'Liechtenstein': {},
          'Line Islands': {},
          'Lithuania': {},
          'Luxembourg': {},
          'Macau': {},
          'Madagascar': {},
          'Malawi': {},
          'Malaysia': {},
          'Maldives': {},
          'Mali': {},
          'Malta': {},
          'Marshall Islands': {},
          'Martinique': {},
          'Mauritania': {},
          'Mauritius': {},
          'Mayotte': {},
          'Mexico': {},
          'Micronesia': {},
          'Midway Islands': {},
          'Moldova': {},
          'Monaco': {},
          'Mongolia': {},
          'Montenegro': {},
          'Montserrat': {},
          'Morocco': {},
          'Mozambique': {},
          'Myanmar': {},
          'Namibia': {},
          'Nauru': {},
          'Navassa Island': {},
          'Nepal': {},
          'Netherlands': {},
          'New Caledonia': {},
          'New Zealand': {},
          'Nicaragua': {},
          'Niger': {},
          'Nigeria': {},
          'Niue': {},
          'Norfolk Island': {},
          'North Korea': {},
          'North Macedonia': {},
          'North Sea': {},
          'Northern Mariana Islands': {},
          'Norway': {},
          'Oman': {},
          'Pakistan': {},
          'Palau': {},
          'Panama': {},
          'Papua New Guinea': {},
          'Paracel Islands': {},
          'Paraguay': {},
          'Peru': {},
          'Philippines': {},
          'Pitcairn Islands': {},
          'Poland': {},
          'Portugal': {},
          'Puerto Rico': {},
          'Qatar': {},
          'Republic of the Congo': {},
          'Reunion': {},
          'Romania': {},
          'Ross Sea': {},
          'Russia': {},
          'Rwanda': {},
          'Saint Helena': {},
          'Saint Kitts and Nevis': {},
          'Saint Lucia': {},
          'Saint Pierre and Miquelon': {},
          'Saint Martin': {},
          'Saint Vincent and the Grenadines': {},
          'Samoa': {},
          'San Marino': {},
          'Sao Tome and Principe': {},
          'Saudi Arabia': {},
          'Senegal': {},
          'Serbia': {},
          'Seychelles': {},
          'Sierra Leone': {},
          'Singapore': {},
          'Sint Maarten': {},
          'Slovakia': {},
          'Slovenia': {},
          'Solomon Islands': {},
          'Somalia': {},
          'South Africa': {},
          'South Georgia and the South Sandwich Islands': {},
          'South Korea': {},
          'South Sudan': {},
          'Spain': {},
          'Spratly Islands': {},
          'Sri Lanka': {},
          'State of Palestine': {},
          'Sudan': {},
          'Suriname': {},
          'Svalbard': {},
          'Swaziland': {},
          'Sweden': {},
          'Switzerland': {},
          'Syria': {},
          'Taiwan': {},
          'Tajikistan': {},
          'Tanzania': {},
          'Thailand': {},
          'Timor-Leste': {},
          'Togo': {},
          'Tokelau': {},
          'Tonga': {},
          'Trinidad and Tobago': {},
          'Tromelin Island': {},
          'Tunisia': {},
          'Turkey': {},
          'Turkmenistan': {},
          'Turks and Caicos Islands': {},
          'Tuvalu': {},
          'USA': {},
          'Uganda': {},
          'Ukraine': {},
          'United Arab Emirates': {},
          'United Kingdom': {},
          'Uruguay': {},
          'Uzbekistan': {},
          'Vanuatu': {},
          'Venezuela': {},
          'Viet Nam': {},
          'Virgin Islands': {},
          'Wake Island': {},
          'Wallis and Futuna': {},
          'West Bank': {},
          'Western Sahara': {},
          'Yemen': {},
          'Zambia': {},
          'Zimbabwe': {},
        },
      },
      {
        fieldName: 'geo_loc_name (province/territory)',
        vocabulary: {
          'ALBERTA': {},
          'BRITISH COLUMBIA': {},
          'MANITOBA': {},
          'NEW BRUNSWICK': {},
          'NEWFOUNDLAND': {},
          'NORTHWEST TERRITORIES': {},
          'NOVA SCOTIA': {},
          'NUNAVUT': {},
          'ONTARIO': {},
          'PRINCE EDWARD ISLAND': {},
          'QUEBEC': {},
          'SASKATCHEWAN': {},
          'YUKON TERRITORY': {},
        },
      },
      {
        fieldName: 'geo_loc_name (city)',
        vocabulary: {},
      },
      {
        fieldName: 'organism',
        vocabulary: {
          'SARS-CoV-2': {},
          'RaTG13': {},
          'RmYN02': {},
        },
      },
      {
        fieldName: 'isolate',
        vocabulary: {},
      },
      {
        fieldName: 'purpose of sampling',
        vocabulary: {
          'Cluster investigation': {},
          'Diagnostic testing': {},
          'Research': {},
          'Surveillance testing': {},
          'Viral passage experiment': {},
        },
      },
      {
        fieldName: 'anatomical material',
        vocabulary: {
          'Blood': {},
          'Fluid': {
            'Fluid (cerebrospinal (CSF))': {},
            'Fluid (oral)': {},
            'Fluid (pleural)': {},
            'Fluid (pericardial)': {},
          },
          'Saliva': {},
          'Tissue': {},
        },
      },
      {
        fieldName: 'anatomical part',
        vocabulary: {
          'Upper respiratory tract': {
            'Anterior Nares': {},
            'Esophagus': {},
            'Ethmoid sinus': {},
            'Inferior Nasal Turbinate': {},
            'Middle Nasal Turbinate': {},
            'Nasal Cavity': {},
            'Nasopharynx': {},
            'Oropharynx': {},
          },
          'Lower respiratory tract': {
            'Alveolar sac': {},
            'Bronchiole': {},
            'Bronchus': {},
            'Lung': {},
            'Pleural cavity': {},
            'Pleural Sac': {},
            'Trachea': {},
          },
          'Anus': {},
          'Duodenum': {},
          'Eye': {},
          'Intestine': {},
          'Rectum': {},
          'Skin': {},
          'Stomach': {},
        },
      },
      {
        fieldName: 'body product',
        vocabulary: {
          'Feces': {},
          'Mucus': {},
          'Sputum': {},
          'Sweat': {},
          'Tear': {},
          'Urine': {},
        },
      },
      {
        fieldName: 'environmental material',
        vocabulary: {
          'Banknote': {},
          'Bathroom': {},
          'Bed rail': {},
          'Building floor': {},
          'Cloth': {},
          'Control panel': {},
          'Corridor': {},
          'Door': {},
          'Door handle': {},
          'Face mask': {},
          'Face shield': {},
          'Glass': {},
          'Handrail': {},
          'Hospital gown': {},
          'Light switch': {},
          'Locker': {},
          'N95 mask': {},
          'Nurse call button': {},
          'Paper': {},
          'Plastic': {},
          'PPE gown': {},
          'Sewage': {},
          'Sink': {},
          'Soil': {},
          'Stainless steel': {},
          'Tissue paper': {},
          'Toilet bowl': {},
          'Water': {},
          'Window': {},
          'Wood': {},
        },
      },
      {
        fieldName: 'environmental site',
        vocabulary: {
          'Acute care facility': {},
          'Air vent': {},
          'Animal house': {},
          'Clinical assessment centre': {},
          'Conference venue': {},
          'Daycare': {},
          'Emergency room (ER)': {},
          'Family practice clinic': {},
          'Group home': {},
          'Homeless shelter': {},
          'Hospital': {},
          'Intensive Care Unit (ICU)': {},
          'Long Term Care Facility': {},
          'Patient room': {},
          'Prison': {},
          'Production Facility': {},
          'School': {},
          'Subway train': {},
        },
      },
      {
        fieldName: 'collection device',
        vocabulary: {
          'Air filter': {},
          'Blood Collection Tube': {},
          'Bronchoscope': {},
          'Collection Cup': {},
          'Collection Tube': {},
          'Fibrobronchoscope Brush': {},
          'Fine Needle': {},
          'Microcapillary tube': {},
          'Micropipette': {},
          'Needle': {},
          'Serum Collection Tube': {},
          'Sputum Collection Tube': {},
          'Suction Catheter': {},
          'Swab': {},
          'Urine Collection Tube': {},
          'Virus Transport Medium': {},
        },
      },
      {
        fieldName: 'collection method',
        vocabulary: {
          'Amniocentesis': {},
          'Aspiration': {
            'Tracheal aspiration': {},
            'Vacuum Aspiration': {},
            'Suprapubic Aspiration': {},
          },
          'Biopsy': {
            'Needle Biopsy': {},
          },
          'Lavage': {
            'Bronchoalveolar lavage (BAL)': {},
            'Gastric Lavage': {},
          },
          'Lumbar Puncture': {},
          'Necropsy': {},
          'Phlebotomy': {},
          'Rinsing': {},
          'Scraping': {},
          'Swab': {},
          'Washout Tear Collection': {},
          'Wash': {},
        },
      },
      {
        fieldName: 'collection protocol',
        vocabulary: {},
      },
      {
        fieldName: 'specimen processing',
        vocabulary: {
          'Virus passage': {},
          'NOT APPLICABLE': {},
        },
      },
      {
        fieldName: 'lab host',
        vocabulary: {
          '293/ACE2 cell line': {},
          'Caco2 cell line': {},
          'Calu3 cell line': {},
          'EFK3B cell line': {},
          'HEK293T cell line': {},
          'HRCE cell line': {},
          'Huh7 cell line': {},
          'LLCMk2 cell line': {},
          'MDBK cell line': {},
          'NHBE cell line': {},
          'PK-15 cell line': {},
          'RK-13 cell line': {},
          'U251 cell line': {},
          'Vero cell line': {},
          'Vero E6 cell line': {},
          'VeroE6/TMPRSS2 cell line': {},
        },
      },
      {
        fieldName: 'passage number',
        vocabulary: {},
      },
      {
        fieldName: 'passage method',
        vocabulary: {},
      },
      {
        fieldName: 'biomaterial extracted',
        vocabulary: {},
      },
    ],
  },
  {
    fieldName: 'Host information',
    children: [
      {
        fieldName: 'host (common name)',
        vocabulary: {
          'Human': {},
          'Bat': {},
          'Cat': {},
          'Chicken': {},
          'Civets': {},
          'Cow': {},
          'Dog': {},
          'Lion': {},
          'Pangolin': {},
          'Pig': {},
          'Pigeon': {},
          'Tiger': {},
          'NOT APPLICABLE': {},
        },
      },
      {
        fieldName: 'host (scientific name)',
        vocabulary: {
          'Homo sapiens': {},
          'Bos taurus': {},
          'Canis lupus familiaris': {},
          'Chiroptera': {},
          'Columbidae': {},
          'Felis catus': {},
          'Gallus gallus': {},
          'Manis': {},
          'Manis javanica': {},
          'Panthera leo': {},
          'Panthera tigris': {},
          'Rhinolophidae': {},
          'Rhinolophus affinis': {},
          'Sus scrofa domesticus': {},
          'Viverridae': {},
          'NOT APPLICABLE': {},
        },
      },
      {
        fieldName: 'host health state',
        vocabulary: {
          'healthy': {},
          'sick': {},
          'recovered': {},
          'deceased': {},
          'NOT COLLECTED': {},
        },
      },
      {
        fieldName: 'host health status details',
        vocabulary: {
          'Self-quarantining': {},
          'Asymptomatic': {},
          'Symptomatic': {},
          'Hospitalized (ICU)': {},
          'NOT APPLICABLE': {},
        },
      },
      {
        fieldName: 'host disease',
        vocabulary: {
          'COVID-19': {},
        },
      },
      {
        fieldName: 'host age',
        vocabulary: {
          '0-9 years': {},
          '10-19 years': {},
          '20-29 years': {},
          '30-39 years': {},
          '40-49 years': {},
          '50-59 years': {},
          '60-69 years': {},
          '70-79 years': {},
          '80+ years': {},
        },
      },
      {
        fieldName: 'host gender',
        vocabulary: {
          'female': {},
          'male': {},
          'non-binary gender': {},
          'transgender': {},
          'undeclared': {},
          'unknown': {},
          'NOT PROVIDED': {},
        },
      },
      {
        fieldName: 'host origin geo_loc name (country)',
        vocabulary: {},
      },
      {
        fieldName: 'host subject ID',
        vocabulary: {},
      },
      {
        fieldName: 'symptom onset date',
        vocabulary: {},
      },
      {
        fieldName: 'signs and symptoms',
        vocabulary: {
          'Arthralgia (painful joints)': {},
          'Chills': {},
          'Coma': {},
          'Confusion': {},
          'Conjunctivitis': {},
          'Cough': {},
          'Diarrhea': {},
          'Encephalitis': {},
          'Fever': {},
          'Headache': {},
          'Hypotension (low blood pressure)': {},
          'Irritability': {},
          'Myalgia (muscle pain)': {},
          'Nausea': {},
          'Pharyngitis (sore throat)': {},
          'Rhinorrhea (runny nose)': {},
          'Seizure': {},
          'Shortness of breath (breathing difficulty)': {},
          'Tachypnea (rapid breathing)': {},
          'Vomiting': {},
          'Weakness': {},
        },
      },
    ],
  },
  {
    fieldName: 'Host exposure information',
    children: [
      {
        fieldName: 'location of exposure geo_loc name (country)',
        vocabulary: {},
      },
      {
        fieldName: 'travel history',
        vocabulary: {},
      },
      {
        fieldName: 'exposure event',
        vocabulary: {
          'mass gathering (convention)': {},
          'mass gathering (religious)': {},
          'mass gathering (social e.g. funeral, wedding etc.)': {},
          'mass gathering (office)': {},
          'occupational exposure (hospital worker)': {},
          'occupational exposure (hospital visit)': {},
          'occupational exposure (frontline response)': {},
          'occupational exposure (healthcare work with the public)': {},
          'occupational exposure (retail)': {},
          'occupational exposure (restaurant)': {},
        },
      },
    ],
  },
  {
    fieldName: 'Sequencing',
    children: [
      {
        fieldName: 'library ID',
        vocabulary: {},
      },
      {
        fieldName: 'sequencing instrument',
        vocabulary: {
          'ILLUMINA': {
            'HiSeq X Five': {},
            'HiSeq X Ten': {},
            'Illumina Genome Analyzer': {},
            'Illumina Genome Analyzer II': {},
            'Illumina Genome Analyzer IIx': {},
            'Illumina HiScanSQ': {},
            'Illumina HiSeq 1000': {},
            'Illumina HiSeq 1500': {},
            'Illumina HiSeq 2000': {},
            'Illumina HiSeq 2500': {},
            'Illumina HiSeq 3000': {},
            'Illumina HiSeq 4000': {},
            'Illumina iSeq 100': {},
            'Illumina NovaSeq 6000': {},
            'Illumina MiniSeq': {},
            'Illumina MiSeq': {},
            'NextSeq 500': {},
            'NextSeq 550': {},
          },
          'Pacific Biosciences': {
            'PacBio RS': {},
            'PacBio RS II': {},
            'PacBio Sequel': {},
            'PacBio Sequel II': {},
            'Ion Torrent': {},
            'Ion Torrent PGM': {},
            'Ion Torrent Proton': {},
            'Ion Torrent S5 XL': {},
            'Ion Torrent S5': {},
          },
          'Oxford Nanopore': {
            'GridION': {},
            'MinION': {},
            'PromethION': {},
          },
          'BGI Genomics': {
            'BGISEQ-500': {},
          },
        },
      },
      {
        fieldName: 'sequencing protocol name',
        vocabulary: {},
      },
      {
        fieldName: 'sequencing protocol source',
        vocabulary: {},
      },
      {
        fieldName: 'sequencing kit number',
        vocabulary: {},
      },
      {
        fieldName: 'amplicon pcr primers filename',
        vocabulary: {},
      },
    ],
  },
  {
    fieldName: 'Bioinformatics and QC metrics',
    children: [
      {
        fieldName: 'raw sequence data processing',
        vocabulary: {},
      },
      {
        fieldName: 'sequencing depth (average)',
        vocabulary: {},
      },
      {
        fieldName: 'assembly name',
        vocabulary: {},
      },
      {
        fieldName: 'assembly method',
        vocabulary: {},
      },
      {
        fieldName: 'assembly coverage breadth',
        vocabulary: {},
      },
      {
        fieldName: 'assembly coverage depth',
        vocabulary: {},
      },
      {
        fieldName: 'r1 fastq filename',
        vocabulary: {},
      },
      {
        fieldName: 'r2 fastq filename',
        vocabulary: {},
      },
      {
        fieldName: 'fasta filename',
        vocabulary: {},
      },
      {
        fieldName: 'number base pairs',
        vocabulary: {},
      },
      {
        fieldName: 'genome length',
        vocabulary: {},
      },
      {
        fieldName: 'mean contig length',
        vocabulary: {},
      },
      {
        fieldName: 'N50',
        vocabulary: {},
      },
      {
        fieldName: 'Ns per 100 kbp',
        vocabulary: {},
      },
      {
        fieldName: 'reference genome accession',
        vocabulary: {},
      },
      {
        fieldName: 'consensus sequence ID',
        vocabulary: {},
      },
      {
        fieldName: 'consensus sequence method',
        vocabulary: {},
      },
      {
        fieldName: 'annotation feature table filename',
        vocabulary: {},
      },
      {
        fieldName: 'bioinformatics protocol',
        vocabulary: {},
      },
    ],
  },
  {
    fieldName: 'Pathogen diagnostic testing',
    children: [
      {
        fieldName: 'gene name 1',
        vocabulary: {},
      },
      {
        fieldName: 'diagnostic pcr protocol 1',
        vocabulary: {},
      },
      {
        fieldName: 'diagnostic pcr Ct value 1',
        vocabulary: {},
      },
      {
        fieldName: 'gene name 2',
        vocabulary: {},
      },
      {
        fieldName: 'diagnostic pcr protocol 2',
        vocabulary: {},
      },
      {
        fieldName: 'diagnostic pcr Ct value 2',
        vocabulary: {},
      },
    ],
  },
  {
    fieldName: 'Contributor acknowledgement',
    children: [
      {
        fieldName: 'authors',
        vocabulary: {},
      },
    ],
  },
];
