const DATA = [
  {
    fieldName: 'Database Identifiers',
    children: [
      {
        fieldName: 'specimen collector sample ID',
        datatype: 'text',
        requirement: 'required',
        description: 'The user-defined name for the sample.',
        guidance: 'Store the collector sample ID. Every collector sample ID from a single submitter must be unique. It can have any format, but we suggest that you make it concise, unique and consistent within your lab, and as informative as possible.',
        examples: 'prov_rona_99',
        vocabulary: {},
      },
      {
        fieldName: 'PHAC sample ID',
        datatype: 'text',
        requirement: 'recommended',
        description: 'The identifier assigned to the sample in the national database.',
        guidance: 'Store the PHAC sample ID. This ID will be assigned by PHAC. The PHAC sample ID may be different than the sample ID assigned by the sample collector. It is important to track both of these for traceability.',
        examples: 'PHAC_123',
        vocabulary: {},
      },
      {
        fieldName: 'IRIDA sample name',
        datatype: 'text',
        requirement: '',
        description: 'The identifier assigned to a sequenced isolate in IRIDA.',
        guidance: 'Store the IRIDA sample name. The IRIDA sample name will be created by the individual entering data into the IRIDA platform. IRIDA samples may be linked to metadata and sequence data, or just metadata alone. It is recommended that the IRIDA sample name be the same as, or contain, the specimen collector sample ID for better traceability.',
        examples: 'prov_rona_99',
        vocabulary: {},
      },
      {
        fieldName: 'umbrella bioproject accession',
        datatype: 'select',
        requirement: '',
        description: 'The INSDC accession number assigned to the umbrella BioProject for the Canadian SARS-CoV-2 sequencing effort.',
        guidance: 'Store the umbrella BioProject accession by selecting it from the pick list in the template. The umbrella BioProject accession will be identical for all CanCOGen submitters. Different provinces will have their own BioProjects, however these BioProjects will be linked under one umbrella BioProject.',
        examples: 'PRJNA623807',
        vocabulary: {
          'PRJNA623807': {},
        },
      },
      {
        fieldName: 'bioproject accession',
        datatype: 'text',
        requirement: '',
        description: 'The INSDC accession number of the BioProject(s) to which the BioSample belongs.',
        guidance: 'Store the BioProject accession number. BioProjects are an organizing tool that links together raw sequence data, assemblies, and their associated metadata. A valid NCBI BioProject accession has prefix PRJN e.g., PRJNA12345 and is created once at the beginning of a new sequencing project.',
        examples: 'PRJNA608651',
        vocabulary: {},
      },
      {
        fieldName: 'biosample accession',
        datatype: 'text',
        requirement: '',
        description: 'The identifier assigned to a BioSample in INSDC archives.',
        guidance: 'Store the accession returned from the BioSample submission. NCBI BioSamples will have the prefix SAMN.',
        examples: 'SAMN14180202',
        vocabulary: {},
      },
      {
        fieldName: 'SRA accession',
        datatype: 'text',
        requirement: '',
        description: 'The Sequence Read Archive (SRA) identifier linking raw read data, methodological metadata and quality control metrics submitted to the INSDC.',
        guidance: 'Store the accession assigned to the submitted \'run\'. NCBI-SRA accessions start with SRR.',
        examples: 'SRR11177792',
        vocabulary: {},
      },
      {
        fieldName: 'GenBank accession',
        datatype: 'text',
        requirement: '',
        description: 'The GenBank identifier assigned to the sequence in the INSDC archives.',
        guidance: 'Store the accession returned from a GenBank submission (viral genome assembly).',
        examples: 'MN908947.3',
        vocabulary: {},
      },
      {
        fieldName: 'GISAID accession',
        datatype: 'text',
        requirement: '',
        description: 'The GISAID accession number assigned to the sequence.',
        guidance: 'Store the accession returned from the GISAID submission.',
        examples: 'hCov-19/Canada/prov_rona_99/2020',
        vocabulary: {},
      },
    ],
  },
  {
    fieldName: 'Sample collection and processing',
    children: [
      {
        fieldName: 'sample collected by',
        datatype: 'text',
        requirement: 'required',
        description: 'The name of the agency that collected the original sample.',
        guidance: 'The name of the agency should be written out in full, (with minor exceptions) and be consistent across multple submissions e.g. Public Health Agency of Canada, Public Health Ontario, BC Centre for Disease Control',
        examples: 'BC Centre for Disease Control',
        vocabulary: {},
      },
      {
        fieldName: 'sample collector contact email',
        datatype: 'text',
        requirement: '',
        description: 'The email address of the contact responsible for follow-up regarding the sample.',
        guidance: 'The email address can represent a specific individual or lab e.g. johnnyblogs@lab.ca, or RespLab@lab.ca',
        examples: 'RespLab@lab.ca',
        vocabulary: {},
      },
      {
        fieldName: 'sample collector contact address',
        datatype: 'text',
        requirement: '',
        description: 'The mailing address of the agency submitting the sample.',
        guidance: 'The mailing address should be in the format: Street number and name, City, Province/Territory, Postal Code, Country',
        examples: '655 Lab St, Vancouver, British Columbia, V5N 2A2, Canada',
        vocabulary: {},
      },
      {
        fieldName: 'sequence submitted by',
        datatype: 'text',
        requirement: 'required',
        description: 'The name of the agency that generated the sequence.',
        guidance: 'The name of the agency should be written out in full, (with minor exceptions) and be consistent across multple submissions e.g. Public Health Agency of Canada, Public Health Ontario, BC Centre for Disease Control',
        examples: 'Public Health Ontario',
        vocabulary: {},
      },
      {
        fieldName: 'sequence submitter contact email',
        datatype: 'text',
        requirement: '',
        description: 'The email address of the contact responsible for follow-up regarding the sequence.',
        guidance: 'The email address can represent a specific individual or lab e.g. johnnyblogs@lab.ca, or RespLab@lab.ca',
        examples: 'RespLab@lab.ca',
        vocabulary: {},
      },
      {
        fieldName: 'sequence submitter contact address',
        datatype: 'text',
        requirement: '',
        description: 'The mailing address of the agency submitting the sequence.',
        guidance: 'The mailing address should be in the format: Street number and name, City, Province/Territory, Postal Code, Country',
        examples: '123 Sunnybrooke St, Toronto, Ontario, M4P 1L6, Canada',
        vocabulary: {},
      },
      {
        fieldName: 'sample collection date',
        datatype: 'date',
        requirement: 'required',
        description: 'The date on which the sample was collected.',
        guidance: 'ISO 8601 standard \'YYYY-MM-DD\', \'YYYY-MM\'or \'YYYY\'',
        examples: '2020-03-16',
        vocabulary: {},
      },
      {
        fieldName: 'geo_loc_name (country)',
        datatype: 'select',
        requirement: 'required',
        description: 'The country where the sample was collected.',
        guidance: 'Provide the country name from the controlled vocabulary provided.',
        examples: 'Canada',
        vocabulary: {
          'Afghanistan': {},
          'Albania': {},
          'Algeria': {},
          'American Samoa': {},
          'Andorra': {},
          'Angola': {},
          'Anguilla': {},
          'Antarctica': {},
          'Antigua and Barbuda': {},
          'Argentina': {},
          'Armenia': {},
          'Aruba': {},
          'Ashmore and Cartier Islands': {},
          'Australia': {},
          'Austria': {},
          'Azerbaijan': {},
          'Bahamas': {},
          'Bahrain': {},
          'Baker Island': {},
          'Bangladesh': {},
          'Barbados': {},
          'Bassas da India': {},
          'Belarus': {},
          'Belgium': {},
          'Belize': {},
          'Benin': {},
          'Bermuda': {},
          'Bhutan': {},
          'Bolivia': {},
          'Borneo': {},
          'Bosnia and Herzegovina': {},
          'Botswana': {},
          'Bouvet Island': {},
          'Brazil': {},
          'British Virgin Islands': {},
          'Brunei': {},
          'Bulgaria': {},
          'Burkina Faso': {},
          'Burundi': {},
          'Cambodia': {},
          'Cameroon': {},
          'Canada': {},
          'Cape Verde': {},
          'Cayman Islands': {},
          'Central African Republic': {},
          'Chad': {},
          'Chile': {},
          'China': {},
          'Christmas Island': {},
          'Clipperton Island': {},
          'Cocos Islands': {},
          'Colombia': {},
          'Comoros': {},
          'Cook Islands': {},
          'Coral Sea Islands': {},
          'Costa Rica': {},
          'Cote d\'Ivoire': {},
          'Croatia': {},
          'Cuba': {},
          'Curacao': {},
          'Cyprus': {},
          'Czech Republic': {},
          'Democratic Republic of the Congo': {},
          'Denmark': {},
          'Djibouti': {},
          'Dominica': {},
          'Dominican Republic': {},
          'Ecuador': {},
          'Egypt': {},
          'El Salvador': {},
          'Equatorial Guinea': {},
          'Eritrea': {},
          'Estonia': {},
          'Eswatini': {},
          'Ethiopia': {},
          'Europa Island': {},
          'Falkland Islands (Islas Malvinas)': {},
          'Faroe Islands': {},
          'Fiji': {},
          'Finland': {},
          'France': {},
          'French Guiana': {},
          'French Polynesia': {},
          'French Southern and Antarctic Lands': {},
          'Gabon': {},
          'Gambia': {},
          'Gaza Strip': {},
          'Georgia': {},
          'Germany': {},
          'Ghana': {},
          'Gibraltar': {},
          'Glorioso Islands': {},
          'Greece': {},
          'Greenland': {},
          'Grenada': {},
          'Guadeloupe': {},
          'Guam': {},
          'Guatemala': {},
          'Guernsey': {},
          'Guinea': {},
          'Guinea-Bissau': {},
          'Guyana': {},
          'Haiti': {},
          'Heard Island and McDonald Islands': {},
          'Honduras': {},
          'Hong Kong': {},
          'Howland Island': {},
          'Hungary': {},
          'Iceland': {},
          'India': {},
          'Indonesia': {},
          'Iran': {},
          'Iraq': {},
          'Ireland': {},
          'Isle of Man': {},
          'Israel': {},
          'Italy': {},
          'Jamaica': {},
          'Jan Mayen': {},
          'Japan': {},
          'Jarvis Island': {},
          'Jersey': {},
          'Johnston Atoll': {},
          'Jordan': {},
          'Juan de Nova Island': {},
          'Kazakhstan': {},
          'Kenya': {},
          'Kerguelen Archipelago': {},
          'Kingman Reef': {},
          'Kiribati': {},
          'Kosovo': {},
          'Kuwait': {},
          'Kyrgyzstan': {},
          'Laos': {},
          'Latvia': {},
          'Lebanon': {},
          'Lesotho': {},
          'Liberia': {},
          'Libya': {},
          'Liechtenstein': {},
          'Line Islands': {},
          'Lithuania': {},
          'Luxembourg': {},
          'Macau': {},
          'Madagascar': {},
          'Malawi': {},
          'Malaysia': {},
          'Maldives': {},
          'Mali': {},
          'Malta': {},
          'Marshall Islands': {},
          'Martinique': {},
          'Mauritania': {},
          'Mauritius': {},
          'Mayotte': {},
          'Mexico': {},
          'Micronesia': {},
          'Midway Islands': {},
          'Moldova': {},
          'Monaco': {},
          'Mongolia': {},
          'Montenegro': {},
          'Montserrat': {},
          'Morocco': {},
          'Mozambique': {},
          'Myanmar': {},
          'Namibia': {},
          'Nauru': {},
          'Navassa Island': {},
          'Nepal': {},
          'Netherlands': {},
          'New Caledonia': {},
          'New Zealand': {},
          'Nicaragua': {},
          'Niger': {},
          'Nigeria': {},
          'Niue': {},
          'Norfolk Island': {},
          'North Korea': {},
          'North Macedonia': {},
          'North Sea': {},
          'Northern Mariana Islands': {},
          'Norway': {},
          'Oman': {},
          'Pakistan': {},
          'Palau': {},
          'Panama': {},
          'Papua New Guinea': {},
          'Paracel Islands': {},
          'Paraguay': {},
          'Peru': {},
          'Philippines': {},
          'Pitcairn Islands': {},
          'Poland': {},
          'Portugal': {},
          'Puerto Rico': {},
          'Qatar': {},
          'Republic of the Congo': {},
          'Reunion': {},
          'Romania': {},
          'Ross Sea': {},
          'Russia': {},
          'Rwanda': {},
          'Saint Helena': {},
          'Saint Kitts and Nevis': {},
          'Saint Lucia': {},
          'Saint Pierre and Miquelon': {},
          'Saint Martin': {},
          'Saint Vincent and the Grenadines': {},
          'Samoa': {},
          'San Marino': {},
          'Sao Tome and Principe': {},
          'Saudi Arabia': {},
          'Senegal': {},
          'Serbia': {},
          'Seychelles': {},
          'Sierra Leone': {},
          'Singapore': {},
          'Sint Maarten': {},
          'Slovakia': {},
          'Slovenia': {},
          'Solomon Islands': {},
          'Somalia': {},
          'South Africa': {},
          'South Georgia and the South Sandwich Islands': {},
          'South Korea': {},
          'South Sudan': {},
          'Spain': {},
          'Spratly Islands': {},
          'Sri Lanka': {},
          'State of Palestine': {},
          'Sudan': {},
          'Suriname': {},
          'Svalbard': {},
          'Swaziland': {},
          'Sweden': {},
          'Switzerland': {},
          'Syria': {},
          'Taiwan': {},
          'Tajikistan': {},
          'Tanzania': {},
          'Thailand': {},
          'Timor-Leste': {},
          'Togo': {},
          'Tokelau': {},
          'Tonga': {},
          'Trinidad and Tobago': {},
          'Tromelin Island': {},
          'Tunisia': {},
          'Turkey': {},
          'Turkmenistan': {},
          'Turks and Caicos Islands': {},
          'Tuvalu': {},
          'USA': {},
          'Uganda': {},
          'Ukraine': {},
          'United Arab Emirates': {},
          'United Kingdom': {},
          'Uruguay': {},
          'Uzbekistan': {},
          'Vanuatu': {},
          'Venezuela': {},
          'Viet Nam': {},
          'Virgin Islands': {},
          'Wake Island': {},
          'Wallis and Futuna': {},
          'West Bank': {},
          'Western Sahara': {},
          'Yemen': {},
          'Zambia': {},
          'Zimbabwe': {},
        },
      },
      {
        fieldName: 'geo_loc_name (province/territory)',
        datatype: 'select',
        requirement: 'required',
        description: 'The province/territory where the sample was collected.',
        guidance: 'Provide the province/territory name from the controlled vocabulary provided.',
        examples: 'Saskatchewan',
        vocabulary: {
          'ALBERTA': {},
          'BRITISH COLUMBIA': {},
          'MANITOBA': {},
          'NEW BRUNSWICK': {},
          'NEWFOUNDLAND': {},
          'NORTHWEST TERRITORIES': {},
          'NOVA SCOTIA': {},
          'NUNAVUT': {},
          'ONTARIO': {},
          'PRINCE EDWARD ISLAND': {},
          'QUEBEC': {},
          'SASKATCHEWAN': {},
          'YUKON TERRITORY': {},
        },
      },
      {
        fieldName: 'geo_loc_name (city)',
        datatype: 'text',
        requirement: '',
        description: 'The city where the sample was collected.',
        guidance: 'Provide the city name. Use this look-up service to identify the standardized term: https://www.ebi.ac.uk/ols/ontologies/gaz',
        examples: 'Medicine Hat',
        vocabulary: {},
      },
      {
        fieldName: 'organism',
        datatype: 'select',
        requirement: 'required',
        description: 'Taxonomic name of the organism.',
        guidance: 'Use SARS-CoV-2. This value is provided in the template.',
        examples: 'SARS-CoV-2',
        vocabulary: {
          'SARS-CoV-2': {},
          'RaTG13': {},
          'RmYN02': {},
        },
      },
      {
        fieldName: 'isolate',
        datatype: 'text',
        requirement: 'required',
        description: 'Identifier of the specific isolate.',
        guidance: 'Provide the isolate name. This identifer should be an unique, indexed, alpha-numeric ID within your laboratory. The isolate name is often the same as the specimen collector sample ID.',
        examples: 'prov_rona_99',
        vocabulary: {},
      },
      {
        fieldName: 'purpose of sampling',
        datatype: 'select',
        requirement: 'recommended',
        description: 'The reason that the sample was collected.',
        guidance: 'Provide the purpose of sampling from the picklist in the template.',
        examples: 'Diagnostic testing',
        vocabulary: {
          'Cluster investigation': {},
          'Diagnostic testing': {},
          'Research': {},
          'Surveillance testing': {},
          'Viral passage experiment': {},
        },
      },
      {
        fieldName: 'anatomical material',
        datatype: 'select',
        requirement: 'required',
        description: 'A substance obtained from an anatomical part of an organism e.g. tissue, blood.',
        guidance: 'Provide a descriptor if an anatomical material was sampled. Use the picklist provided in the template. If a desired term is missing from the picklist, use this look-up service to identify a standardized term: https://www.ebi.ac.uk/ols/ontologies/uberon. If not applicable, leave blank.',
        examples: 'Blood',
        vocabulary: {
          'Blood': {},
            'Saliva': {},
          'Fluid': {
            'Fluid (cerebrospinal (CSF))': {},
            'Fluid (pericardial)': {},
            'Fluid (pleural)': {},
            'Fluid (vaginal)': {},
            'Fluid (amniotic)': {},
            'Fluid (seminal)': {},
          },
          'Tissue': {},
        },
      },
      {
        fieldName: 'anatomical part',
        datatype: 'select',
        requirement: 'required',
        description: 'An anatomical part of an organism e.g. oropharynx.',
        guidance: 'Provide a descriptor if an anatomical part was sampled. Use the picklist provided in the template. If a desired term is missing from the picklist, use this look-up service to identify a standardized term: https://www.ebi.ac.uk/ols/ontologies/uberon. If not applicable, leave blank.',
        examples: 'Nasopharynx',
        vocabulary: {
          'Anus': {},
          'Duodenum': {},
          'Eye': {},
          'Intestine': {},
          'Rectum': {},
          'Skin': {},
          'Stomach': {},
          'Upper respiratory tract': {
            'Anterior Nares': {},
            'Esophagus': {},
            'Ethmoid sinus': {},
            'Nasal Cavity': {
              'Middle Nasal Turbinate': {},
              'Inferior Nasal Turbinate': {},
            },
            'Nasopharynx (NP)': {},
            'Oropharynx (OP)': {},
          },
          'Lower respiratory tract': {
            'Bronchus': {},
            'Lung': {
              'Bronchiole': {},
              'Alveolar sac': {},
            },
            'Pleural sac': {
              'Pleural cavity': {},
            },
            'Trachea': {},
          },
        },
      },
      {
        fieldName: 'body product',
        datatype: 'select',
        requirement: 'required',
        description: 'A substance excreted/secreted from an organism e.g. feces, urine, sweat.',
        guidance: 'Provide a descriptor if a body product was sampled. Use the picklist provided in the template. If a desired term is missing from the picklist, use this look-up service to identify a standardized term: https://www.ebi.ac.uk/ols/ontologies/uberon. If not applicable, leave blank.',
        examples: 'Feces',
        vocabulary: {
          'Feces': {},
          'Urine': {},
          'Sweat': {},
          'Mucus': {
            'Sputum': {},
          },
          'Tear': {},
        },
      },
      {
        fieldName: 'environmental material',
        datatype: 'select',
        requirement: 'required',
        description: 'A substance obtained from the natural or man-made environment e.g. soil, water, sewage.',
        guidance: 'Provide a descriptor if an environmental material was sampled. Use the picklist provided in the template. If a desired term is missing from the picklist, use this look-up service to identify a standardized term: https://www.ebi.ac.uk/ols/ontologies/envo. If not applicable, leave blank.',
        examples: 'Face mask',
        vocabulary: {
          'Banknote': {},
          'Bathroom': {},
          'Bed rail': {},
          'Building floor': {},
          'Cloth': {},
          'Control panel': {},
          'Corridor': {},
          'Door  ': {},
          'Door handle': {},
          'Face mask': {},
          'Face shield': {},
          'Glass': {},
          'Handrail': {},
          'Hospital gown': {},
          'Light switch': {},
          'Locker': {},
          'N95 mask': {},
          'Nurse call button ': {},
          'Paper': {},
          'Plastic': {},
          'PPE gown': {},
          'Sewage': {},
          'Sink': {},
          'Soil': {},
          'Stainless steel': {},
          'Tissue paper': {},
          'Toilet bowl': {},
          'Water': {},
          'Window': {},
          'Wood': {},
        },
      },
      {
        fieldName: 'environmental site',
        datatype: 'select',
        requirement: 'required',
        description: 'An environmental location may describe a site in the natural or built environment e.g. contact surface, metal can, hospital, wet market, bat cave.',
        guidance: 'Provide a descriptor if an environmental site was sampled. Use the picklist provided in the template. If a desired term is missing from the picklist, use this look-up service to identify a standardized term: https://www.ebi.ac.uk/ols/ontologies/envo. If not applicable, leave blank.',
        examples: 'Building floor',
        vocabulary: {
          'Acute care facility': {},
          'Air vent': {},
          'Animal house': {},
          'Clinical assessment centre': {},
          'Conference venue': {},
          'Daycare': {},
          'Emergency room (ER)': {},
          'Family practice clinic': {},
          'Group home': {},
          'Homeless shelter': {},
          'Hospital': {},
          'Intensive Care Unit (ICU)': {},
          'Long Term Care Facility': {},
          'Patient room': {},
          'Prison': {},
          'Production Facility': {},
          'School': {},
          'Subway train': {},
          'Wet market': {},
        },
      },
      {
        fieldName: 'collection device',
        datatype: 'select',
        requirement: 'required',
        description: 'The instrument or container used to collect the sample e.g. swab.',
        guidance: 'Provide a descriptor if a device was used for sampling. Use the picklist provided in the template. If a desired term is missing from the picklist, use this look-up service to identify a standardized term: https://www.ebi.ac.uk/ols/ontologies/obi. If not applicable, leave blank.',
        examples: 'Swab',
        vocabulary: {
          'Air filter': {},
          'Blood Collection Tube': {},
          'Bronchoscope': {},
          'Collection Container': {},
          'Collection Cup': {},
          'Fibrobronchoscope Brush': {},
          'Fine Needle': {},
          'Microcapillary tube': {},
          'Micropipette': {},
          'Needle': {},
          'Serum Collection Tube': {},
          'Sputum Collection Tube': {},
          'Suction Catheter': {},
          'Swab': {},
          'Urine Collection Tube': {},
          'Virus Transport Medium': {},
        },
      },
      {
        fieldName: 'collection method',
        datatype: 'select',
        requirement: 'required',
        description: 'The process used to collect the sample e.g. phlebotamy, necropsy.',
        guidance: 'Provide a descriptor if a collection method was used for sampling. Use the picklist provided in the template. If a desired term is missing from the picklist, use this look-up service to identify a standardized term: https://www.ebi.ac.uk/ols/ontologies/obi. If not applicable, leave blank.',
        examples: 'Bronchoalveolar lavage (BAL)',
        vocabulary: {
          'Amniocentesis': {},
          'Aspiration': {
            'Suprapubic Aspiration': {},
            'Tracheal aspiration': {},
            'Vacuum Aspiration': {},
          },
          'Biopsy': {
            'Needle Biopsy': {},
          },
          'Lavage': {
            'Bronchoalveolar lavage (BAL)': {},
            'Gastric Lavage': {},
          },
          'Lumbar Puncture': {},
          'Necropsy': {},
          'Phlebotomy': {},
          'Rinsing': {},
          'Scraping': {},
          'Swab': {
            'Finger Prick': {},
          },
          'Wash': {},
          'Washout Tear Collection': {},
        },
      },
      {
        fieldName: 'collection protocol',
        datatype: 'select',
        requirement: '',
        description: 'The name and version of a particular protocol used for sampling.',
        guidance: 'Free text.',
        examples: 'BCRonaSamplingProtocol v. 1.2',
        vocabulary: {},
      },
      {
        fieldName: 'specimen processing',
        datatype: 'select',
        requirement: 'recommended',
        description: 'Any processing applied to the sample during or after receiving the sample.',
        guidance: 'Critical for passage history. If virus was passaged, select \'virus passage\'from the picklist. If the sample was not passaged, put \'not applicable\'.',
        examples: 'Virus passage',
        vocabulary: {
          'Virus passage': {},
          'NOT APPLICABLE': {},
        },
      },
      {
        fieldName: 'lab host',
        datatype: 'select',
        requirement: 'recommended',
        description: 'Name and description of the laboratory host used to propagate the source organism or material from which the sample was obtained.',
        guidance: 'Type of cell line used for propagation. Provide the name of the cell line using the picklist in the template. If not passaged, put \'not applicable\'.',
        examples: 'Vero E6 cell line',
        vocabulary: {
          '293/ACE2 cell line': {},
          'Caco2 cell line': {},
          'Calu3 cell line': {},
          'EFK3B cell line': {},
          'HEK293T cell line': {},
          'HRCE cell line': {},
          'Huh7 cell line': {},
          'LLCMk2 cell line': {},
          'MDBK cell line': {},
          'Mv1Lu cell line': {},
          'NHBE cell line': {},
          'PK-15 cell line': {},
          'RK-13 cell line': {},
          'U251 cell line': {},
          'Vero cell line': {
            'Vero E6 cell line': {
              'VeroE6/TMPRSS2 cell line': {},
            },
          },
        },
      },
      {
        fieldName: 'passage number',
        datatype: 'integer',
        requirement: 'recommended',
        description: 'Number of passages.',
        guidance: 'Provide number of known passages. If not passaged, put \'not applicable\'',
        examples: '3',
        vocabulary: {},
      },
      {
        fieldName: 'passage method',
        datatype: 'text',
        requirement: 'recommended',
        description: 'Description of how organism was passaged.',
        guidance: 'Free text. Provide a very short description (<10 words). If not passaged, put \'not applicable\'.',
        examples: '',
        vocabulary: {},
      },
      {
        fieldName: 'biomaterial extracted',
        datatype: 'select',
        requirement: '',
        description: 'The biomaterial extracted from samples for the purpose of sequencing.',
        guidance: 'Provide the biomaterial extracted from the picklist in the template.',
        examples: 'RNA (total)',
        vocabulary: {
          'RNA (total),': {},
          'RNA (poly-A),': {},
          'RNA (ribo-depleted),': {},
          'mRNA (cDNA)': {},
        },
      },
    ],
  },
  {
    fieldName: 'Host Information',
    children: [
      {
        fieldName: 'host (common name)',
        datatype: 'select',
        requirement: '',
        description: 'The commonly used name of the host.',
        guidance: 'Common name or scientific name are required if there was a host. Both can be provided, if known. Use terms from the pick lists in the template. Common name e.g. human, bat. If the sample was environmental, put \'not applicable.',
        examples: 'Human',
        vocabulary: {
          'Human': {},
          'Bat': {},
          'Cat': {},
          'Chicken': {},
          'Civets': {},
          'Cow': {},
          'Dog': {},
          'Lion': {},
          'Pangolin': {},
          'Pig': {},
          'Pigeon': {},
          'Tiger': {},
        },
      },
      {
        fieldName: 'host (scientific name)',
        datatype: 'select',
        requirement: 'required',
        description: 'The taxonomic, or scientific name of the host.',
        guidance: 'Common name or scientific name are required if there was a host. Both can be provided, if known. Use terms from the pick lists in the template. Scientific name e.g. Homo sapiens, If the sample was environmental, put \'not applicable',
        examples: 'Homo sapiens',
        vocabulary: {
          'Homo sapiens': {},
          'Bos taurus': {},
          'Canis lupus familiaris': {},
          'Chiroptera': {},
          'Columbidae': {},
          'Felis catus': {},
          'Gallus gallus': {},
          'Manis': {},
          'Manis javanica': {},
          'Panthera leo': {},
          'Panthera tigris': {},
          'Rhinolophidae': {},
          'Rhinolophus affinis': {},
          'Sus scrofa domesticus': {},
          'Viverridae': {},
        },
      },
      {
        fieldName: 'host health state',
        datatype: 'select',
        requirement: '',
        description: 'Health status of the host at the time of sample collection.',
        guidance: 'If known, select a descriptor from the pick list provided in the template.',
        examples: 'sick',
        vocabulary: {
          'healthy': {},
          'sick': {},
          'recovered': {},
          'deceased': {},
          'NOT COLLECTED': {},
        },
      },
      {
        fieldName: 'host health status details',
        datatype: 'select',
        requirement: '',
        description: 'Further details pertaining to the health or disease status of the host at time of collection.',
        guidance: 'If known, select a descriptor from the pick list provided in the template.',
        examples: 'Hospitalized (ICU)',
        vocabulary: {
          'Self-quarantining': {},
          'Asymptomatic': {},
          'Symptomatic': {},
          'Hospitalized (ICU)': {},
          'NOT APPLICABLE': {},
        },
      },
      {
        fieldName: 'host disease',
        datatype: 'select',
        requirement: 'required',
        description: 'The name of the disease experienced by the host.',
        guidance: 'Select \'COVID-19\'from the pick list provided in the template.',
        examples: 'COVID-19',
        vocabulary: {
          'COVID-19': {},
        },
      },
      {
        fieldName: 'host age',
        datatype: 'decimal',
        requirement: 'required',
        description: 'Age of host at the time of sampling.',
        guidance: 'Enter the age of the host in years. If not available, put \'unknown\'.',
        examples: '79',
        vocabulary: {},
      },
      {
        fieldName: 'host gender',
        datatype: 'select',
        requirement: 'required',
        description: 'The gender of the host at the time of sample collection.',
        guidance: 'Select the corresponding host gender from the pick list provided in the template. If not available, put \'unknown\'.',
        examples: 'male',
        vocabulary: {
          'female': {},
          'male': {},
          'non-binary gender': {},
          'transgender': {},
          'undeclared': {},
          'unknown': {},
          'NOT PROVIDED': {},
        },
      },
      {
        fieldName: 'host origin geo_loc name (country)',
        datatype: 'select',
        requirement: '',
        description: 'The country of residence of the host.',
        guidance: 'Select the country name from pick list provided in the template.',
        examples: 'United Kingdom',
        vocabulary: {},
      },
      {
        fieldName: 'host subject ID',
        datatype: 'text',
        requirement: '',
        description: 'A unique identifier by which each host can be referred to e.g. #131',
        guidance: 'Provide the host identifier. Should be a unique, user-defined identifier.',
        examples: 'BCxy123',
        vocabulary: {},
      },
      {
        fieldName: 'symptom onset date',
        datatype: 'date',
        requirement: '',
        description: 'The date on which the symptoms began or were first noted.',
        guidance: 'ISO 8601 standard \'YYYY-MM-DD\', \'YYYY-MM\'or \'YYYY\'',
        examples: '2020-03-16',
        vocabulary: {},
      },
      {
        fieldName: 'signs and symptoms',
        datatype: 'multiple',
        requirement: '',
        description: 'A perceived change in function or sensation, (loss, disturbance or appearance) indicative of a disease, reported by a patient.',
        guidance: 'Provide a list of symptoms experienced by the host. List in order of appearance, separated by a comma.',
        examples: 'Cough, Fever, Chills',
        vocabulary: {
          'Ageusia': {},
          'Anosmia': {},
          'Arthralgia (painful joints)': {},
          'Asthenia': {},
          'Chest Pain': {},
          'Chills': {},
          'Coma': {},
          'Confusion ': {},
          'Conjunctivitis ': {},
          'Cough ': {},
          'Delirium': {},
          'Diarrhea': {},
          'Dysgeusia': {},
          'Encephalitis ': {},
          'Fatigue': {},
          'Fever': {},
          'Headache': {},
          'Hemoptysis': {},
          'Hypogeusia': {},
          'Hyposmia': {},
          'Hypotension (low blood pressure)': {},
          'Hypoxemia': {},
          'Irritability': {},
          'Loss of speech': {},
          'Loss of taste': {},
          'Low appetite': {},
          'Malaise': {},
          'Myalgia (muscle pain) ': {},
          'Nasal obstruction (stuffy nose)': {},
          'Nausea': {},
          'Pharyngitis (sore throat) ': {},
          'Rash': {},
          'Rhinorrhea (runny nose)': {},
          'Seizure': {},
          'Shortness of breath (breathing difficulty) ': {},
          'Slurred speech': {},
          'Tachypnea (rapid breathing)': {},
          'Vomiting': {},
          'Weakness': {},
        },
      },
    ],
  },
  {
    fieldName: 'Host exposure information',
    children: [
      {
        fieldName: 'location of exposure geo_loc name (country)',
        datatype: 'select',
        requirement: '',
        description: 'The country where the host was likely exposed to the causative agent of the illness.',
        guidance: 'Select the country name from pick list provided in the template.',
        examples: 'Canada',
        vocabulary: {},
      },
      {
        fieldName: 'travel history',
        datatype: 'text',
        requirement: '',
        description: 'Travel outside the country in last six months.',
        guidance: 'Specify the countries (and more granular locations if known, separated by a comma) travelled in the last six months; can include multiple travels. Separate multiple travel events with a semi-colon. List most recent travel first.',
        examples: 'Canada, Vancouver; USA, Seattle; Italy, Milan',
        vocabulary: {},
      },
      {
        fieldName: 'exposure event',
        datatype: 'select',
        requirement: '',
        description: 'Event leading to exposure.',
        guidance: 'Select an exposure event from the pick list provided in the template. If the desired term is missing, contact the curation team.',
        examples: 'Mass gathering (convention)',
        vocabulary: {
          'mass gathering (convention)': {},
          'mass gathering (religious)': {},
          'mass gathering (social e.g. funeral, wedding etc.)': {},
          'mass gathering (office)': {},
          'occupational exposure (hospital worker)': {},
          'occupational exposure (hospital visit)': {},
          'occupational exposure (frontline response)': {},
          'occupational exposure (healthcare work with the public)': {},
          'occupational exposure (retail)': {},
          'occupational exposure (restaurant)': {},
        },
      },
    ],
  },
  {
    fieldName: 'Sequencing',
    children: [
      {
        fieldName: 'library ID',
        datatype: 'text',
        requirement: 'recommended',
        description: 'The user-specified identifier for the library prepared for sequencing.',
        guidance: 'The library name should be unique, and can be an autogenerated ID from your LIMS, or modification of the isolate ID.',
        examples: 'XYZ_123345',
        vocabulary: {},
      },
      {
        fieldName: 'sequencing instrument',
        datatype: 'select',
        requirement: 'required',
        description: 'The model of the sequencing instrument used.',
        guidance: 'Select a sequencing instrument from the picklist provided in the template.',
        examples: 'MinIon',
        vocabulary: {
          'ILLUMINA': {
            'HiSeq X ': {
              'HiSeq X Five': {},
              'HiSeq X Ten': {},
            },
            'Illumina Genome Analyzer': {
              'Illumina Genome Analyzer II': {},
              'Illumina Genome Analyzer IIx': {},
            },
            'Illumina HiScanSQ': {},
            'Illumina HiSeq 1000': {},
            'Illumina HiSeq 1500': {},
            'Illumina HiSeq 2000': {},
            'Illumina HiSeq 2500': {},
            'Illumina HiSeq 3000': {},
            'Illumina HiSeq 4000': {},
            'Illumina iSeq 100': {},
            'Illumina NovaSeq 6000': {},
            'Illumina MiniSeq': {},
            'Illumina MiSeq': {},
            'NextSeq 500': {},
            'NextSeq 550': {},
          },
          'Pacific Biosciences': {
            'PacBio RS': {},
            'PacBio RS II': {},
            'PacBio Sequel': {},
            'PacBio Sequel II': {},
          },
          'Ion Torrent': {
            'Ion Torrent PGM': {},
            'Ion Torrent Proton': {},
            'Ion Torrent S5 XL': {},
            'Ion Torrent S5': {},
          },
          'Oxford Nanopore': {
            'GridION': {},
            'MinION': {},
            'PromethION': {},
          },
          'BGI Genomics': {
            'BGISEQ-500': {},
          },
        },
      },
      {
        fieldName: 'sequencing protocol name',
        datatype: 'text',
        requirement: 'recommended',
        description: 'The name and version number of the sequencing protocol used.',
        guidance: 'Provide the name and version of the sequencing protocol e.g. 1D_DNA_MinION',
        examples: '1D_DNA_MinION, ARTIC Network Protocol v. 3',
        vocabulary: {},
      },
      {
        fieldName: 'sequencing protocol source',
        datatype: 'text',
        requirement: '',
        description: 'The name of the organization/authors of the protocol.',
        guidance: 'Provide the name of the source of the protocol e.g. ARTIC Network.',
        examples: 'ARTIC Network',
        vocabulary: {},
      },
      {
        fieldName: 'sequencing kit number',
        datatype: 'text',
        requirement: '',
        description: 'The manufacturer\'s kit number.',
        guidance: 'Alphanumeric value.',
        examples: 'AB456XYZ789',
        vocabulary: {},
      },
      {
        fieldName: 'amplicon pcr primers filename',
        datatype: 'text',
        requirement: '',
        description: 'The filename of the file containing amplicon PCR primer names and sequences.',
        guidance: 'Important for documenting methods and should be considered for submission, particularly if primers were designed in-house and not by a public consortium/network.',
        examples: 'Rona_primers_2020.txt',
        vocabulary: {},
      },
    ],
  },
  {
    fieldName: 'Bioinformatics and QC metrics',
    children: [
      {
        fieldName: 'raw sequence data processing',
        datatype: 'text',
        requirement: 'recommended',
        description: 'The names of the software and version number used for raw data processing such as removing barcodes, adapter trimming, filtering etc.',
        guidance: 'Provide the software name followed by the version e.g. Trimmomatic v. 0.38, Porechop v. 0.2.3',
        examples: 'Porechop v. 0.2.3',
        vocabulary: {},
      },
      {
        fieldName: 'sequencing depth (average)',
        datatype: 'text',
        requirement: '',
        description: 'The total number of sequenced base pairs divided by the expected number of base pairs in the genome.',
        guidance: 'Provide the value as a fold of coverage.',
        examples: '80x',
        vocabulary: {},
      },
      {
        fieldName: 'assembly name',
        datatype: 'text',
        requirement: '',
        description: 'Name/version of the assembly provided by the submitter.',
        guidance: 'Provide the assembly name.',
        examples: 'rona123assembly.fasta',
        vocabulary: {},
      },
      {
        fieldName: 'assembly method',
        datatype: 'select',
        requirement: 'required',
        description: 'The name and version number of the assembly method used.',
        guidance: 'Provide the software name followed by the version e.g. Canu v. 2.0',
        examples: 'Canu v. 2.0',
        vocabulary: {},
      },
      {
        fieldName: 'assembly coverage breadth',
        datatype: 'text',
        requirement: '',
        description: 'The percentage of the assembled genome that was sequenced to a prescribed depth of coverage.',
        guidance: 'Provide value as a percent e.g. 95%.',
        examples: '95%',
        vocabulary: {},
      },
      {
        fieldName: 'assembly coverage depth',
        datatype: 'text',
        requirement: '',
        description: 'The average number of reads representing a given nucleotide in the assembled sequence.',
        guidance: 'Provide value as a fold of coverage e.g. 80x.',
        examples: '400x',
        vocabulary: {},
      },
      {
        fieldName: 'r1 fastq filename        ',
        datatype: 'text',
        requirement: 'recommended',
        description: 'The user-specified filename of the r1 FASTQ file.',
        guidance: 'Provide the r1 fastq filename.',
        examples: 'ABC123_S1_L001_R1_001.fastq.gz',
        vocabulary: {},
      },
      {
        fieldName: 'r2 fastq filename',
        datatype: 'text',
        requirement: 'recommended',
        description: 'The user-specified filename of the r2 FASTQ file.',
        guidance: 'Provide the r2 fastq filename.',
        examples: 'ABC123_S1_L001_R2_001.fastq.gz',
        vocabulary: {},
      },
      {
        fieldName: 'fasta filename',
        datatype: 'text',
        requirement: '',
        description: 'The user-specified filename of the FASTA file.',
        guidance: 'Provide the fasta filename.',
        examples: 'batch1a_sequences.fasta',
        vocabulary: {},
      },
      {
        fieldName: 'number base pairs',
        datatype: 'integer',
        requirement: '',
        description: 'The number of total base pairs generated by the sequencing process.',
        guidance: 'Provide a numerical value (no need to include units).',
        examples: '387566',
        vocabulary: {},
      },
      {
        fieldName: 'genome length',
        datatype: 'integer',
        requirement: '',
        description: 'Size of the reconstructed genome described as the number of base pairs.',
        guidance: 'Provide a numerical value (no need to include units).',
        examples: '38677',
        vocabulary: {},
      },
      {
        fieldName: 'mean contig length',
        datatype: 'integer',
        requirement: '',
        description: 'The mean contig length is the count of base pairs in the average size contig of the sequence assembly.',
        guidance: 'Provide a numerical value (no need to include units).',
        examples: '12689',
        vocabulary: {},
      },
      {
        fieldName: 'N50',
        datatype: 'integer',
        requirement: '',
        description: 'The minimum contig length needed to cover 50% of the genome.',
        guidance: 'Provide a numerical value (no need to include units).',
        examples: '10500',
        vocabulary: {},
      },
      {
        fieldName: 'Ns per 100 kbp',
        datatype: 'decimal',
        requirement: '',
        description: 'The number of N symbols present in the consensus fasta sequence, per 100kbp of sequence.',
        guidance: 'Provide a numerical value (no need to include units).',
        examples: '3.3',
        vocabulary: {},
      },
      {
        fieldName: 'reference genome accession',
        datatype: 'text',
        requirement: '',
        description: 'A persistent, unique identifier of a genome database entry.',
        guidance: 'Provide the accession number of the reference genome.',
        examples: 'NC_045512.2',
        vocabulary: {},
      },
      {
        fieldName: 'consensus sequence ID',
        datatype: 'text',
        requirement: '',
        description: 'The identifer used to specify the consensus sequence.',
        guidance: 'Provide the consensus sequence identifier.',
        examples: 'ProvConsensusSeq.fasta',
        vocabulary: {},
      },
      {
        fieldName: 'consensus sequence method',
        datatype: 'text',
        requirement: '',
        description: 'The name and version number of the software used to produce the consensus sequence.',
        guidance: 'Provide the software name followed by the version e.g. iVar v. 1.2',
        examples: 'iVar v. 1.2',
        vocabulary: {},
      },
      {
        fieldName: 'annotation feature table filename',
        datatype: 'text',
        requirement: '',
        description: 'The filename of the file containing genome features such as gene names and corresponding CDS.',
        guidance: 'Provide the filename of the annotation feature table.',
        examples: 'BCRonaAnnotationFeatures',
        vocabulary: {},
      },
      {
        fieldName: 'bioinformatics protocol',
        datatype: 'text',
        requirement: '',
        description: 'The name and version number of the bioinformatics protocol used.',
        guidance: 'Further details regarding the methods used to process raw data, and/or generate assemblies, and/or generate consensus sequences can be provided in an SOP or protocol. Provide the name and version number of the protocol.',
        examples: 'https://www.protocols.io/groups/cphln-sarscov2-sequencing-consortium/members',
        vocabulary: {},
      },
    ],
  },
  {
    fieldName: 'Pathogen diagnostic testing',
    children: [
      {
        fieldName: 'gene name 1',
        datatype: 'text',
        requirement: '',
        description: 'The name of the gene used in the diagnostic RT-PCR test.',
        guidance: 'Provide the full name of the gene used in the test. The gene symbol (short form of gene name) can also be provided. Standardized gene names and symbols can be found in the Gene Ontology using this look-up service: https://bit.ly/2Sq1LbI',
        examples: 'envelope small membrane protein (SARS-CoV-2)',
        vocabulary: {},
      },
      {
        fieldName: 'diagnostic pcr protocol 1',
        datatype: 'text',
        requirement: '',
        description: 'The name and version number of the protocol used for diagnostic marker amplification.',
        guidance: 'The name and version number of the protocol used for carrying out a diagnostic PCR test. This information can be compared to sequence data for evaluation of performance and quality control.',
        examples: 'AllTheTestingPCRingEGene v. 2',
        vocabulary: {},
      },
      {
        fieldName: 'diagnostic pcr Ct value 1',
        datatype: 'text',
        requirement: '',
        description: 'The Ct value result from a diagnostic SARS-CoV-2 RT-PCR test.',
        guidance: 'Provide the CT value of the sample from the diagnostic RT-PCR test.',
        examples: '21',
        vocabulary: {},
      },
      {
        fieldName: 'gene name 2',
        datatype: 'text',
        requirement: '',
        description: 'The name of the gene used in the diagnostic RT-PCR test.',
        guidance: 'Provide the full name of another gene used in an RT-PCR test. The gene symbol (short form of gene name) can also be provided. Standardized gene names and symbols can be found in the Gene Ontology using this look-up service: https://bit.ly/2Sq1LbI',
        examples: 'RNA-directed RNA Polymerase (RdRP)',
        vocabulary: {},
      },
      {
        fieldName: 'diagnostic pcr protocol 2',
        datatype: 'text',
        requirement: '',
        description: 'The name and version number of the protocol used for diagnostic marker amplification.',
        guidance: 'The name and version number of the protocol used for carrying out a second diagnostic PCR test. This information can be compared to sequence data for evaluation of performance and quality control.',
        examples: 'AllTheTestingPCRingRdRpGene v. 3',
        vocabulary: {},
      },
      {
        fieldName: 'diagnostic pcr Ct value 2',
        datatype: 'text',
        requirement: '',
        description: 'The Ct value result from a diagnostic SARS-CoV-2 RT-PCR test.',
        guidance: 'Provide the CT value of the sample from the second diagnostic RT-PCR test.',
        examples: '36',
        vocabulary: {},
      },
    ],
  },
  {
    fieldName: 'Contributor acknowledgement',
    children: [
      {
        fieldName: 'authors',
        datatype: 'text',
        requirement: 'recommended',
        description: 'Names of individuals contributing to the processes of sample collection, sequence generation, analysis, and data submission.',
        guidance: 'Include the first and last names of all individuals that should be attributed, separated by a comma.',
        examples: 'Tejinder Singh, Fei Hu, Joe Blogs',
        vocabulary: {},
      },
    ],
  },
]