var DATA = [
  {
    "fieldName": "Database Identifiers",
    "children": [
      {
        "fieldName": "sample_name",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": [
          "Not Applicable",
          "Missing",
          "Not Collected",
          "Not Provided",
          "Restricted Access"
        ],
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "The user-defined name for the sample.",
        "guidance": "Every Sample Name from a single submitter must be unique. It can have any format, but we suggest that you make it concise, unique and consistent within your lab, and as informative as possible.",
        "examples": "SA20131043",
        "EXPORT_???": ""
      },
      {
        "fieldName": "progeny_sample_ID",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The user-defined identifier for progeny isolates derived from the original sample.",
        "guidance": "If your sequence data pertains to progeny of an original isolate, provide the progeny sample ID.",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "alternative_sample_ID",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "An alternative sample ID assigned to the sample by another organization.",
        "guidance": "If an alternative sample ID is available, here\u2019s where you can include it.",
        "examples": "PHAC_45678",
        "EXPORT_???": ""
      },
      {
        "fieldName": "IRIDA_sample_ID",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The identifier assigned to the corresponding sequence data in IRIDA.",
        "guidance": "IRIDA sample IDs should be unqiue to avoid ID clash. This is very important in large Projects, especially when samples are shared from different organizations. Download the IRIDA sample ID and add it to the sample data in your spreadsheet as part of good data management practices.",
        "examples": "",
        "EXPORT_???": ""
      }
    ]
  },
  {
    "fieldName": "Fields to put in sections",
    "children": [
      {
        "fieldName": "strain",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The strain identifier.",
        "guidance": "If the isolate represents or is derived from, a lab reference strain or strain from a type culture collection, provide the strain identifier.",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "publication_PMID",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The PubMed ID for a publication.",
        "guidance": "If the isolate is associated with a published work which can provide additional information, provide the PubMed identifier of the publication.",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "attribute_package",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The attribute package used to structure metadata in an INSDC BioSample.",
        "guidance": "If the sample is from a specific human or animal, put \u201cPathogen.cl\u201d. If the sample is from an environmental sample including food, feed, production facility, farm, water source, manure etc, put \u201cPathogen.env\u201d.",
        "examples": "Pathogen.cl",
        "EXPORT_???": ""
      },
      {
        "fieldName": "geo_loc (country)",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The country where the sample was collected.",
        "guidance": "Use the controlled vocabulary provided in the template pick list.",
        "examples": "Canada",
        "EXPORT_???": ""
      },
      {
        "fieldName": "geo_loc (state/province/region)",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The province/territory where the sample was collected.",
        "guidance": "Use the controlled vocabulary provided in the template pick list.",
        "examples": "British Columbia",
        "EXPORT_???": ""
      },
      {
        "fieldName": "lat_lon",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The latitude and longitude coordinates where the sample was collected.",
        "guidance": "If known, provide the degrees latitude and longitude. Do NOT provide lat/lon of the institution, nor the centre of the city/region where the sample was collected as this falsely implicates an existing geographical location and creates data inaccuracies. If unknown, put \"missing\".",
        "examples": "38.98 N 77.11 W.",
        "EXPORT_???": ""
      },
      {
        "fieldName": "collection_date",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The date on which the sample was collected.",
        "guidance": "Provide the date according to the ISO 8601 standard \"YYYY-MM-DD\", \"YYYY-MM\" or \"YYYY\".",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "collected_by",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The affiliation of the sample collector.",
        "guidance": "Provide the name of the agency associated with the collection of the sample in full.",
        "examples": "Canadian Food Inspection Agency",
        "EXPORT_???": ""
      },
      {
        "fieldName": "laboratory_name",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The name of the specific laboratory that collected the sample.",
        "guidance": "If known, provide the name of the specific lab that collected the sample. This information will be useful for follow-up, attribution of contributions, and establishing data ownership.",
        "examples": "Smith Lab",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sample_collector_contact_email",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The email address of the contact responsible for follow-up regarding the sample.",
        "guidance": "The email address can represent a specific individual or lab.",
        "examples": "johnnyblogs@lab.ca, EntericsLab@lab.ca.",
        "EXPORT_???": ""
      },
      {
        "fieldName": "organism",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The taxonomic name of the organism.",
        "guidance": "Put the genus and species (and subspecies if applicable) of the bacteria, if known. The standardized term can be sourced from this look-up service: https://www.ebi.ac.uk/ols/ontologies/ncbitaxon.",
        "examples": "Salmonella enterica subspecies enterica",
        "EXPORT_???": ""
      },
      {
        "fieldName": "serovar",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The serovar of the organism.",
        "guidance": "Only include this information if it has been determined by traditional serological methods or a validated in silico prediction tool e.g. SISTR.",
        "examples": "Heidelberg",
        "EXPORT_???": ""
      },
      {
        "fieldName": "serotyping_method",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The method used to determine the serovar.",
        "guidance": "If the serovar was determined via traditional serotyping methods, put \u201ctraditional serotyping\u201d. If the serovar was determined via in silico methods, provide the name and version number of the software.",
        "examples": "SISTR v.1.0.1",
        "EXPORT_???": ""
      },
      {
        "fieldName": "phagetype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The phagetype of the organism.",
        "guidance": "Provide if known. If unknown, put \u201cmissing\u201d.",
        "examples": "47",
        "EXPORT_???": ""
      },
      {
        "fieldName": "purpose_of_sampling",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The reason why the sample was originally collected.",
        "guidance": "The information can help to interpret the results of an analysis. Select a value from the pick list provided.",
        "examples": "Surveillance",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sample_processing",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The processing applied to samples prior to sequencing.",
        "guidance": "If the sample is a composite (pooled samples), choose \u201csamples pooled\u201d. If samples are from a single source, choose \u201cisolated from single source\u201d. If unknown, put \u201cmissing\u201d.",
        "examples": "samples pooled",
        "EXPORT_???": ""
      },
      {
        "fieldName": "host (common name)",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The commonly used name of the host.",
        "guidance": "If the sample is directly from a host, either a common or scientific name must be provided (although both can be included, if known). If known, provide the common name.",
        "examples": "cow, chicken, human",
        "EXPORT_???": ""
      },
      {
        "fieldName": "host (scientific name)",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The scientific name of the host.",
        "guidance": "If the sample is directly from a host, either a common or scientific name must be provided (although both can be included, if known). If known, provide the scientific name. The standardized term can be sourced from this look-up service: https://www.ebi.ac.uk/ols/ontologies/ncbitaxon.",
        "examples": "Bos taurus, Homo sapiens",
        "EXPORT_???": ""
      },
      {
        "fieldName": "host_disease",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The name of the disease experienced by the host.",
        "guidance": "This field is only required if the Pathogen.cl package was selected. If the host was sick, provide the name of the disease.The standardized term can be sourced from this look-up service: https://www.ebi.ac.uk/ols/ontologies/doid If the disease is not known, put \u201cmissing\u201d.",
        "examples": "mastitis, gastroenteritis",
        "EXPORT_???": ""
      },
      {
        "fieldName": "environmental_site",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "An environmental site is a location in the natural or built environment.",
        "guidance": "If applicable, provide the standardized term and ontology ID for the environmental site. The standardized term can be sourced from these look-up services: https://www.ebi.ac.uk/ols/ontologies/envo or https://www.ebi.ac.uk/ols/ontologies/genepio.",
        "examples": "contact surface, production facility, floor drain, hatchery.",
        "EXPORT_???": ""
      },
      {
        "fieldName": "animal_or_plant_population",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The type of animal or plant population inhabiting an area.",
        "guidance": "This field should be used when a sample is taken from an environmental location inhabited by many individuals of a specific type, rather than describing a sample taken from one particular host. If applicable, provide the standardized term and ontology ID for the animal or plant population name. The standardized term can be sourced from this look-up service: https://www.ebi.ac.uk/ols/ontologies/genepio. If not applicable, leave blank.",
        "examples": "turkey",
        "EXPORT_???": ""
      },
      {
        "fieldName": "environmental_material",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "A substance or object obtained from the natural or man-made environment .",
        "guidance": "If applicable, provide the standardized term and ontology ID for the environmental material. The standardized term can be sourced from these look-up services: https://www.ebi.ac.uk/ols/ontologies/envo or https://www.ebi.ac.uk/ols/ontologies/genepio. If not applicable, leave blank.",
        "examples": "soil, water, sewage, tractor",
        "EXPORT_???": ""
      },
      {
        "fieldName": "body_product",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "A substance excreted/secreted from an organism.",
        "guidance": "If applicable, provide the standardized term and ontology ID for the body product. The standardized term can be sourced from this look-up service: https://www.ebi.ac.uk/ols/ontologies/uberon. If not applicable, leave blank.",
        "examples": "feces, urine, sweat.",
        "EXPORT_???": ""
      },
      {
        "fieldName": "anatomical_part",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "A substance obtained from an anatomical part of an organism.",
        "guidance": "If applicable, provide the standardized term and ontology ID for the anatomical material. The standardized term can be sourced from this look-up service: https://www.ebi.ac.uk/ols/ontologies/uberon. If not applicable, leave blank.",
        "examples": "tissue, blood",
        "EXPORT_???": ""
      },
      {
        "fieldName": "food_product",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "A material consumed and digested for nutritional value or enjoyment.",
        "guidance": "This field includes animal feed. If applicable, provide the standardized term and ontology ID for the anatomical material. The standardized term can be sourced from this look-up service: https://www.ebi.ac.uk/ols/ontologies/foodon. If not applicable, leave blank.",
        "examples": "feather and bone meal, chicken breast",
        "EXPORT_???": ""
      },
      {
        "fieldName": "collection_device",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The instrument or container used to collect the sample.",
        "guidance": "This field includes animal feed. If applicable, provide the standardized term and ontology ID for the anatomical material. The standardized term can be sourced from this look-up service: https://www.ebi.ac.uk/ols/ontologies/genepio. If not applicable, leave blank.",
        "examples": "swab",
        "EXPORT_???": ""
      },
      {
        "fieldName": "collection_method",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The process used to collect the sample.",
        "guidance": "If applicable, provide the standardized term and ontology ID for the anatomical material. The standardized term can be sourced from this look-up service: https://www.ebi.ac.uk/ols/ontologies/genepio. If not applicable, leave blank.",
        "examples": "phlebotomy, necropsy, rinsing",
        "EXPORT_???": ""
      }
    ]
  },
  {
    "fieldName": "Antimicrobial resistance",
    "children": [
      {
        "fieldName": "AMR_laboratory_typing_method",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Type of method used for antibiotic susceptibility testing.",
        "guidance": "\u201cMIC\u201d, \u201cagar dilution\u201d, \u201cdisk diffusion\u201d, or \u201cmissing\u201d",
        "examples": "MIC",
        "EXPORT_???": ""
      },
      {
        "fieldName": "AMR_laboratory_typing_platform",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The brand/platform used for antibiotic susceptibility testing",
        "guidance": "\u201cMicroscan\u201d, \u201cPhoenix\u201d, \u201cSensititre\u201d, or \u201cVitek\u201d",
        "examples": "Sensititre",
        "EXPORT_???": ""
      },
      {
        "fieldName": "AMR_laboratory_typing_platform_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The specific name and version of the plate, panel, or other platform used for antibiotic susceptibility testing.",
        "guidance": "Any additional information about the nature of the antimicrobial susceptibility test can go in this field.",
        "examples": "CMV3AGNF",
        "EXPORT_???": ""
      },
      {
        "fieldName": "AMR_measurement_units",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Units used for measuring antibiotic susceptibility",
        "guidance": "\u201cmg/L\u201d or \u201cmm\u201d",
        "examples": "mg/L",
        "EXPORT_???": ""
      },
      {
        "fieldName": "amoxicillin-clavulanic_acid_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Antimicrobial resistance phenotype, as determined by the antibiotic susceptibility measurement and testing standard for this antibiotic",
        "guidance": "\u201cresistant\u201d, \u201csusceptible\u201d, \u201cintermediate\u201d, \u201cnonsusceptible\u201d, \u201csuceptible-dose dependent\u201d, or \u201cnot defined\u201d",
        "examples": "sensitive",
        "EXPORT_???": ""
      },
      {
        "fieldName": "amoxicillin-clavulanic_acid_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Qualifier associated with the antibiotic susceptibility measurement",
        "guidance": "\u201c<\u201d, \u201c<=\u201d, \u201c==\u201d, \u201c>=\u201d, or \u201c>\". If the susceptibility measurement for this antibiotic and for this sample is exact, use \u201c==\u201d.",
        "examples": "#ERROR!",
        "EXPORT_???": ""
      },
      {
        "fieldName": "amoxicillin-clavulanic_acid_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Antibiotic susceptibility measurement, measured in the units specified in the \u201cAMR_measurement_units\u201d field.",
        "guidance": "This field should only contain a number (either an integer or a number with decimals).",
        "examples": "4",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ampicillin_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "CLSI",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ampicillin_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "M100",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ampicillin_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "27th ed. Wayne, PA: Clinical and Laboratory Standards Institute; 2017.",
        "EXPORT_???": ""
      },
      {
        "fieldName": "azithromycin_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "8",
        "EXPORT_???": ""
      },
      {
        "fieldName": "azithromycin_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "16",
        "EXPORT_???": ""
      },
      {
        "fieldName": "azithromycin_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "32",
        "EXPORT_???": ""
      },
      {
        "fieldName": "cefoxitin_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "cefoxitin_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "cefoxitin_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ceftriaxone_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ceftriaxone_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ceftriaxone_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "chloramphenicol_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "chloramphenicol_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "chloramphenicol_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ciprofloxacin_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ciprofloxacin_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ciprofloxacin_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "gentamicin_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "gentamicin_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "gentamicin_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "meropenem_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "meropenem_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "meropenem_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "nalidixic_acid_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "nalidixic_acid_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "nalidixic_acid_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "streptomycin_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "streptomycin_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "streptomycin_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sulfisoxazole_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sulfisoxazole_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sulfisoxazole_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "tetracycline_resistance_phenotype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "tetracycline_measurement_sign",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "tetracycline_measurement",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "amoxicillin-clavulanic_acid_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Testing standard used for determination of resistance phenotype",
        "guidance": "\u201cCLSI\u201d, \u201cNARMS\u201d, \u201cBSAC\u201d, \u201cDIN\u201d, \u201cEUCAST\u201d, \u201cNCCLS\u201d, \u201cSFM\u201d, \u201cSIR\u201d, \u201cWRG\u201d, or \u201cmissing\u201d",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "amoxicillin-clavulanic_acid_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Version number associated with the testing standard used for determination of resistance phenotype",
        "guidance": "If applicable, include a version number for the testing standard used.",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "amoxicillin-clavulanic_acid_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Additional details associated with the testing standard used for determination of resistance phenotype",
        "guidance": "This information may include the year or location where the testing standard was published. If not applicable, leave blank.",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "amoxicillin-clavulanic_acid_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Maximum measurement, in the units specified in the \u201cAMR_measurement_units\u201d field, for a sample to be considered \u201csensitive\u201d to this antibiotic",
        "guidance": "This field should only contain a number (either an integer or a number with decimals), since the \u201c<=\u201d qualifier is implied.",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "amoxicillin-clavulanic_acid_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Intermediate measurement(s), in the units specified in the \u201cAMR_measurement_units\u201d field, where a sample would be considered to have an \u201cintermediate\u201d phenotype for this antibiotic",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "amoxicillin-clavulanic_acid_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Minimum measurement, in the units specified in the \u201cAMR_measurement_units\u201d field, for a sample to be considered \u201cresistant\u201d to this antibiotic",
        "guidance": "This field should only contain a number (either an integer or a number with decimals), since the \u201c>=\u201d qualifier is implied.",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ampicillin_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ampicillin_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ampicillin_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ampicillin_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ampicillin_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ampicillin_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "azithromycin_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "azithromycin_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "azithromycin_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "azithromycin_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "azithromycin_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "azithromycin_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "cefoxitin_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "cefoxitin_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "cefoxitin_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "cefoxitin_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "cefoxitin_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "cefoxitin_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ceftriaxone_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ceftriaxone_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ceftriaxone_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ceftriaxone_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ceftriaxone_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ceftriaxone_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "chloramphenicol_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "chloramphenicol_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "chloramphenicol_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "chloramphenicol_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "chloramphenicol_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "chloramphenicol_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ciprofloxacin_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ciprofloxacin_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ciprofloxacin_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ciprofloxacin_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ciprofloxacin_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "ciprofloxacin_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "gentamicin_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "gentamicin_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "gentamicin_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "gentamicin_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "gentamicin_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "gentamicin_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "meropenem_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "meropenem_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "meropenem_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "meropenem_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "meropenem_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "meropenem_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "nalidixic_acid_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "nalidixic_acid_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "nalidixic_acid_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "nalidixic_acid_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "nalidixic_acid_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "nalidixic_acid_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "streptomycin_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "streptomycin_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "streptomycin_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "streptomycin_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "streptomycin_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "streptomycin_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sulfisoxazole_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sulfisoxazole_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sulfisoxazole_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sulfisoxazole_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sulfisoxazole_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "sulfisoxazole_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "tetracycline_testing_standard",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "tetracycline_testing_standard_version",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "tetracycline_testing_standard_details",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "tetracycline_susceptible_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "tetracycline_intermediate_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      },
      {
        "fieldName": "tetracycline_resistant_breakpoint",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "",
        "guidance": "",
        "examples": "",
        "EXPORT_???": ""
      }
    ]
  }
]