var DATA = [
  {
    "fieldName": "sample identification",
    "children": [
      {
        "fieldName": "unique_ID",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:unique",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Unique ID",
        "guidance": "Field REQUIRED for ALL sample submission. Options: IGSN- http://www.geosamples.org/getigsn ; UUID- https://www.uuidgenerator.net/",
        "examples": "{text}"
      },
      {
        "fieldName": "samp_name",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Sample Name",
        "guidance": "ID that is present on the shipped sample. Human readable.",
        "examples": "{text}"
      },
      {
        "fieldName": "investigation_type",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Analysis/Data Type",
        "guidance": "This field is constrained to contain only a set of limited terms (listed under Expected value) that indicate the types of data that were generated. Include all the data types, this field can have multiple values separated by a ;",
        "examples": "drop down selection list",
        "schema:ItemList": {
          "chemical speciation/mapping": {},
          "genome": {},
          "imaging- electron": {},
          "imaging- ion": {},
          "imaging- light": {},
          "lipidome": {},
          "metabolome": {},
          "molecular structure": {},
          "organic matter": {},
          "proteome": {},
          "transcriptome": {}
        }
      },
      {
        "fieldName": "package",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Sample Type",
        "guidance": "MIxS Package",
        "examples": "{text}"
      },
      {
        "fieldName": "source_mat_id",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Source Material ID",
        "guidance": "A unique identifier assigned to an original material sample collected or to any derived sub-samples. The source material should be listed as a sample to inform details about parent material relationship.",
        "examples": "{text}"
      }
    ]
  },
  {
    "fieldName": "required where applicable",
    "children": [
      {
        "fieldName": "chem_administration",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "chemical administration/addition treatment",
        "guidance": "",
        "examples": "{termLabel} {[termID]}; {timestamp}"
      },
      {
        "fieldName": "watering_regm",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "watering regimen/schedule treatment",
        "guidance": "",
        "examples": "{float} {unit};{Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "air_temp_regm",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "air temperature regimen treatment",
        "guidance": "",
        "examples": "{float} {unit};{Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "gaseous_environment",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "gas evironment/exposure treatment",
        "guidance": "",
        "examples": "{text};{float} {unit};{Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "isotope_exposure",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "isotope exposure/addition treatment",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "climate_environment",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "climate environment treatment",
        "guidance": "",
        "examples": "{text};{Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "humidity_regm",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "humidity regimen/adition treatment",
        "guidance": "",
        "examples": "{float} {unit};{Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "light_regm",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "light regimen treatment",
        "guidance": "",
        "examples": "{text};{float} {unit};{float} {unit}"
      },
      {
        "fieldName": "biotic_regm",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "biotic regimen/addition treatment",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "other",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "treatment-other details",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "samp_collect_device",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "sample collection device",
        "guidance": "Report dimensions and details when applicable",
        "examples": "{text} dimensions"
      },
      {
        "fieldName": "host_common_name",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "common name",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "host_taxid",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "NCBI ID",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "isol_growth_condt",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Isolation and growth conditions",
        "guidance": "",
        "examples": "{DOI} or {URL} or {text}"
      },
      {
        "fieldName": "growth_medium",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Growth Medium",
        "guidance": "",
        "examples": "{text}",
        "schema:ItemList": {
          "3D-structure": {},
          "agar_plate": {},
          "bioreactor": {},
          "broth": {},
          "media_composition": {},
          "plate": {}
        }
      },
      {
        "fieldName": "other",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "treatment-other details",
        "guidance": "",
        "examples": "{text}"
      }
    ]
  },
  {
    "fieldName": "optional",
    "children": [
      {
        "fieldName": "biotic_relationship",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "biotic relationship",
        "guidance": "",
        "examples": "enumeration",
        "schema:ItemList": {
          "commensalism": {},
          "free living": {},
          "mutualism": {},
          "parasitism": {},
          "symbiotic": {}
        }
      },
      {
        "fieldName": "encoded_traits",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "encoded traits",
        "guidance": "",
        "examples": "for plasmid: antibiotic resistance {text}; for phage: converting genes {text}"
      },
      {
        "fieldName": "host_spec_range",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:nonNegativeInteger",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "host specificity or range",
        "guidance": "",
        "examples": "{integer}"
      },
      {
        "fieldName": "oxy_stat_samp",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "oxygenation status of sample",
        "guidance": "",
        "examples": "enumeration",
        "schema:ItemList": {
          "aerobic": {},
          "anaerobic": {},
          "anoxic": {},
          "facultative": {},
          "microaerophilic": {},
          "microanaerobe": {},
          "obligate aerobe": {},
          "obligate anaerobe": {}
        }
      },
      {
        "fieldName": "pathogenicity",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "known pathogenicity",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "propagation",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "propagation",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "ref_biomaterial",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "reference for biomaterial",
        "guidance": "",
        "examples": "{PMID}|{DOI}|{URL}"
      },
      {
        "fieldName": "specific_host",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "specific host",
        "guidance": "",
        "examples": "{NCBI taxid}|{text}"
      },
      {
        "fieldName": "subspecf_gen_lin",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "subspecific genetic lineage",
        "guidance": "",
        "examples": "{rank name}:{text}"
      },
      {
        "fieldName": "trophic_level",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "trophic level",
        "guidance": "",
        "examples": "enumeration",
        "schema:ItemList": {
          "autotroph": {},
          "carboxydotroph": {},
          "chemoautolithotroph": {},
          "chemoautotroph": {},
          "chemoheterotroph": {},
          "chemolithoautotroph": {},
          "chemolithotroph": {},
          "chemoorganoheterotroph": {},
          "chemoorganotroph": {},
          "chemosynthetic": {},
          "chemotroph": {},
          "copiotroph": {},
          "diazotroph": {},
          "facultative": {},
          "heterotroph": {},
          "lithoautotroph": {},
          "lithoheterotroph": {},
          "lithotroph": {},
          "methanotroph": {},
          "methylotroph": {},
          "mixotroph": {},
          "obligate": {},
          "oligotroph": {},
          "organoheterotroph": {},
          "organotroph": {},
          "photoautotroph": {},
          "photoheterotroph": {},
          "photolithoautotroph": {},
          "photolithotroph": {},
          "photosynthetic": {},
          "phototroph": {}
        }
      }
    ]
  },
  {
    "fieldName": "required",
    "children": [
      {
        "fieldName": "growth_facil",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Growth Facility",
        "guidance": "Type of facility or location form where the sample was harvested",
        "examples": "{text}|{termLabel} {[termID]}",
        "schema:ItemList": {
          "experimental_garden": {},
          "field": {},
          "field_incubation": {},
          "greenhouse": {},
          "growth_chamber": {},
          "lab_incubation": {},
          "open_top_chamber": {},
          "other": {}
        }
      },
      {
        "fieldName": "collection_date",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:date",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Collection Date",
        "guidance": "",
        "examples": "{timestamp}"
      },
      {
        "fieldName": "samp_mat_process",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Material Processing",
        "guidance": "",
        "examples": "{text}|{termLabel} {[termID]}"
      },
      {
        "fieldName": "store_cond",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Storage Condition",
        "guidance": "Informs how your sample was stored",
        "examples": "drop down selection list",
        "schema:ItemList": {
          "fresh": {},
          "frozen": {},
          "lyophilized": {},
          "other": {}
        }
      },
      {
        "fieldName": "samp_store_temp",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Storage temperature",
        "guidance": "",
        "examples": "drop down selection list",
        "schema:ItemList": {
          "-20 degree Celsius": {},
          "-80 degree Celsius": {},
          "4 degree Celsius": {},
          "other": {},
          "room temperature": {}
        }
      },
      {
        "fieldName": "samp_size",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Sample size",
        "guidance": "",
        "examples": "{value}{text}"
      }
    ]
  }
]