var DATA = [
  {
    "fieldName": "sample identification",
    "children": [
      {
        "fieldName": "unique_ID",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:unique",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Unique ID",
        "guidance": "Field REQUIRED for ALL sample submission. Options: IGSN- http://www.geosamples.org/getigsn ; UUID- https://www.uuidgenerator.net/",
        "examples": "{text}"
      },
      {
        "fieldName": "samp_name",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Sample Name",
        "guidance": "ID that is present on the shipped sample. Human readable.",
        "examples": "{text}"
      },
      {
        "fieldName": "investigation_type",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Analysis/Data Type",
        "guidance": "This field is constrained to contain only a set of limited terms (listed under Expected value) that indicate the types of data that were generated. Include all the data types, this field can have multiple values separated by a ;",
        "examples": "drop down selection list",
        "schema:ItemList": {
          "chemical speciation/mapping": {},
          "genome": {},
          "imaging- electron": {},
          "imaging- ion": {},
          "imaging- light": {},
          "lipidome": {},
          "metabolome": {},
          "molecular structure": {},
          "organic matter": {},
          "proteome": {},
          "transcriptome": {}
        }
      },
      {
        "fieldName": "package",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Sample Type",
        "guidance": "MIxS Package",
        "examples": "{text}"
      },
      {
        "fieldName": "source_mat_id",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Source Material ID",
        "guidance": "A unique identifier assigned to an original material sample collected or to any derived sub-samples. The source material should be listed as a sample to inform details about parent material relationship.",
        "examples": "{text}"
      }
    ]
  },
  {
    "fieldName": "required where applicable",
    "children": [
      {
        "fieldName": "geo_loc_name",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Geographical Location Name",
        "guidance": "",
        "examples": "country or sea name; region or state; specific location"
      },
      {
        "fieldName": "lat_lon",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "latitude, longitude",
        "guidance": "",
        "examples": "{latitude decimal; longitude decimal}"
      },
      {
        "fieldName": "elev",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:decimal",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "elevation-meters",
        "guidance": "",
        "examples": "{value}"
      },
      {
        "fieldName": "depth",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "depth-meters",
        "guidance": "When sample is collected with a ___ depth and homogenized, please report depth as a ____. (example, 0-10cm for soil collected from the surface to 10cm below and homogenized, or 10-20 for soil collected and homogenized from 10cm below the surface to 20cm).",
        "examples": "{range value}"
      },
      {
        "fieldName": "chem_administration",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "chemical administration/addition treatment",
        "guidance": "",
        "examples": "{termLabel} {[termID]}; {timestamp}"
      },
      {
        "fieldName": "watering_regm",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "watering regimen/schedule treatment",
        "guidance": "",
        "examples": "{float} {unit};{Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "air_temp_regm",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "air temperature regimen treatment",
        "guidance": "",
        "examples": "{float} {unit};{Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "gaseous_environment",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "gas evironment/exposure treatment",
        "guidance": "",
        "examples": "{text};{float} {unit};{Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "isotope_exposure",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "isotope exposure/addition treatment",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "climate_environment",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "climate environment treatment",
        "guidance": "",
        "examples": "{text};{Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "humidity_regm",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "humidity regimen/adition treatment",
        "guidance": "",
        "examples": "{float} {unit};{Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "light_regm",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "light regimen treatment",
        "guidance": "",
        "examples": "{text};{float} {unit};{float} {unit}"
      },
      {
        "fieldName": "biotic_regm",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "biotic regimen/addition treatment",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "other",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "treatment-other details",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "sieving",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Sieve Size",
        "guidance": "",
        "examples": "{value}{text}"
      },
      {
        "fieldName": "samp_collect_device",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "sample collection device",
        "guidance": "Report dimensions and details when applicable",
        "examples": "{text} dimensions"
      },
      {
        "fieldName": "alt",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:decimal",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "altitude-meters",
        "guidance": "",
        "examples": "{value}"
      },
      {
        "fieldName": "other",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "treatment-other details",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "chem_administration",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "chemical administration/addition treatment",
        "guidance": "",
        "examples": "{termLabel} {[termID]}; {timestamp}"
      }
    ]
  },
  {
    "fieldName": "optional",
    "children": [
      {
        "fieldName": "alkalinity",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "alkalinity",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "alkalinity_method",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "alkalinity method",
        "guidance": "",
        "examples": "{text}"
      },
      {
        "fieldName": "alkyl_diethers",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "alkyl diethers",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "aminopept_act",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "aminopeptidase activity",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "ammonium",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "ammonium",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "bacteria_carb_prod",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "bacterial carbon production",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "biomass",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "biomass",
        "guidance": "",
        "examples": "biomass type {text};measurement value {float} {unit}"
      },
      {
        "fieldName": "biotic_relationship",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "biotic relationship",
        "guidance": "",
        "examples": "enumeration",
        "schema:ItemList": {
          "commensalism": {},
          "free living": {},
          "mutualism": {},
          "parasitism": {},
          "symbiotic": {}
        }
      },
      {
        "fieldName": "bishomohopanol",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "bishomohopanol",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "bromide",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "bromide",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "calcium",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "calcium",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "carb_nitro_ratio",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "carbon/nitrogen ratio",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "chloride",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "chloride",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "chlorophyll",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "chlorophyll",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "density",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "density",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "diether_lipids",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "diether lipids",
        "guidance": "",
        "examples": "diether lipid name {text}; measurement value {float} {unit}"
      },
      {
        "fieldName": "diss_carb_dioxide",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "dissolved carbon dioxide",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "diss_hydrogen",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "dissolved hydrogen",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "diss_inorg_carb",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "dissolved inorganic carbon",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "diss_org_carb",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "dissolved organic carbon",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "diss_org_nitro",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "dissolved organic nitrogen",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "diss_oxygen",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "dissolved oxygen",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "extreme_event",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:date",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "history/extreme events",
        "guidance": "",
        "examples": "{timestamp}"
      },
      {
        "fieldName": "fire",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:date",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "history/fire",
        "guidance": "",
        "examples": "{timestamp}"
      },
      {
        "fieldName": "flooding",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:date",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "history/flooding",
        "guidance": "",
        "examples": "{timestamp}"
      },
      {
        "fieldName": "glucosidase_act",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "glucosidase activity",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "magnesium",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "magnesium",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "mean_frict_vel",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "mean friction velocity",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "mean_peak_frict_vel",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "mean peak friction velocity",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "methane",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "methane",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "microbial_biomass",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "microbial biomass",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "microbial_biomass_meth",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "microbial biomass method",
        "guidance": "",
        "examples": "{PMID}|{DOI}|{URL}"
      },
      {
        "fieldName": "misc_param",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "miscellaneous parameter",
        "guidance": "",
        "examples": "parameter name {text}; measurement value {float} {unit}"
      },
      {
        "fieldName": "n_alkanes",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "n-alkanes",
        "guidance": "",
        "examples": "n-alkane name {text}; measurement value {value} {unit}"
      },
      {
        "fieldName": "nitrate",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "nitrate",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "nitrite",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "nitrite",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "nitro",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "nitrogen",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "org_carb",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "organic carbon",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "org_matter",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "organic matter",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "org_nitro",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "organic nitrogen",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "organism_count",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "organism count",
        "guidance": "",
        "examples": "organism name {text}; measurement value {value} {unit}; enumeration [qPCR|ATP|MPN|other]"
      },
      {
        "fieldName": "oxy_stat_samp",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "oxygenation status of sample",
        "guidance": "",
        "examples": "enumeration",
        "schema:ItemList": {
          "aerobic": {},
          "anaerobic": {},
          "anoxic": {},
          "facultative": {},
          "microaerophilic": {},
          "microanaerobe": {},
          "obligate aerobe": {},
          "obligate anaerobe": {}
        }
      },
      {
        "fieldName": "part_org_carb",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "particulate organic carbon",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "particle_class",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "particle classification",
        "guidance": "",
        "examples": "particle name {text}; measurement value {float} {unit}"
      },
      {
        "fieldName": "perturbation",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "perturbation",
        "guidance": "",
        "examples": "perturbation type name {text}; perturbation interval and duration {Rn/start_time/end_time/duration}"
      },
      {
        "fieldName": "petroleum_hydrocarb",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "petroleum hydrocarbon",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "ph",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:decimal",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "pH",
        "guidance": "",
        "examples": "{float}"
      },
      {
        "fieldName": "ph_meth",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "pH method",
        "guidance": "",
        "examples": "{PMID}|{DOI}|{URL}"
      },
      {
        "fieldName": "phaeopigments",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "phaeopigments",
        "guidance": "",
        "examples": "phaeopigment name {text}; measurement value {float} {unit}"
      },
      {
        "fieldName": "phosphate",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "phosphate",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "phosplipid_fatt_acid",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "phospholipid fatty acid",
        "guidance": "",
        "examples": "phospholipid fatty acid name {text}; measurement value {float} {unit}"
      },
      {
        "fieldName": "porosity",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "porosity",
        "guidance": "",
        "examples": "{float} - {float} {unit}"
      },
      {
        "fieldName": "potassium",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "potassium",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "pressure",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "pressure",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "redox_potential",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "redox potential",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "salinity",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "salinity",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "sediment_type",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "sediment type",
        "guidance": "",
        "examples": "enumeration",
        "schema:ItemList": {
          "biogenous": {},
          "cosmogenous": {},
          "hydrogenous": {},
          "lithogenous": {}
        }
      },
      {
        "fieldName": "silicate",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "silicate",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "sodium",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "sodium",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "sulfate",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "sulfate",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "sulfide",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "sulfide",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "temp",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "temperature",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "tidal_stage",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "tidal stage",
        "guidance": "",
        "examples": "enumeration",
        "schema:ItemList": {
          "ebb tide": {},
          "flood tide": {},
          "high tide": {},
          "low tide": {}
        }
      },
      {
        "fieldName": "tot_carb",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "total carbon",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "tot_depth_water_col",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "total depth of water column",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "tot_nitro_content",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "total nitrogen content",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "tot_n_meth",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "total nitrogen content method",
        "guidance": "",
        "examples": "{PMID}|{DOI}|{URL}"
      },
      {
        "fieldName": "tot_org_c_meth",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "total organic carbon method",
        "guidance": "",
        "examples": "{PMID}|{DOI}|{URL}"
      },
      {
        "fieldName": "tot_org_carb",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "total organic carbon",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "turbidity",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "turbidity",
        "guidance": "",
        "examples": "{float} {unit}",
        "pattern": "^[+-]?([0-9]*[.])?[0-9]+ \\S+$"
      },
      {
        "fieldName": "water_content",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:decimal",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "water content",
        "guidance": "",
        "examples": "{float}"
      },
      {
        "fieldName": "water_cont_soil_meth",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "water content method",
        "guidance": "",
        "examples": "{PMID}|{DOI}|{URL}"
      }
    ]
  },
  {
    "fieldName": "required",
    "children": [
      {
        "fieldName": "growth_facil",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Growth Facility",
        "guidance": "Type of facility or location form where the sample was harvested",
        "examples": "{text}|{termLabel} {[termID]}",
        "schema:ItemList": {
          "experimental_garden": {},
          "field": {},
          "field_incubation": {},
          "greenhouse": {},
          "growth_chamber": {},
          "lab_incubation": {},
          "open_top_chamber": {},
          "other": {}
        }
      },
      {
        "fieldName": "collection_date",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:date",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Collection Date",
        "guidance": "",
        "examples": "{timestamp}"
      },
      {
        "fieldName": "samp_mat_process",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Material Processing",
        "guidance": "",
        "examples": "{text}|{termLabel} {[termID]}"
      },
      {
        "fieldName": "store_cond",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Storage Condition",
        "guidance": "Informs how your sample was stored",
        "examples": "drop down selection list",
        "schema:ItemList": {
          "fresh": {},
          "frozen": {},
          "lyophilized": {},
          "other": {}
        }
      },
      {
        "fieldName": "samp_store_temp",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Storage temperature",
        "guidance": "",
        "examples": "drop down selection list",
        "schema:ItemList": {
          "-20 degree Celsius": {},
          "-80 degree Celsius": {},
          "4 degree Celsius": {},
          "other": {},
          "room temperature": {}
        }
      },
      {
        "fieldName": "samp_size",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Sample size",
        "guidance": "",
        "examples": "{value}{text}"
      }
    ]
  }
]