apis:
  bioportal:
    uri: https://data.bioontology.org/
    apikey: 75494b6d-7473-49b5-b47a-6e846f90d16b
    ontologies:
      - envo
  ols:
    uri: http://www.ebi.ac.uk/ols4/api/ontologies/{ontology}/terms/{double_encoded}/graph
    ontologies: []
sssom:
  - ./sources/sssom.tsv
sources:
  envo:
    title: The Environment Ontology
    name: envo
    version: '2025-10-20'
    content_type: OWL
    file_format: owl
    reachable_from:
      source_ontology: https://purl.obolibrary.org/obo/envo.owl
    download_date: '2026-04-16'
    description: ENVO is an ontology which represents knowledge about environments,environmental
      processes, ecosystems, habitats, and related entities
    license: https://creativecommons.org/publicdomain/zero/1.0/
    prefixes:
      BFO: http://purl.obolibrary.org/obo/BFO_
      CHEBI: http://purl.obolibrary.org/obo/CHEBI_
      sesaw: http://purl.obolibrary.org/me/there
  LOINCDataAbsentReason:
    title: DataAbsentReason
    name: LOINCDataAbsentReason
    see_also: https://terminology.hl7.org/7.1.0/en/CodeSystem-data-absent-reason.json.html
    version: 1.0.0
    content_type: LOINCCodeSystem
    file_format: json
    reachable_from:
      source_ontology: https://terminology.hl7.org/7.1.0/en/CodeSystem-data-absent-reason.json
    download_date: '2026-03-26'
    prefixes:
      LOINC: https://loinc.org/
  LOINCPersonalPronouns:
    title: Personal Pronouns
    name: LOINCPersonalPronouns
    version: 2.0.0
    content_type: LOINCValueSet
    file_format: json
    reachable_from:
      source_ontology: https://terminology.hl7.org/7.1.0/en/ValueSet-pronouns.json
    download_date: '2026-03-29'
    see_also: https://terminology.hl7.org/7.1.0/en/ValueSet-pronouns.json.html
    prefixes:
      LOINC: https://loinc.org/
  LOINCValuesetsCda:
    title: LOINC ValuesetsCda Value Sets
    name: LOINCValuesetsCda
    version: null
    content_type: LOINC
    file_format: html
    reachable_from:
      source_ontology: https://terminology.hl7.org/en/valuesets-cda.html
    download_date: '2026-04-01'
    prefixes:
      LOINC: https://loinc.org/
    description: "CDA Value Sets defined and maintained by HL7 as part of the CDA\
      \ family of Standards, and published in the International CDA r2 Base Standard.\
      \  \n    Please note that all of these value sets at this time are drawn from\
      \ the masters published in the HL7 Version 3 International Standard through\
      \ the coremif."
  NAPCSCanadaAgriculturalGoods2022:
    title: Variant of NAPCS Canada 2022 Version 1.0 - Agricultural goods (extension
      variant)
    name: NAPCSCanadaAgriculturalGoods2022
    version: '2022'
    content_type: NAPCSCanada
    file_format: csv
    see_also:
      - https://www.statcan.gc.ca/en/subjects/standard/napcs/2022/index
    prefixes:
      napcscanada: napcscanada/
    reachable_from:
      source_ontology: https://www.statcan.gc.ca/en/media/5274
    download_date: '2026-04-14'
    concise: true
  NSDBSLCv3_2:
    title: Soil Landscapes of Canada version 3.2
    name: NSDBSLCv3_2
    version: '3.2'
    content_type: NSDBSLC
    file_format: html
    reachable_from:
      source_ontology: https://sis.agr.gc.ca/cansis/nsdb/slc/v3.2/index.html
    download_date: '2026-04-14'
    description: SLC version 3.2 is the latest revision of the Soil Landscapes of
      Canada, which was developed by Agriculture and Agri-Food Canada to provide information
      about the country's agricultural soils at the provincial and national levels.  SLC
      v3.2 replaces SLC v3.1.1.
  NSDBSNT_WATERTBL:
    title: Water Table Characteristics
    name: NSDBSNT_WATERTBL
    version: '2'
    content_type: NSDBSNT
    file_format: html
    reachable_from:
      source_ontology: https://sis.agr.gc.ca/cansis/nsdb/soil/v2/snt/watertbl.html
    download_date: '2026-04-15'
    description: Indicates the presence of a water table at a depth of 100cm, and
      identifies its temporal characteristics.
  NSDBSNTv2:
    title: Soil Name Table (SNT)
    name: NSDBSNTv2
    version: '2'
    content_type: NSDBSNT
    file_format: html
    reachable_from:
      source_ontology: https://sis.agr.gc.ca/cansis/nsdb/soil/v2/snt/index.html
    download_date: '2026-04-14'
    description: "The Soil Name Table (SNT) describes the general physical and chemical\
      \ characteristics for all of the soils identified in a geographic region.  \n\
      Soil Order, Great Group and Subgroup are listed, along with attributes such\
      \ as mode of deposition, and drainage class."
  NSDBSoilNameAndLayerV2:
    title: NSDB Soil Name and Layer Tables
    name: NSDBSoilNameAndLayerV2
    version: v2
    content_type: NSDB
    file_format: html
    reachable_from:
      source_ontology: https://sis.agr.gc.ca/cansis/nsdb/soil/v2/index.html
    download_date: '2026-04-14'
    description: This schema contains summary information for named soils within the
      Canadian soil surveys NSDB database
  STATSCAN1326727:
    title: Classification of gender
    name: STATSCAN1326727
    version: null
    content_type: STATSCAN
    file_format: html
    reachable_from:
      source_ontology: https://www23.statcan.gc.ca/imdb/p3VD.pl?Function=getVD&TVD=1326727
    download_date: '2026-04-14'
  STATSCAN1368814:
    title: Variant of Standard Geographical Classification (SGC) 2021 for Agricultural
      Regions
    name: STATSCAN1368814
    version: null
    content_type: STATSCAN
    file_format: html
    reachable_from:
      source_ontology: https://www23.statcan.gc.ca/imdb/p3VD.pl?Function=getVD&TVD=1368814
    download_date: '2026-04-14'
  valuesets_merged_hierarchy:
    title: Merged Value Sets with Hierarchical Structure
    name: valuesets_merged_hierarchy
    version: null
    content_type: LinkML
    file_format: yaml
    reachable_from:
      source_ontology: https://raw.githubusercontent.com/linkml/valuesets/refs/heads/main/src/valuesets/merged/merged_hierarchy.yaml
    download_date: '2026-04-16'
    prefixes:
      _base: http://example.org/
      adms: http://www.w3.org/ns/adms#
      AFO: http://purl.allotrope.org/ontologies/quality#
      AGRO: http://purl.obolibrary.org/obo/AGRO_
      ANSI: https://www.ansi.org/
      arxiv: https://arxiv.org/abs/
      BAO: http://www.bioassayontology.org/bao#BAO_
      BFO: http://purl.obolibrary.org/obo/BFO_
      bibo: http://purl.org/ontology/bibo/
      biolink: https://w3id.org/biolink/
      BLS: https://www.bls.gov/
      brick: https://brickschema.org/schema/Brick#
      BSPO: http://purl.obolibrary.org/obo/BSPO_
      BTO: http://purl.obolibrary.org/obo/BTO_
      caDSR: https://cadsr.cancer.gov/onedata/cde/
      CFR: https://www.ecfr.gov/
      CHEBI: http://purl.obolibrary.org/obo/CHEBI_
      CHMO: http://purl.obolibrary.org/obo/CHMO_
      CIO: http://purl.obolibrary.org/obo/CIO_
      cito: http://purl.org/spar/cito/
      CL: http://purl.obolibrary.org/obo/CL_
      COB: http://purl.obolibrary.org/obo/COB_
      CRediT: https://credit.niso.org/contributor-roles/
      CSCMP: https://cscmp.org/
      CSS: https://www.w3.org/TR/css-color-3/#
      damlpt: http://www.daml.org/2003/01/periodictable/PeriodicTable#
      DataCite: https://datacite.org/schema/kernel-4/
      dcat: http://www.w3.org/ns/dcat#
      DCMITYPE: http://purl.org/dc/dcmitype/
      dcterms: http://purl.org/dc/terms/
      DICOM: http://dicom.nema.org/dcm/
      DOID: http://purl.obolibrary.org/obo/DOID_
      DUO: http://purl.obolibrary.org/obo/DUO_
      EC: https://enzyme.expasy.org/EC/
      ECO: http://purl.obolibrary.org/obo/ECO_
      ECOCORE: http://purl.obolibrary.org/obo/ECOCORE_
      ECTO: http://purl.obolibrary.org/obo/ECTO_
      EDAM: http://edamontology.org/
      EEO: https://www.eeoc.gov/
      EFO: http://www.ebi.ac.uk/efo/EFO_
      EMMO: http://emmo.info/emmo#
      ENM: http://purl.enanomapper.org/onto/ENM_
      ENVO: http://purl.obolibrary.org/obo/ENVO_
      ERO: http://purl.obolibrary.org/obo/ERO_
      euvoc: http://publications.europa.eu/resource/authority/
      example: http://example.org/
      ExO: http://purl.obolibrary.org/obo/ExO_
      FABIO: http://purl.org/spar/fabio/
      FBbi: http://purl.obolibrary.org/obo/FBbi_
      fhir: http://hl7.org/fhir/
      fhir_data_absent_reason: http://terminology.hl7.org/CodeSystem/data-absent-reason
      fibo.commons.PartiesAndSituations: https://spec.edmcouncil.org/fibo/ontology/FBC/ommons/PartiesAndSituations/
      FLSA: https://www.dol.gov/agencies/whd/flsa/
      FOODON: http://purl.obolibrary.org/obo/FOODON_
      gc: http://purl.org/gc/
      GENO: http://purl.obolibrary.org/obo/GENO_
      geonames: http://sws.geonames.org/
      GO: http://purl.obolibrary.org/obo/GO_
      GO_REF: http://purl.obolibrary.org/obo/GO_REF_
      goldbook: https://goldbook.iupac.org/terms/view/
      greg: http://www.w3.org/ns/time/gregorian#
      GRID: https://www.grid.ac/institutes/
      GSSO: http://purl.obolibrary.org/obo/GSSO_
      HEX: https://www.color-hex.com/color/
      HL7: http://terminology.hl7.org/CodeSystem/
      HP: http://purl.obolibrary.org/obo/HP_
      HsapDv: http://purl.obolibrary.org/obo/HsapDv_
      IAEA: https://www.iaea.org/
      iana: https://www.iana.org/assignments/media-types/
      IAO: http://purl.obolibrary.org/obo/IAO_
      ICD10: http://purl.bioontology.org/ontology/ICD10/
      ICDO: http://purl.obolibrary.org/obo/ICDO_
      IEEE: https://standards.ieee.org/
      INES: https://www.iaea.org/resources/databases/ines
      insdc: https://www.insdc.org/controlled-vocabulary/geographic-location/
      IRS: https://www.irs.gov/
      ISIC: https://unstats.un.org/unsd/classifications/Econ/ISIC
      ISM: https://www.ismworld.org/
      ISNI: https://isni.org/isni/
      ISO: https://www.iso.org/
      iso3166loc: http://id.loc.gov/vocabulary/countries/
      ITIL: https://www.itil-officialsite.com/
      IUPAC: http://purl.obolibrary.org/obo/IUPAC_
      LEAN: https://www.lean.org/
      linkml: https://w3id.org/linkml/
      LOINC: https://loinc.org/
      marcrel: http://id.loc.gov/vocabulary/relators/
      MESH: http://id.nlm.nih.gov/mesh/
      mesh: http://id.nlm.nih.gov/mesh/
      METPO: https://w3id.org/metpo/
      MFOEM: http://purl.obolibrary.org/obo/MFOEM_
      MI: http://purl.obolibrary.org/obo/MI_
      MICRO: http://purl.obolibrary.org/obo/MICRO_
      MINMOD: https://minmod.isi.edu/resource/
      mixs: http://purl.obolibrary.org/obo/MIXS_
      MMO: http://purl.obolibrary.org/obo/MMO_
      MmusDv: http://purl.obolibrary.org/obo/MmusDv_
      MOD: http://purl.obolibrary.org/obo/MOD_
      MONDO: http://purl.obolibrary.org/obo/MONDO_
      MOP: http://purl.obolibrary.org/obo/MOP_
      MS: http://purl.obolibrary.org/obo/MS_
      MSIO: http://purl.obolibrary.org/obo/MSIO_
      NAICS: https://www.census.gov/naics/
      NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_
      NCIT: http://purl.obolibrary.org/obo/NCIT_
      NCIt: http://purl.obolibrary.org/obo/NCIT_
      NRC: https://www.nrc.gov/
      OBCS: http://purl.obolibrary.org/obo/OBCS_
      OBI: http://purl.obolibrary.org/obo/OBI_
      oboe-core: http://ecoinformatics.org/oboe/oboe.1.0/oboe-core.owl#
      OEO: http://openenergy-platform.org/ontology/oeo/OEO_
      om: http://www.opengis.net/om/2.0
      omopschema: http://example.org/omop/
      OMP: http://purl.obolibrary.org/obo/OMP_
      OMRSE: http://purl.obolibrary.org/obo/OMRSE_
      OPMI: http://purl.obolibrary.org/obo/OPMI_
      orcid: https://orcid.org/
      ORCID: https://orcid.org/
      OSHA: https://www.osha.gov/
      owl: http://www.w3.org/2002/07/owl#
      PATO: http://purl.obolibrary.org/obo/PATO_
      pdg: https://pdgapi.lbl.gov/summaries/
      PECO: http://purl.obolibrary.org/obo/PECO_
      PMI: https://www.pmi.org/
      PO: http://purl.obolibrary.org/obo/PO_
      PR: http://purl.obolibrary.org/obo/PR_
      premis: http://id.loc.gov/vocabulary/preservation/
      PRIDE: http://purl.obolibrary.org/obo/PRIDE_
      PROCO: http://purl.obolibrary.org/obo/PROCO_
      prov: http://www.w3.org/ns/prov#
      quantitykind: http://qudt.org/vocab/quantitykind/
      QUDT: http://qudt.org/vocab/unit/
      rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
      rdfs: http://www.w3.org/2000/01/rdf-schema#
      REX: http://purl.obolibrary.org/obo/REX_
      RO: http://purl.obolibrary.org/obo/RO_
      ROR: https://ror.org/
      RXNO: http://purl.obolibrary.org/obo/RXNO_
      RxNorm: http://purl.bioontology.org/ontology/RXNORM/
      SBA: https://www.sba.gov/
      SBO: http://biomodels.net/SBO/SBO_
      schema: http://schema.org/
      SCOR: https://www.apics.org/apics-for-business/frameworks/scor
      SEC: https://www.sec.gov/
      seer: https://seer.cancer.gov/
      SHRM: https://www.shrm.org/
      SI: http://www.bipm.org/en/si/
      SIC: https://www.osha.gov/data/sic-manual/
      SIO: http://semanticscience.org/resource/SIO_
      SLM: https://swisslipids.org/rdf/SLM_
      SNOMED: http://snomed.info/id/
      SO: http://purl.obolibrary.org/obo/SO_
      SPDX: https://spdx.org/licenses/
      spdx: https://spdx.org/licenses/
      SRAO: http://www.fairsharing.org/ontology/subject/SRAO_
      STATO: http://purl.obolibrary.org/obo/STATO_
      sweet: http://sweetontology.net/
      SWO: http://purl.obolibrary.org/obo/SWO_
      TAXRANK: http://purl.obolibrary.org/obo/TAXRANK_
      TIME: http://www.w3.org/2006/time#
      TO: http://purl.obolibrary.org/obo/TO_
      TQM: https://www.asq.org/
      UBERON: http://purl.obolibrary.org/obo/UBERON_
      UCUM: http://unitsofmeasure.org/
      ucum: http://unitsofmeasure.org/
      uniprot.proteome: http://purl.uniprot.org/proteomes/
      UO: http://purl.obolibrary.org/obo/UO_
      valuesets: https://w3id.org/valuesets/
      valuesets_meta: https://w3id.org/valuesets/meta/
      VO: http://purl.obolibrary.org/obo/VO_
      VT: http://purl.obolibrary.org/obo/VT_
      wgs84: http://www.w3.org/2003/01/geo/wgs84_pos#
      wikidata: http://www.wikidata.org/entity/
      WNA: https://world-nuclear.org/
      X11: https://en.wikipedia.org/wiki/X11_color_names#
      xsd: http://www.w3.org/2001/XMLSchema#
