locales:
  - en
  - fr
apis:
  agrovoc:
    type:
      sparql:
        uri: https://agrovoc.fao.org/sparql/
      rest:
        uri: https://agrovoc.fao.org/browse/rest/v1/
    ontologies:
      - agrovoc
  bioportal:
    type:
      rest:
        uri: https://data.bioontology.org/
        apikey: 75494b6d-7473-49b5-b47a-6e846f90d16b
    ontologies:
      - envo
  ols:
    type:
      rest:
        uri: http://www.ebi.ac.uk/ols4/api/ontologies/{ontology}/terms/{double_encoded}/graph
    ontologies: []
sssom:
  - ./sources/sssom.tsv
sources:
  AFCPicklists:
    title: AgriFoodCA Picklists
    name: AFCPicklists
    version: null
    content_type: AgriFoodCA
    file_format: yaml
    reachable_from:
      source_ontology: https://github.com/agrifooddatacanada/picklists_for_schemas/tree/main/picklists
    download_date: '2026-04-26'
    description: Agricultural food data picklists from AgriFoodData Canada
  AFCSoilAerationStatus:
    title: Soil aeration status
    name: AFCSoilAerationStatus
    version: null
    content_type: AgriFoodCA
    file_format: csv
    reachable_from:
      source_ontology: https://raw.githubusercontent.com/agrifooddatacanada/picklists_for_schemas/main/picklists/soil_aeration_status.csv
    download_date: '2026-04-26'
    description: Qualitative oxygen availability status.
    see_also: https://static.ixambee.com/public/miscellaneous-pdf/physical_and_chemical_properties_of_soil1720241418.pdf
  AFCSoilDrainage:
    title: Soil Drainage Class
    name: AFCSoilDrainage
    version: null
    content_type: AgriFoodCA
    file_format: csv
    reachable_from:
      source_ontology: https://raw.githubusercontent.com/agrifooddatacanada/picklists_for_schemas/main/picklists/soil_drainage.csv
    download_date: '2026-04-26'
    description: Indicates the type of drainage found within a soil profile.
    see_also: https://sis.agr.gc.ca/cansis/nsdb/soil/v2/snt/drainage.html
  agrovoc:
    name: agrovoc
    title: AGROVOC Multilingual Thesaurus
    version: null
    content_type: OntologyAPI
    file_format: json
    description: AGROVOC is a multilingual, structured thesaurus coordinated by the
      Food and Agriculture Organization (FAO) of the United Nations since the early
      1980s. It acts as a controlled vocabulary covering all areas of interest to
      FAO, such as food, agriculture, fisheries, forestry, and the environment.
    reachable_from:
      api:
        agrovoc:
          type: sparql
      source_nodes:
        - 'agrovoc:c_26950'
      include_self: true
    prefixes:
      agrovoc: http://aims.fao.org/aos/agrovoc/
  AGROVOC_c_26950:
    title: fishing
    name: AGROVOC_c_26950
    version: null
    content_type: OntologyAPI
    file_format: json
    reachable_from:
      api:
        agrovoc:
          type: sparql
      source_nodes:
        - 'agrovoc:c_26950'
      include_self: true
    download_date: '2026-04-22'
    description: '"Fishing" defines the extent of the activities that should be regarded
      as fishing and include not only the harvesting or catching of fish but also
      any activity undertaken to search for, attract and locate fish prior to its
      being caught. "Fishing" is a general term; therefore it is recommended to use
      specific terms such as "commercial fishing", "experimental fishing", "sport
      fishing", etc. As an adjective is used for example: "fishing activity", "fishing
      boat".'
    prefixes:
      agrovoc: http://aims.fao.org/aos/agrovoc/
  AGROVOC_c_2808:
    title: farmland
    name: AGROVOC_c_2808
    version: null
    content_type: OntologyAPI
    file_format: json
    reachable_from:
      api:
        agrovoc:
          type: sparql
      source_nodes:
        - 'agrovoc:c_2808'
      include_self: true
    download_date: '2026-04-24'
    description: Land which is or can be used for agriculture without further clearing
      or draining; for forest land use <24843>
    prefixes:
      agrovoc: http://aims.fao.org/aos/agrovoc/
  envo:
    title: The Environment Ontology
    name: envo
    version: '2025-10-20'
    content_type: OWL
    file_format: owl
    reachable_from:
      source_ontology: https://purl.obolibrary.org/obo/envo.owl
    download_date: '2026-04-16'
    description: ENVO is an ontology which represents knowledge about environments,environmental
      processes, ecosystems, habitats, and related entities
    license: https://creativecommons.org/publicdomain/zero/1.0/
    prefixes:
      BFO: http://purl.obolibrary.org/obo/BFO_
      CHEBI: http://purl.obolibrary.org/obo/CHEBI_
      testing: http://purl.obolibrary.org/testing
  LOINCDataAbsentReason:
    title: DataAbsentReason
    name: LOINCDataAbsentReason
    see_also: https://terminology.hl7.org/7.1.0/en/CodeSystem-data-absent-reason.json.html
    version: 1.0.0
    content_type: LOINCCodeSystem
    file_format: json
    reachable_from:
      source_ontology: https://terminology.hl7.org/7.1.0/en/CodeSystem-data-absent-reason.json
    download_date: '2026-03-26'
    prefixes:
      LOINC: https://loinc.org/
  LOINCFoodTypeCodes:
    title: Food Type Codes
    name: LOINCFoodTypeCodes
    version: 6.0.0-ballot4
    content_type: LOINCValueSet
    file_format: json
    reachable_from:
      source_ontology: https://build.fhir.org/valueset-food-type.json
    download_date: '2026-04-24'
    see_also: https://build.fhir.org/valueset-food-type.json.html
    prefixes:
      LOINC: https://loinc.org/
  LOINCPersonalPronouns:
    title: Personal Pronouns
    name: LOINCPersonalPronouns
    version: 2.0.0
    content_type: LOINCValueSet
    file_format: json
    reachable_from:
      source_ontology: https://terminology.hl7.org/7.1.0/en/ValueSet-pronouns.json
    download_date: '2026-03-29'
    see_also: https://terminology.hl7.org/7.1.0/en/ValueSet-pronouns.json.html
    prefixes:
      LOINC: https://loinc.org/
  LOINCValuesetsCda:
    title: LOINC ValuesetsCda Value Sets
    name: LOINCValuesetsCda
    version: null
    content_type: LOINC
    file_format: html
    reachable_from:
      source_ontology: https://terminology.hl7.org/en/valuesets-cda.html
    download_date: '2026-04-01'
    prefixes:
      LOINC: https://loinc.org/
    description: "CDA Value Sets defined and maintained by HL7 as part of the CDA\
      \ family of Standards, and published in the International CDA r2 Base Standard.\
      \  \n    Please note that all of these value sets at this time are drawn from\
      \ the masters published in the HL7 Version 3 International Standard through\
      \ the coremif."
  NAPCSCanadaAgriculturalGoods2022:
    title: Variant of NAPCS Canada 2022 Version 1.0 - Agricultural goods (extension
      variant)
    name: NAPCSCanadaAgriculturalGoods2022
    version: '2022'
    content_type: NAPCSCanada
    file_format: csv
    see_also:
      - https://www.statcan.gc.ca/en/subjects/standard/napcs/2022/index
    prefixes:
      napcscanada: napcscanada/
    reachable_from:
      source_ontology: https://www.statcan.gc.ca/en/media/5274
    download_date: '2026-04-14'
    concise: true
  NRCSSoilFieldBook:
    title: USDA NRCS Field Book for Describing and Sampling Soils
    name: NRCSSoilFieldBook
    version: '4.0'
    content_type: NRCSSoilFieldBook
    file_format: pdf
    reachable_from:
      source_ontology: https://www.nrcs.usda.gov/sites/default/files/2025-05/Field-Book-for-Describing-and-Sampling-Soils-Ver4.pdf
    download_date: '2026-04-28'
    description: The U.S. Department of Agriculture Natural Resources Conservation
      Service Field Book for Describing and Sampling Soils provides a standard for
      many soil description variables.  This resource lists selected categorical picklists
      for soil type, etc.
  NSDBSLCv3_2:
    title: Soil Landscapes of Canada version 3.2
    name: NSDBSLCv3_2
    version: '3.2'
    content_type: NSDBSLC
    file_format: html
    reachable_from:
      source_ontology: https://sis.agr.gc.ca/cansis/nsdb/slc/v3.2/index.html
    download_date: '2026-04-14'
    description: SLC version 3.2 is the latest revision of the Soil Landscapes of
      Canada, which was developed by Agriculture and Agri-Food Canada to provide information
      about the country's agricultural soils at the provincial and national levels.  SLC
      v3.2 replaces SLC v3.1.1.
  NSDBSNT_DRAINAGE:
    title: Soil Drainage Class
    name: NSDBSNT_DRAINAGE
    version: '2'
    content_type: NSDBSNT
    file_format: html
    reachable_from:
      source_ontology: https://sis.agr.gc.ca/cansis/nsdb/soil/v2/snt/drainage.html
    download_date: '2026-04-26'
    description: Indicates the type of drainage found within a soil profile. First
      used in SLC 3.0. Identical classes to drainage in SLC 1.0, but codes differ.
  NSDBSNT_WATERTBL:
    title: Water Table Characteristics
    name: NSDBSNT_WATERTBL
    version: '2'
    content_type: NSDBSNT
    file_format: html
    reachable_from:
      source_ontology: https://sis.agr.gc.ca/cansis/nsdb/soil/v2/snt/watertbl.html
    download_date: '2026-04-15'
    description: Indicates the presence of a water table at a depth of 100cm, and
      identifies its temporal characteristics.
  NSDBSNTv2:
    title: Soil Name Table (SNT)
    name: NSDBSNTv2
    version: '2'
    content_type: NSDBSNT
    file_format: html
    reachable_from:
      source_ontology: https://sis.agr.gc.ca/cansis/nsdb/soil/v2/snt/index.html
    download_date: '2026-04-14'
    description: "The Soil Name Table (SNT) describes the general physical and chemical\
      \ characteristics for all of the soils identified in a geographic region.  \n\
      Soil Order, Great Group and Subgroup are listed, along with attributes such\
      \ as mode of deposition, and drainage class."
  NSDBSoilNameAndLayerV2:
    title: NSDB Soil Name and Layer Tables
    name: NSDBSoilNameAndLayerV2
    version: v2
    content_type: NSDB
    file_format: html
    reachable_from:
      source_ontology: https://sis.agr.gc.ca/cansis/nsdb/soil/v2/index.html
    download_date: '2026-04-14'
    description: This schema contains summary information for named soils within the
      Canadian soil surveys NSDB database
  SNOMED56265001:
    title: Heart disease
    name: SNOMED56265001
    version: http://snomed.info/sct/900000000000207008/version/20251017
    content_type: OntologyAPI
    file_format: json
    reachable_from:
      api:
        ols:
          type: rest
      source_nodes:
        - 'SNOMED:56265001'
      include_self: true
    download_date: '2026-04-25'
    prefixes:
      SNOMED: http://snomed.info/id/
  STATSCAN1326727:
    title: Classification of gender
    name: STATSCAN1326727
    version: null
    content_type: STATSCAN
    file_format: html
    reachable_from:
      source_ontology: https://www23.statcan.gc.ca/imdb/p3VD.pl?Function=getVD&TVD=1326727
    download_date: '2026-04-14'
  STATSCAN1368814:
    title: Variant of Standard Geographical Classification (SGC) 2021 for Agricultural
      Regions
    name: STATSCAN1368814
    version: null
    content_type: STATSCAN
    file_format: html
    reachable_from:
      source_ontology: https://www23.statcan.gc.ca/imdb/p3VD.pl?Function=getVD&TVD=1368814
    download_date: '2026-04-14'
  valuesets_merged_hierarchy:
    title: Merged Value Sets with Hierarchical Structure
    name: valuesets_merged_hierarchy
    version: null
    content_type: LinkML
    file_format: yaml
    reachable_from:
      source_ontology: https://raw.githubusercontent.com/linkml/valuesets/refs/heads/main/src/valuesets/merged/merged_hierarchy.yaml
    download_date: '2026-04-24'
    minus:
      concepts:
        - academic
        - bio
        - bioprocessing
        - business
        - chemistry
        - clinical
        - computing
        - visual
        - energy
        - environmental_health
        - geography
        - industry
        - materials_science
        - maturity_levels
        - medical
        - microelectronics
        - mining_processing
        - organizations
        - physics
        - publishing
        - quantum
        - spatial
        - binary_classification
        - priority_severity
        - sentiment_analysis
        - text_classification
        - demographics
        - hydrology
        - subsurface
        - BusinessTimeFrame
        - BioticInteractionType
        - Disease
        - Cancer
        - GeneticDisease
        - InfectiousDisease
        - Protein
    include:
      concepts:
        - PublicationType
        - ResearchField
        - ResearchRole
        - BasicColorEnum
        - PesticideTypeEnum
        - ExtremeWeatherEventEnum
        - PesticideTypeEnum
        - CanadianProvinceCodeEnum
        - ImagingAssayEnum
        - MassSpectrometryAssayEnum
        - SequencingAssayEnum
        - Environment
        - EnvironmentalMaterial
        - FlowerColorEnum
        - PlantLeafColorEnum
        - InsdcMissingValueEnum
        - plant_developmental_stages
        - plant_experimental_conditions
        - sequencing_platforms
        - specimen_processing
        - TaxonomicRank
        - file_formats
        - mime_types
