var DATA = [
  {
    "fieldName": "NMDC slots",
    "children": [
      {
        "fieldName": "id",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "A unique identifier for a thing. Must be either a CURIE shorthand for a URI or a complete URI",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "identifier",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": " ",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "name",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "A human readable label for an entity",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "ncbi_taxonomy_name",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": " ",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "env_package",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "MIxS extension for reporting of measurements and observations obtained from one or more of the environments where the sample was obtained. All environmental packages listed here are further defined in separate subtables. By giving the name of the environmental package, a selection of fields can be made from the subtables and can be reported",
        "guidance": "Expected value: enumeration. Position: 13.0",
        "examples": "soil"
      },
      {
        "fieldName": "samp_mat_process",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "A brief description of any processing applied to the sample during or after retrieving the sample from environment, or a link to the relevant protocol(s) performed.",
        "guidance": "Expected value: text. Position: 32.0",
        "examples": "filtering of seawater, storing samples in ethanol"
      },
      {
        "fieldName": "ecosystem",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "TODO",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "ecosystem_category",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "TODO",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "ecosystem_type",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "TODO",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "ecosystem_subtype",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "TODO",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "specific_ecosystem",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "TODO",
        "guidance": "",
        "examples": ""
      },
      {
        "fieldName": "Study IDs",
        "capitalize": "",
        "ontology_id": "",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "recommended",
        "description": "|-seperated list of NMDC study identifiers",
        "guidance": "",
        "examples": ""
      }
    ]
  },
  {
    "fieldName": "environment field",
    "children": [
      {
        "fieldName": "alt",
        "capitalize": "",
        "ontology_id": "MIXS:0000094",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Altitude is a term used to identify heights of objects such as airplanes, space shuttles, rockets, atmospheric balloons and heights of places such as atmospheric layers and clouds. It is used to measure the height of an object which is above the earth's surface. In this context, the altitude measurement is the vertical distance between the earth's surface above sea level and the sampled position in the air",
        "guidance": "Expected value: measurement value. This field is used in: 3 packages: air, host-associated, miscellaneous natural or artificial environment",
        "examples": "100 meter"
      },
      {
        "fieldName": "collection_date",
        "capitalize": "",
        "ontology_id": "MIXS:0000011",
        "datatype": "xs:date",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "The time of sampling, either as an instance (single point in time) or interval. In case no exact time is available, the date/time can be right truncated i.e. all of these are valid times: 2008-01-23T19:23:10+00:00; 2008-01-23T19:23:10; 2008-01-23; 2008-01; 2008; Except: 2008-01; 2008 all are ISO8601 compliant",
        "guidance": "Expected value: date and time. Position: 9.0",
        "examples": "2018-05-11T10:00:00+01:00; 2018-05-11"
      },
      {
        "fieldName": "depth",
        "capitalize": "",
        "ontology_id": "MIXS:0000018",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "The vertical distance below local surface, e.g. for sediment or soil samples depth is measured from sediment or soil surface, respectively. Depth can be reported as an interval for subsurface samples.",
        "guidance": "Expected value: measurement value. Position: 6.0. This field is used in: 8 packages: host-associated, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, soil, wastewater_sludge, water",
        "examples": "10 meter"
      },
      {
        "fieldName": "elev",
        "capitalize": "",
        "ontology_id": "MIXS:0000093",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Elevation of the sampling site is its height above a fixed reference point, most commonly the mean sea level. Elevation is mainly used when referring to points on the earth's surface, while altitude is used for points above the surface, such as an aircraft in flight or a spacecraft in orbit.",
        "guidance": "Expected value: measurement value. Position: 7.0. This field is used in: 9 packages: air, host-associated, hydrocarbon resources-cores, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, soil, water",
        "examples": "100 meter"
      },
      {
        "fieldName": "env_broad_scale",
        "capitalize": "",
        "ontology_id": "MIXS:0000012",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Report the major environmental system the sample or specimen came from. The system(s) identified should have a coarse spatial grain, to provide the general environmental context of where the sampling was done (e.g. in the desert or a rainforest). We recommend using subclasses of EnvOs biome class:  http://purl.obolibrary.org/obo/ENVO_00000428. EnvO documentation about how to use the field: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS",
        "guidance": "Expected value: The major environment type(s) where the sample was collected. Recommend subclasses of biome [ENVO:00000428]. Multiple terms can be separated by one or more pipes.. Position: 10.0",
        "examples": "oceanic epipelagic zone biome [ENVO:01000033] for annotating a water sample from the photic zone in middle of the Atlantic Ocean"
      },
      {
        "fieldName": "env_local_scale",
        "capitalize": "",
        "ontology_id": "MIXS:0000013",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Report the entity or entities which are in the sample or specimens local vicinity and which you believe have significant causal influences on your sample or specimen. We recommend using EnvO terms which are of smaller spatial grain than your entry for env_broad_scale. Terms, such as anatomical sites, from other OBO Library ontologies which interoperate with EnvO (e.g. UBERON) are accepted in this field. EnvO documentation about how to use the field: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS",
        "guidance": "Expected value: Environmental entities having causal influences upon the entity at time of sampling.. Position: 11.0",
        "examples": "litter layer [ENVO:01000338]; Annotating a pooled sample taken from various vegetation layers in a forest consider: canopy [ENVO:00000047]|herb and fern layer [ENVO:01000337]|litter layer [ENVO:01000338]|understory [01000335]|shrub layer [ENVO:01000336]."
      },
      {
        "fieldName": "env_medium",
        "capitalize": "",
        "ontology_id": "MIXS:0000014",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Report the environmental material(s) immediately surrounding the sample or specimen at the time of sampling. We recommend using subclasses of 'environmental material' (http://purl.obolibrary.org/obo/ENVO_00010483). EnvO documentation about how to use the field: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS . Terms from other OBO ontologies are permissible as long as they reference mass/volume nouns (e.g. air, water, blood) and not discrete, countable entities (e.g. a tree, a leaf, a table top).",
        "guidance": "Expected value: The material displaced by the entity at time of sampling. Recommend subclasses of environmental material [ENVO:00010483].. Position: 12.0",
        "examples": "soil [ENVO:00001998]; Annotating a fish swimming in the upper 100 m of the Atlantic Ocean, consider: ocean water [ENVO:00002151]. Example: Annotating a duck on a pond consider: pond water [ENVO:00002228]|air [ENVO_00002005]"
      },
      {
        "fieldName": "geo_loc_name",
        "capitalize": "",
        "ontology_id": "MIXS:0000010",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "The geographical origin of the sample as defined by the country or sea name followed by specific region name. Country or sea names should be chosen from the INSDC country list (http://insdc.org/country.html), or the GAZ ontology (http://purl.bioontology.org/ontology/GAZ)",
        "guidance": "Expected value: country or sea name (INSDC or GAZ): region(GAZ), specific location name. Position: 8.0",
        "examples": "USA: Maryland, Bethesda"
      },
      {
        "fieldName": "lat_lon",
        "capitalize": "",
        "ontology_id": "MIXS:0000009",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "The geographical origin of the sample as defined by latitude and longitude. The values should be reported in decimal degrees and in WGS84 system",
        "guidance": "Expected value: decimal degrees,  limit to 8 decimal points. Position: 5.0",
        "examples": "50.586825 6.408977"
      },
      {
        "fieldName": "temp",
        "capitalize": "",
        "ontology_id": "MIXS:0000113",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Temperature of the sample at the time of sampling.",
        "guidance": "Expected value: measurement value. Preferred unit: degree Celsius. Position: 40.0. This field is used in: 15 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "25 degree Celsius"
      }
    ]
  },
  {
    "fieldName": "core field",
    "children": [
      {
        "fieldName": "ances_data",
        "capitalize": "",
        "ontology_id": "MIXS:0000247",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Information about either pedigree or other ancestral information description (e.g. parental variety in case of mutant or selection), e.g. A/3*B (meaning [(A x B) x B] x B)",
        "guidance": "Expected value: free text. Occurrence: 1. Position: 1.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "A/3*B"
      },
      {
        "fieldName": "biol_stat",
        "capitalize": "",
        "ontology_id": "MIXS:0000858",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The level of genome modification.",
        "guidance": "Expected value: enumeration. Occurrence: 1. Position: 2.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "natural",
        "schema:ItemList": {
          "wild": {},
          "natural": {},
          "semi-natural": {},
          "inbred line": {},
          "breeder's line": {},
          "hybrid": {},
          "clonal selection": {},
          "mutant": {}
        }
      },
      {
        "fieldName": "blood_press_diast",
        "capitalize": "",
        "ontology_id": "MIXS:0000258",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Resting diastolic blood pressure, measured as mm mercury",
        "guidance": "Expected value: measurement value. Preferred unit: millimeter mercury. Occurrence: 1. Position: 31.0. This field is used uniquely in: host-associated",
        "examples": ""
      },
      {
        "fieldName": "blood_press_syst",
        "capitalize": "",
        "ontology_id": "MIXS:0000259",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Resting systolic blood pressure, measured as mm mercury",
        "guidance": "Expected value: measurement value. Preferred unit: millimeter mercury. Occurrence: 1. Position: 32.0. This field is used uniquely in: host-associated",
        "examples": ""
      },
      {
        "fieldName": "chem_administration",
        "capitalize": "",
        "ontology_id": "MIXS:0000751",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "List of chemical compounds administered to the host or site where sampling occurred, and when (e.g. Antibiotics, n fertilizer, air filter); can include multiple compounds. For chemical entities of biological interest ontology (chebi) (v 163), http://purl.bioontology.org/ontology/chebi",
        "guidance": "Expected value: CHEBI;timestamp. Occurrence: m. Position: 1.0. This field is used in: 13 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "agar [CHEBI:2509];2018-05-11T20:00Z"
      },
      {
        "fieldName": "genetic_mod",
        "capitalize": "",
        "ontology_id": "MIXS:0000859",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Genetic modifications of the genome of an organism, which may occur naturally by spontaneous mutation, or be introduced by some experimental means, e.g. specification of a transgene or the gene knocked-out or details of transient transfection",
        "guidance": "Expected value: PMID,DOI,url or free text. Occurrence: 1. Position: 3.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "aox1A transgenic"
      },
      {
        "fieldName": "gravidity",
        "capitalize": "",
        "ontology_id": "MIXS:0000875",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Whether or not subject is gravid, and if yes date due or date post-conception, specifying which is used",
        "guidance": "Expected value: gravidity status;timestamp. Occurrence: 1. Position: 35.0. This field is used uniquely in: host-associated",
        "examples": "yes;due date:2018-05-11"
      },
      {
        "fieldName": "host_age",
        "capitalize": "",
        "ontology_id": "MIXS:0000255",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Age of host at the time of sampling; relevant scale depends on species and study, e.g. Could be seconds for amoebae or centuries for trees",
        "guidance": "Expected value: value. Preferred unit: year, day, hour. Occurrence: 1. Position: 9.0. This field is used in: 7 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, plant-associated",
        "examples": "10 days"
      },
      {
        "fieldName": "host_body_habitat",
        "capitalize": "",
        "ontology_id": "MIXS:0000866",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Original body habitat where the sample was obtained from",
        "guidance": "Expected value: free text. Occurrence: 1. Position: 14.0. This field is used uniquely in: host-associated",
        "examples": "nasopharynx"
      },
      {
        "fieldName": "host_body_product",
        "capitalize": "",
        "ontology_id": "MIXS:0000888",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Substance produced by the body, e.g. Stool, mucus, where the sample was obtained from. For foundational model of anatomy ontology (fma) or Uber-anatomy ontology (UBERON) terms, please see https://www.ebi.ac.uk/ols/ontologies/fma or https://www.ebi.ac.uk/ols/ontologies/uberon",
        "guidance": "Expected value: FMA or UBERON. Occurrence: 1. Position: 16.0. This field is used in: 6 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal",
        "examples": "Portion of mucus [fma66938]"
      },
      {
        "fieldName": "host_body_site",
        "capitalize": "",
        "ontology_id": "MIXS:0000867",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Name of body site where the sample was obtained from, such as a specific organ or tissue (tongue, lung etc...). For foundational model of anatomy ontology (fma) (v 4.11.0) or Uber-anatomy ontology (UBERON) (v releases/2014-06-15) terms, please see http://purl.bioontology.org/ontology/FMA or http://purl.bioontology.org/ontology/UBERON",
        "guidance": "Expected value: FMA or UBERON. Occurrence: 1. Position: 15.0. This field is used in: 6 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal",
        "examples": "gill [UBERON:0002535]"
      },
      {
        "fieldName": "host_body_temp",
        "capitalize": "",
        "ontology_id": "MIXS:0000274",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Core body temperature of the host when sample was collected",
        "guidance": "Expected value: measurement value. Preferred unit: degree Celsius. Occurrence: 1. Position: 29.0. This field is used in: 6 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal",
        "examples": "15 degree Celsius"
      },
      {
        "fieldName": "host_color",
        "capitalize": "",
        "ontology_id": "MIXS:0000260",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The color of host",
        "guidance": "Expected value: color. Occurrence: 1. Position: 33.0. This field is used uniquely in: host-associated",
        "examples": ""
      },
      {
        "fieldName": "host_common_name",
        "capitalize": "",
        "ontology_id": "MIXS:0000248",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Common name of the host.",
        "guidance": "Expected value: common name. Occurrence: 1. Position: 4.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "human"
      },
      {
        "fieldName": "host_diet",
        "capitalize": "",
        "ontology_id": "MIXS:0000869",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Type of diet depending on the host, for animals omnivore, herbivore etc., for humans high-fat, meditteranean etc.; can include multiple diet types",
        "guidance": "Expected value: diet type. Occurrence: m. Position: 20.0. This field is used in: 6 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal",
        "examples": "herbivore"
      },
      {
        "fieldName": "host_dry_mass",
        "capitalize": "",
        "ontology_id": "MIXS:0000257",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Measurement of dry mass",
        "guidance": "Expected value: measurement value. Preferred unit: kilogram, gram. Occurrence: 1. Position: 30.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "500 gram"
      },
      {
        "fieldName": "host_family_relation",
        "capitalize": "",
        "ontology_id": "MIXS:0000872",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Familial relationships to other hosts in the same study; can include multiple relationships",
        "guidance": "Expected value: relationship type;arbitrary identifier. Occurrence: m. Position: 24.0. This field is used in: 6 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal",
        "examples": "offspring;Mussel25"
      },
      {
        "fieldName": "host_genotype",
        "capitalize": "",
        "ontology_id": "MIXS:0000365",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Observed genotype",
        "guidance": "Expected value: genotype. Occurrence: 1. Position: 27.0. This field is used in: 7 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, plant-associated",
        "examples": "C57BL/6"
      },
      {
        "fieldName": "host_growth_cond",
        "capitalize": "",
        "ontology_id": "MIXS:0000871",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Literature reference giving growth conditions of the host",
        "guidance": "Expected value: PMID,DOI,url or free text. Occurrence: 1. Position: 22.0. This field is used uniquely in: host-associated",
        "examples": "https://academic.oup.com/icesjms/article/68/2/349/617247"
      },
      {
        "fieldName": "host_height",
        "capitalize": "",
        "ontology_id": "MIXS:0000264",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The height of subject",
        "guidance": "Expected value: measurement value. Preferred unit: centimeter, millimeter, meter. Occurrence: 1. Position: 18.0. This field is used in: 7 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, plant-associated",
        "examples": "0.1 meter"
      },
      {
        "fieldName": "host_infra_spec_name",
        "capitalize": "",
        "ontology_id": "MIXS:0000253",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Taxonomic information about the host below subspecies level",
        "guidance": "Expected value: name. Occurrence: 1. Position: 25.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "borealis"
      },
      {
        "fieldName": "host_infra_spec_rank",
        "capitalize": "",
        "ontology_id": "MIXS:0000254",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Taxonomic rank information about the host below subspecies level, such as variety, form, rank etc.",
        "guidance": "Expected value: rank. Occurrence: 1. Position: 26.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "subspecies"
      },
      {
        "fieldName": "host_last_meal",
        "capitalize": "",
        "ontology_id": "MIXS:0000870",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Content of last meal and time since feeding; can include multiple values",
        "guidance": "Expected value: content;duration. Occurrence: m. Position: 21.0. This field is used in: 6 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal",
        "examples": "corn feed;P2H"
      },
      {
        "fieldName": "host_length",
        "capitalize": "",
        "ontology_id": "MIXS:0000256",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The length of subject",
        "guidance": "Expected value: measurement value. Preferred unit: centimeter, millimeter, meter. Occurrence: 1. Position: 19.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "1 meter"
      },
      {
        "fieldName": "host_life_stage",
        "capitalize": "",
        "ontology_id": "MIXS:0000251",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Description of life stage of host",
        "guidance": "Expected value: stage. Occurrence: 1. Position: 10.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "adult"
      },
      {
        "fieldName": "host_phenotype",
        "capitalize": "",
        "ontology_id": "MIXS:0000874",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Phenotype of human or other host. For phenotypic quality ontology (pato) (v 2018-03-27) terms, please see http://purl.bioontology.org/ontology/pato. For Human Phenotype Ontology (HP) (v 2018-06-13) please see http://purl.bioontology.org/ontology/HP",
        "guidance": "Expected value: PATO or HP. Occurrence: 1. Position: 28.0. This field is used in: 7 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, plant-associated",
        "examples": "elongated [PATO:0001154]"
      },
      {
        "fieldName": "host_sex",
        "capitalize": "",
        "ontology_id": "MIXS:0000811",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Gender or physical sex of the host.",
        "guidance": "Expected value: enumeration. Occurrence: 1. Position: 11.0. This field is used in: 6 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal",
        "examples": "non-binary",
        "schema:ItemList": {
          "female": {},
          "hermaphrodite": {},
          "non-binary": {},
          "male": {},
          "transgender": {},
          "transgender (female to male)": {},
          "transgender (male to female)": {},
          "undeclared": {}
        }
      },
      {
        "fieldName": "host_shape",
        "capitalize": "",
        "ontology_id": "MIXS:0000261",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Morphological shape of host",
        "guidance": "Expected value: shape. Occurrence: 1. Position: 34.0. This field is used uniquely in: host-associated",
        "examples": "round"
      },
      {
        "fieldName": "host_subject_id",
        "capitalize": "",
        "ontology_id": "MIXS:0000861",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "A unique identifier by which each subject can be referred to, de-identified.",
        "guidance": "Expected value: unique identifier. Occurrence: 1. Position: 8.0. This field is used in: 6 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal",
        "examples": "MPI123"
      },
      {
        "fieldName": "host_subspecf_genlin",
        "capitalize": "",
        "ontology_id": "MIXS:0001318",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Information about the genetic distinctness of the host organism below the subspecies level, e.g., serovar, serotype, biotype, ecotype, or any relevant genetic typing schemes like Group I plasmid. Subspecies should not be recorded in this term, but in the NCBI taxonomy. Supply both the lineage name and the lineage rank separated by a colon, e.g., biovar:abc123.",
        "guidance": "Expected value: Genetic lineage below lowest rank of NCBI taxonomy, which is subspecies, e.g. serovar, biotype, ecotype, plus genetic lineage name.. Occurrence: m. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "subvariety:glabrum"
      },
      {
        "fieldName": "host_substrate",
        "capitalize": "",
        "ontology_id": "MIXS:0000252",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The growth substrate of the host.",
        "guidance": "Expected value: substrate name. Occurrence: 1. Position: 23.0. This field is used uniquely in: host-associated",
        "examples": "rock"
      },
      {
        "fieldName": "host_symbiont",
        "capitalize": "",
        "ontology_id": "MIXS:0001298",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The taxonomic name of the organism(s) found living in mutualistic, commensalistic, or parasitic symbiosis with the specific host.",
        "guidance": "Expected value: species name or common name. Occurrence: m. This field is used in: 7 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, plant-associated",
        "examples": "flukeworms"
      },
      {
        "fieldName": "host_taxid",
        "capitalize": "",
        "ontology_id": "MIXS:0000250",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "NCBI taxon id of the host, e.g. 9606",
        "guidance": "Expected value: NCBI taxon identifier. Occurrence: 1. Position: 7.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "7955"
      },
      {
        "fieldName": "host_tot_mass",
        "capitalize": "",
        "ontology_id": "MIXS:0000263",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Total mass of the host at collection, the unit depends on host",
        "guidance": "Expected value: measurement value. Preferred unit: kilogram, gram. Occurrence: 1. Position: 17.0. This field is used in: 7 packages: host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, plant-associated",
        "examples": "2500 gram"
      },
      {
        "fieldName": "misc_param",
        "capitalize": "",
        "ontology_id": "MIXS:0000752",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Any other measurement performed or parameter collected, that is not listed here",
        "guidance": "Expected value: parameter name;measurement value. Occurrence: m. Position: 1.0. This field is used in: 16 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, soil, wastewater_sludge, water",
        "examples": "Bicarbonate ion concentration;2075 micromole per kilogram"
      },
      {
        "fieldName": "organism_count",
        "capitalize": "",
        "ontology_id": "MIXS:0000103",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Total cell count of any organism (or group of organisms) per gram, volume or area of sample, should include name of organism followed by count. The method that was used for the enumeration (e.g. qPCR, atp, mpn, etc.) Should also be provided. (example: total prokaryotes; 3.5e7 cells per ml; qpcr)",
        "guidance": "Expected value: organism name;measurement value;enumeration. Preferred unit: number of cells per cubic meter, number of cells per milliliter, number of cells per cubic centimeter. Occurrence: m. Position: 1.0. This field is used in: 16 packages: air, built environment, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "total prokaryotes;3.5e7 cells per milliliter;qPCR",
        "schema:ItemList": {
          "ATP": {},
          "MPN": {},
          "other": {}
        }
      },
      {
        "fieldName": "oxy_stat_samp",
        "capitalize": "",
        "ontology_id": "MIXS:0000753",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Oxygenation status of sample",
        "guidance": "Expected value: enumeration. Occurrence: 1. Position: 1.0. This field is used in: 15 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "aerobic",
        "schema:ItemList": {
          "aerobic": {},
          "anaerobic": {},
          "other": {}
        }
      },
      {
        "fieldName": "perturbation",
        "capitalize": "",
        "ontology_id": "MIXS:0000754",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Type of perturbation, e.g. chemical administration, physical disturbance, etc., coupled with perturbation regimen including how many times the perturbation was repeated, how long each perturbation lasted, and the start and end time of the entire perturbation period; can include multiple perturbation types",
        "guidance": "Expected value: perturbation type name;perturbation interval and duration. Occurrence: m. Position: 1.0. This field is used in: 13 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "antibiotic addition;R2/2018-05-11T14:30Z/2018-05-11T19:30Z/P1H30M"
      },
      {
        "fieldName": "salinity",
        "capitalize": "",
        "ontology_id": "MIXS:0000183",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "The total concentration of all dissolved salts in a liquid or solid sample. While salinity can be measured by a complete chemical analysis, this method is difficult and time consuming. More often, it is instead derived from the conductivity measurement. This is known as practical salinity. These derivations compare the specific conductance of the sample to a salinity standard such as seawater.",
        "guidance": "Expected value: measurement value. Preferred unit: practical salinity unit, percentage. Occurrence: 1. Position: 1.0. This field is used in: 15 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "25 practical salinity unit"
      },
      {
        "fieldName": "samp_capt_status",
        "capitalize": "",
        "ontology_id": "MIXS:0000860",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Reason for the sample",
        "guidance": "Expected value: enumeration. Occurrence: 1. Position: 5.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "farm sample",
        "schema:ItemList": {
          "active surveillance in response to an outbreak": {},
          "active surveillance not initiated by an outbreak": {},
          "farm sample": {},
          "market sample": {},
          "other": {}
        }
      },
      {
        "fieldName": "samp_dis_stage",
        "capitalize": "",
        "ontology_id": "MIXS:0000249",
        "datatype": "select",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Stage of the disease at the time of sample collection, e.g. inoculation, penetration, infection, growth and reproduction, dissemination of pathogen.",
        "guidance": "Expected value: enumeration. Occurrence: 1. Position: 6.0. This field is used in: 2 packages: host-associated, plant-associated",
        "examples": "infection",
        "schema:ItemList": {
          "dissemination": {},
          "growth and reproduction": {},
          "infection": {},
          "inoculation": {},
          "penetration": {},
          "other": {}
        }
      },
      {
        "fieldName": "samp_salinity",
        "capitalize": "",
        "ontology_id": "MIXS:0000109",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Salinity is the total concentration of all dissolved salts in a liquid or solid (in the form of an extract obtained by centrifugation) sample. While salinity can be measured by a complete chemical analysis, this method is difficult and time consuming. More often, it is instead derived from the conductivity measurement. This is known as practical salinity. These derivations compare the specific conductance of the sample to a salinity standard such as seawater",
        "guidance": "Expected value: measurement value. Preferred unit: milligram per liter, practical salinity unit, percentage. Occurrence: 1. Position: 1.0. This field is used in: 11 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, plant-associated, wastewater_sludge",
        "examples": "1 milligram per liter"
      },
      {
        "fieldName": "samp_store_dur",
        "capitalize": "",
        "ontology_id": "MIXS:0000116",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Duration for which the sample was stored",
        "guidance": "Expected value: duration. Occurrence: 1. Position: 1.0. This field is used in: 15 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "P1Y6M"
      },
      {
        "fieldName": "samp_store_loc",
        "capitalize": "",
        "ontology_id": "MIXS:0000755",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "",
        "description": "Location at which sample was stored, usually name of a specific freezer/room",
        "guidance": "Expected value: location name. Occurrence: 1. Position: 1.0. This field is used in: 15 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "Freezer no:5"
      },
      {
        "fieldName": "samp_store_temp",
        "capitalize": "",
        "ontology_id": "MIXS:0000110",
        "datatype": "xs:token",
        "source": "",
        "dataStatus": null,
        "xs:minInclusive": "",
        "xs:maxInclusive": "",
        "requirement": "required",
        "description": "Temperature at which sample was stored, e.g. -80 degree Celsius",
        "guidance": "Expected value: measurement value. Preferred unit: degree Celsius. Occurrence: 1. Position: 1.0. This field is used in: 15 packages: air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids_swabs, microbial mat_biofilm, miscellaneous natural or artificial environment, plant-associated, sediment, wastewater_sludge, water",
        "examples": "-80 degree Celsius"
      }
    ]
  }
]