const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = (env, argv) => {
  var config = {
    context: path.resolve(__dirname),
    entry: './index.js',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'scripts/[name].js',
    },
    externals: {
      // Schemas lib external to this webpack build. Imported in html file.
      schemas: 'schemas',
    },
    plugins: [
      new HtmlWebpackPlugin({
        template: './index.html',
      }),
      new CopyPlugin({
        patterns: [
          {
            from: 'main.html',
          },
        ],
      }),
    ],
    module: {
      rules: [
        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader'],
        },
        {
          test: /\.html$/,
          exclude: path.resolve(__dirname, 'index.html'),
          type: 'asset/source',
        },
        {
          test: /\.(png|svg|jpg|jpeg|gif)$/i,
          type: 'asset/resource',
          generator: {
            // Will throw a file not found error if ``dist`` folder not in
            // ``{project root}/web/``.
            filename: '../[file]',
            emit: false,
          },
        },
      ],
    },
    devServer: {
      hot: true,
      watchFiles: [path.resolve(__dirname, 'index.html')],
    },
  };

  // Difficult to run two webpack instances on a single dev server (i.e., this
  // file, and the other webpack file that builds schemas). So for dev servers,
  // we will insert all schema content into the webpack build generated by this
  // file, and this singular build serves the entirety of the application. This
  // is fine, because the whole point of having a separate build for schema
  // content was to reduce production build times when users are only editing
  // schema files (and not the rest of the application), but the dev server
  // already gets around this problem through hot loading.
  if (argv.mode === 'development') {
    config.devtool = 'eval-source-map';
    // The schemas lib will come from a direct import of the javascript, instead
    // of embedding an external lib into the html
    config.resolve = {
      alias: {
        schemas: path.resolve(__dirname, 'schemas.js'),
      },
    };
    delete config.externals;
    // Need pdf SOPs that schema build previously supplied
    config.plugins.push(
      new CopyPlugin({
        patterns: [
          {
            context: 'templates',
            from: '**/*.pdf',
            to: 'templates/[path][name][ext]',
          },
        ],
      })
    );
    // False emits don't play nice with dev servers either
    for (const rule of config.module.rules) {
      if (rule.hasOwnProperty('generator')) {
        delete rule.generator.filename;
        delete rule.generator.emit;
      }
    }
  }

  return config;
};
